<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

class GetImportSubscribersResponse implements \JsonSerializable
{
    /** @var ImportStatus|SdkNotGiven */
    public readonly ImportStatus|SdkNotGiven $data;

    /**
     * @param ImportStatus|SdkNotGiven $data
     */
    public function __construct(
        ImportStatus|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, ImportStatus::class) : SdkNotGiven::Value),
        );
    }
}

class ImportSubscribersResponse implements \JsonSerializable
{
    /** @var ImportStatus|SdkNotGiven */
    public readonly ImportStatus|SdkNotGiven $data;

    /**
     * @param ImportStatus|SdkNotGiven $data
     */
    public function __construct(
        ImportStatus|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, ImportStatus::class) : SdkNotGiven::Value),
        );
    }
}

class StopImportSubscribersResponse implements \JsonSerializable
{
    /** @var ImportStatus|SdkNotGiven */
    public readonly ImportStatus|SdkNotGiven $data;

    /**
     * @param ImportStatus|SdkNotGiven $data
     */
    public function __construct(
        ImportStatus|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, ImportStatus::class) : SdkNotGiven::Value),
        );
    }
}

class GetImportSubscriberLogsResponse implements \JsonSerializable
{
    /** @var string|SdkNotGiven */
    public readonly string|SdkNotGiven $data;

    /**
     * @param string|SdkNotGiven $data
     */
    public function __construct(
        string|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::stringValue($data->data) : SdkNotGiven::Value),
        );
    }
}

class Import
{
    /**
     * Retrieves the current status of subscriber imports. Use this endpoint to check the import status without submitting an import request.
     *
     * returns import status.
     *
     * @return GetImportSubscribersResponse
     */
    public static function getImportSubscribers(ClientConfig $clientConfig, ?RequestOptions $requestOptions = null): GetImportSubscribersResponse
    {

        return SdkClient::typedData(SdkClient::request('GET', "/import/subscribers", $clientConfig, returnType: GetImportSubscribersResponse::class, decoder: 'json', operationId: 'getImportSubscribers', requestOptions: $requestOptions), GetImportSubscribersResponse::class);
    }


    /**
     * Uploads and imports a ZIP file containing one or more CSV files of subscribers. Send the upload as `multipart/form-data`; `params` can contain import settings as a JSON string. Use GET /import/subscribers to retrieve import status.
     *
     * handles the uploading and bulk importing of a ZIP file of one or more CSV files. params: JSON string containing import parameters for more detail https://listmonk.app/docs/apis/import/#params-json-string · file: File for upload.
     *
     * @param string|SdkNotGiven $params
     * @param SdkUploadFile|SdkNotGiven $file
     * @return ImportSubscribersResponse
     */
    public static function importSubscribers(ClientConfig $clientConfig, string|SdkNotGiven $params = SdkNotGiven::Value, SdkUploadFile|SdkNotGiven $file = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): ImportSubscribersResponse
    {

        return SdkClient::typedData(SdkClient::request('POST', "/import/subscribers", $clientConfig, body: ['params' => $params, 'file' => $file], contentType: 'multipart/form-data', returnType: ImportSubscribersResponse::class, decoder: 'json', operationId: 'importSubscribers', requestOptions: $requestOptions), ImportSubscribersResponse::class);
    }


    /**
     * Sends a stop signal to the subscriber importer. Use this endpoint to request that an ongoing import stop.
     *
     * sends a stop signal to the importer.
     *
     * @return StopImportSubscribersResponse
     */
    public static function stopImportSubscribers(ClientConfig $clientConfig, ?RequestOptions $requestOptions = null): StopImportSubscribersResponse
    {

        return SdkClient::typedData(SdkClient::request('DELETE', "/import/subscribers", $clientConfig, returnType: StopImportSubscribersResponse::class, decoder: 'json', operationId: 'stopImportSubscribers', requestOptions: $requestOptions), StopImportSubscribersResponse::class);
    }


    /**
     * Retrieves logs from an ongoing subscriber import. Use this endpoint to inspect import activity while the import is running.
     *
     * returns import logs from an ongoing import
     *
     * @return GetImportSubscriberLogsResponse
     */
    public static function getImportSubscriberLogs(ClientConfig $clientConfig, ?RequestOptions $requestOptions = null): GetImportSubscriberLogsResponse
    {

        return SdkClient::typedData(SdkClient::request('GET', "/import/subscribers/logs", $clientConfig, returnType: GetImportSubscriberLogsResponse::class, decoder: 'json', operationId: 'getImportSubscriberLogs', requestOptions: $requestOptions), GetImportSubscriberLogsResponse::class);
    }
}
