<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

class GetLogsResponse implements \JsonSerializable
{
    /** @var list<string>|SdkNotGiven */
    public readonly array|SdkNotGiven $data;

    /**
     * @param list<string>|SdkNotGiven $data
     */
    public function __construct(
        array|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? array_values(array_map(static fn($item) => SdkClient::stringValue($item), SdkClient::arrayValue($data->data))) : SdkNotGiven::Value),
        );
    }
}

class Logs
{
    /**
     * Lists log entries currently stored in the log buffer. Use this endpoint to retrieve the buffered entries as an array of strings.
     *
     * returns the log entries stored in the log buffer
     *
     * @return GetLogsResponse
     */
    public static function getLogs(ClientConfig $clientConfig, ?RequestOptions $requestOptions = null): GetLogsResponse
    {

        return SdkClient::typedData(SdkClient::request('GET', "/logs", $clientConfig, returnType: GetLogsResponse::class, decoder: 'json', operationId: 'getLogs', requestOptions: $requestOptions), GetLogsResponse::class);
    }
}
