<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

class GetMediaResponse implements \JsonSerializable
{
    /** @var list<MediaFileObject>|SdkNotGiven */
    public readonly array|SdkNotGiven $data;

    /**
     * @param list<MediaFileObject>|SdkNotGiven $data
     */
    public function __construct(
        array|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? array_values(array_map(static fn ($item) => SdkClient::hydrateClass($item, MediaFileObject::class), SdkClient::arrayValue($data->data))) : SdkNotGiven::Value),
        );
    }
}

class UploadMediaResponse implements \JsonSerializable
{
    /** @var MediaFileObject|SdkNotGiven */
    public readonly MediaFileObject|SdkNotGiven $data;

    /**
     * @param MediaFileObject|SdkNotGiven $data
     */
    public function __construct(
        MediaFileObject|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, MediaFileObject::class) : SdkNotGiven::Value),
        );
    }
}

class GetMediaByIdResponse implements \JsonSerializable
{
    /** @var MediaFileObject|SdkNotGiven */
    public readonly MediaFileObject|SdkNotGiven $data;

    /**
     * @param MediaFileObject|SdkNotGiven $data
     */
    public function __construct(
        MediaFileObject|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, MediaFileObject::class) : SdkNotGiven::Value),
        );
    }
}

class DeleteMediaByIdResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $data;

    /**
     * @param bool|SdkNotGiven $data
     */
    public function __construct(
        bool|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::boolValue($data->data) : SdkNotGiven::Value),
        );
    }
}

class Media
{
    /**
     * Lists uploaded media. Use this endpoint to retrieve the available media records and their file details.
     *
     * handles retrieval of uploaded media.
     *
     * @return GetMediaResponse
     */
    public static function getMedia(ClientConfig $clientConfig, ?RequestOptions $requestOptions = null): GetMediaResponse
    {

        return SdkClient::typedData(SdkClient::request('GET', "/media", $clientConfig, returnType: GetMediaResponse::class, decoder: 'json', operationId: 'getMedia', requestOptions: $requestOptions), GetMediaResponse::class);
    }


    /**
     * Uploads a media file. Send the file as a binary value using `multipart/form-data`; the request body schema does not define additional metadata fields.
     *
     * handles media file uploads.
     *
     * @param string|SdkNotGiven $body
     * @return UploadMediaResponse
     */
    public static function uploadMedia(ClientConfig $clientConfig, string|SdkNotGiven $body = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): UploadMediaResponse
    {

        return SdkClient::typedData(SdkClient::request('POST', "/media", $clientConfig, body: $body, contentType: 'multipart/form-data', returnType: UploadMediaResponse::class, decoder: 'json', operationId: 'uploadMedia', requestOptions: $requestOptions), UploadMediaResponse::class);
    }


    /**
     * Retrieves an uploaded media record by its identifier. Use the media identifier to access the record's file details and URLs.
     *
     * handles retrieval of uploaded media. id: media file id
     *
     * @param int $id
     * @return GetMediaByIdResponse
     */
    public static function getMediaById(ClientConfig $clientConfig, int $id, ?RequestOptions $requestOptions = null): GetMediaByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('GET', "/media/" . SdkClient::encodePathSegment($id) . "", $clientConfig, returnType: GetMediaByIdResponse::class, decoder: 'json', operationId: 'getMediaById', requestOptions: $requestOptions), GetMediaByIdResponse::class);
    }


    /**
     * Deletes an uploaded media record. Supply the media identifier for the record you want to remove.
     *
     * handles deletion of uploaded media. id: The id value of the list you want to delete.
     *
     * @param int $id
     * @return DeleteMediaByIdResponse
     */
    public static function deleteMediaById(ClientConfig $clientConfig, int $id, ?RequestOptions $requestOptions = null): DeleteMediaByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('DELETE', "/media/" . SdkClient::encodePathSegment($id) . "", $clientConfig, returnType: DeleteMediaByIdResponse::class, decoder: 'json', operationId: 'deleteMediaById', requestOptions: $requestOptions), DeleteMediaByIdResponse::class);
    }
}
