<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

class GetHealthCheckResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $data;

    /**
     * @param bool|SdkNotGiven $data
     */
    public function __construct(
        bool|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::boolValue($data->data) : SdkNotGiven::Value),
        );
    }
}

class GetServerConfigResponse implements \JsonSerializable
{
    /** @var ServerConfig|SdkNotGiven */
    public readonly ServerConfig|SdkNotGiven $data;

    /**
     * @param ServerConfig|SdkNotGiven $data
     */
    public function __construct(
        ServerConfig|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, ServerConfig::class) : SdkNotGiven::Value),
        );
    }
}

class GetI18nLangResponse implements \JsonSerializable
{
    /** @var LanguagePack|SdkNotGiven */
    public readonly LanguagePack|SdkNotGiven $data;

    /**
     * @param LanguagePack|SdkNotGiven $data
     */
    public function __construct(
        LanguagePack|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, LanguagePack::class) : SdkNotGiven::Value),
        );
    }
}

class GetDashboardChartsResponse implements \JsonSerializable
{
    /** @var DashboardChart|SdkNotGiven */
    public readonly DashboardChart|SdkNotGiven $data;

    /**
     * @param DashboardChart|SdkNotGiven $data
     */
    public function __construct(
        DashboardChart|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, DashboardChart::class) : SdkNotGiven::Value),
        );
    }
}

class GetDashboardCountsResponse implements \JsonSerializable
{
    /** @var DashboardCount|SdkNotGiven */
    public readonly DashboardCount|SdkNotGiven $data;

    /**
     * @param DashboardCount|SdkNotGiven $data
     */
    public function __construct(
        DashboardCount|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, DashboardCount::class) : SdkNotGiven::Value),
        );
    }
}

class Miscellaneous
{
    /**
     * Returns the service health-check result. Use the boolean `data` value to determine whether the service is responding.
     *
     * healthcheck endpoint
     *
     * @return GetHealthCheckResponse
     */
    public static function getHealthCheck(ClientConfig $clientConfig, ?RequestOptions $requestOptions = null): GetHealthCheckResponse
    {

        return SdkClient::typedData(SdkClient::request('GET', "/health", $clientConfig, returnType: GetHealthCheckResponse::class, decoder: 'json', operationId: 'getHealthCheck', requestOptions: $requestOptions), GetHealthCheckResponse::class);
    }


    /**
     * Returns the general server configuration. Use this endpoint to retrieve the configuration object exposed by the server.
     *
     * returns general server config.
     *
     * @return GetServerConfigResponse
     */
    public static function getServerConfig(ClientConfig $clientConfig, ?RequestOptions $requestOptions = null): GetServerConfigResponse
    {

        return SdkClient::typedData(SdkClient::request('GET', "/config", $clientConfig, returnType: GetServerConfigResponse::class, decoder: 'json', operationId: 'getServerConfig', requestOptions: $requestOptions), GetServerConfigResponse::class);
    }


    /**
     * Returns the JSON language pack for the requested language code. Supply `lang` to select the language pack to retrieve.
     *
     * returns the JSON language pack given the language code lang: JSON language pack required
     *
     * @param string $lang
     * @return GetI18nLangResponse
     */
    public static function getI18nLang(ClientConfig $clientConfig, string $lang, ?RequestOptions $requestOptions = null): GetI18nLangResponse
    {

        return SdkClient::typedData(SdkClient::request('GET', "/lang/" . SdkClient::encodePathSegment($lang) . "", $clientConfig, returnType: GetI18nLangResponse::class, decoder: 'json', operationId: 'getI18nLang', requestOptions: $requestOptions), GetI18nLangResponse::class);
    }


    /**
     * Returns chart data points for the dashboard. Use the `link_clicks` and `campaign_views` data to render the corresponding dashboard charts.
     *
     * returns chart data points to render on the dashboard.
     *
     * @return GetDashboardChartsResponse
     */
    public static function getDashboardCharts(ClientConfig $clientConfig, ?RequestOptions $requestOptions = null): GetDashboardChartsResponse
    {

        return SdkClient::typedData(SdkClient::request('GET', "/dashboard/charts", $clientConfig, returnType: GetDashboardChartsResponse::class, decoder: 'json', operationId: 'getDashboardCharts', requestOptions: $requestOptions), GetDashboardChartsResponse::class);
    }


    /**
     * Returns statistics counts for the dashboard. Use the returned counts to display summary statistics in the dashboard.
     *
     * returns stats counts to show on the dashboard
     *
     * @return GetDashboardCountsResponse
     */
    public static function getDashboardCounts(ClientConfig $clientConfig, ?RequestOptions $requestOptions = null): GetDashboardCountsResponse
    {

        return SdkClient::typedData(SdkClient::request('GET', "/dashboard/counts", $clientConfig, returnType: GetDashboardCountsResponse::class, decoder: 'json', operationId: 'getDashboardCounts', requestOptions: $requestOptions), GetDashboardCountsResponse::class);
    }
}
