<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

class GetPublicListsResponseItem implements \JsonSerializable
{
    /** @var string|SdkNotGiven */
    public readonly string|SdkNotGiven $uuid;
    /** @var string|SdkNotGiven */
    public readonly string|SdkNotGiven $name;

    /**
     * @param string|SdkNotGiven $uuid
     * @param string|SdkNotGiven $name
     */
    public function __construct(
        string|SdkNotGiven $uuid = SdkNotGiven::Value,
        string|SdkNotGiven $name = SdkNotGiven::Value,
    ) {
        $this->uuid = $uuid;
        $this->name = $name;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->uuid !== SdkNotGiven::Value) {
            $values["uuid"] = $this->uuid;
        }
        if ($this->name !== SdkNotGiven::Value) {
            $values["name"] = $this->name;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            uuid: (property_exists($data, "uuid") ? SdkClient::stringValue($data->uuid) : SdkNotGiven::Value),
            name: (property_exists($data, "name") ? SdkClient::stringValue($data->name) : SdkNotGiven::Value),
        );
    }
}

class HandlePublicSubscriptionResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $hasOptin;

    /**
     * @param bool|SdkNotGiven $hasOptin
     */
    public function __construct(
        bool|SdkNotGiven $hasOptin = SdkNotGiven::Value,
    ) {
        $this->hasOptin = $hasOptin;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->hasOptin !== SdkNotGiven::Value) {
            $values["has_optin"] = $this->hasOptin;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            hasOptin: (property_exists($data, "has_optin") ? SdkClient::boolValue($data->has_optin) : SdkNotGiven::Value),
        );
    }
}

class PublicResource
{
    /**
     * Lists the public mailing lists with their minimal identifying fields. Use this endpoint to retrieve each list's `uuid` and `name` for display or subscription workflows.
     *
     * returns the list of public lists with minimal fields
     *
     * @return list<array<array-key,mixed>>
     */
    public static function getPublicLists(ClientConfig $clientConfig, ?RequestOptions $requestOptions = null): array
    {

        return array_values(array_map(static fn($item) => SdkClient::stringMapValue($item), SdkClient::arrayValue(SdkClient::request('GET', "/public/lists", $clientConfig, decoder: 'json', operationId: 'getPublicLists', requestOptions: $requestOptions)->data)));
    }


    /**
     * Submits a subscription request through the public API. Include `email` and optionally `name` and `list_uuids` in the request body; the schema does not mark any fields as required. A 200 response indicates whether opt-in is required in `has_optin`.
     *
     * handles subscription requests coming from public API calls.
     *
     * @param string|SdkNotGiven $name
     * @param string|SdkNotGiven $email
     * @param list<string>|SdkNotGiven $listUuids
     * @return HandlePublicSubscriptionResponse
     */
    public static function handlePublicSubscription(ClientConfig $clientConfig, string|SdkNotGiven $name = SdkNotGiven::Value, string|SdkNotGiven $email = SdkNotGiven::Value, array|SdkNotGiven $listUuids = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): HandlePublicSubscriptionResponse
    {

        return SdkClient::typedData(SdkClient::request('POST', "/public/subscription", $clientConfig, body: ['name' => $name, 'email' => $email, 'list_uuids' => $listUuids], returnType: HandlePublicSubscriptionResponse::class, decoder: 'json', operationId: 'handlePublicSubscription', requestOptions: $requestOptions), HandlePublicSubscriptionResponse::class);
    }
}
