<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

trait CampaignsMethodsPart1
{
    /**
     * Lists campaigns, with optional filters for status and tags and optional sorting controls. Use `query` to apply custom SQL criteria, or use `page` and `per_page` to paginate the results. Set `no_body` to true to request a response without body content.
     *
     * handles retrieval of campaigns status: Filter campaigns by status. Multiple status values can be specified by repeating the parameter · noBody: When set to true, returns response without body content · page: Page number for paginated results. · perPage: Number of items per page. Use an integer for specific page size or 'all' to retrieve all results · tags: Filter campaigns by tags. Multiple tags can be specified by repeating the parameter · order: Determines the sort order of results. ASC for ascending, DESC for descending order · orderBy: Specifies the field by which to sort the campaigns. Available options are 'name', 'status', 'created_at', and 'updated_at' · query: SQL query expression to filter campaigns by custom criteria
     *
     * @param list<string>|SdkNotGiven $status
     * @param bool|SdkNotGiven $noBody
     * @param int|SdkNotGiven $page
     * @param int|GetCampaignsPerPageEnum|SdkNotGiven $perPage
     * @param list<string>|SdkNotGiven $tags
     * @param GetCampaignsOrder|SdkNotGiven $order
     * @param GetCampaignsOrderBy|SdkNotGiven $orderBy
     * @param string|SdkNotGiven $query
     * @return GetCampaignsResponse
     */
    public static function getCampaigns(ClientConfig $clientConfig, array|SdkNotGiven $status = SdkNotGiven::Value, bool|SdkNotGiven $noBody = SdkNotGiven::Value, int|SdkNotGiven $page = SdkNotGiven::Value, int|GetCampaignsPerPageEnum|string|SdkNotGiven $perPage = SdkNotGiven::Value, array|SdkNotGiven $tags = SdkNotGiven::Value, GetCampaignsOrder|SdkNotGiven $order = SdkNotGiven::Value, GetCampaignsOrderBy|SdkNotGiven $orderBy = SdkNotGiven::Value, string|SdkNotGiven $query = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): GetCampaignsResponse
    {

        return SdkClient::typedData(SdkClient::request('GET', "/campaigns", $clientConfig, query: ['status' => new SdkQueryValue($status, "form", true), 'no_body' => new SdkQueryValue($noBody, "form", true), 'page' => new SdkQueryValue($page, "form", true), 'per_page' => new SdkQueryValue($perPage, "form", true), 'tags' => new SdkQueryValue($tags, "form", true), 'order' => new SdkQueryValue($order, "form", true), 'order_by' => new SdkQueryValue($orderBy, "form", true), 'query' => new SdkQueryValue($query, "form", true)], returnType: GetCampaignsResponse::class, decoder: 'json', operationId: 'getCampaigns', requestOptions: $requestOptions), GetCampaignsResponse::class);
    }


    /**
     * Creates a campaign from the campaign details supplied in the request body. Provide fields such as `name`, `subject`, and `lists` to define the campaign; all body fields are optional in the schema. A successful response contains the new campaign object.
     *
     * handles campaign creation name: Optional `string` value serialized in the `name` wire field. · subject: Optional `string` value serialized in the `subject` wire field. · lists: Optional array value serialized in the `lists` wire field. · fromEmail: Optional `string` value serialized in the `from_email` wire field. · contentType: Optional `string` value serialized in the `content_type` wire field. · messenger: Optional `string` value serialized in the `messenger` wire field. · type: Optional `string` value serialized in the `type` wire field. · tags: Optional array value serialized in the `tags` wire field. · sendLater: Optional `boolean` value serialized in the `send_later` wire field. · sendAt: Optional object value serialized in the `send_at` wire field.
     *
     * @param string|SdkNotGiven $name
     * @param string|SdkNotGiven $subject
     * @param list<float>|SdkNotGiven $lists
     * @param string|SdkNotGiven $fromEmail
     * @param string|SdkNotGiven $contentType
     * @param string|SdkNotGiven $messenger
     * @param string|SdkNotGiven $type
     * @param list<string>|SdkNotGiven $tags
     * @param bool|SdkNotGiven $sendLater
     * @param CreateCampaignSendAt|SdkNotGiven $sendAt
     * @return CreateCampaignResponse
     */
    public static function createCampaign(ClientConfig $clientConfig, string|SdkNotGiven $name = SdkNotGiven::Value, string|SdkNotGiven $subject = SdkNotGiven::Value, array|SdkNotGiven $lists = SdkNotGiven::Value, string|SdkNotGiven $fromEmail = SdkNotGiven::Value, string|SdkNotGiven $contentType = SdkNotGiven::Value, string|SdkNotGiven $messenger = SdkNotGiven::Value, string|SdkNotGiven $type = SdkNotGiven::Value, array|SdkNotGiven $tags = SdkNotGiven::Value, bool|SdkNotGiven $sendLater = SdkNotGiven::Value, CreateCampaignSendAt|SdkNotGiven $sendAt = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): CreateCampaignResponse
    {

        return SdkClient::typedData(SdkClient::request('POST', "/campaigns", $clientConfig, body: ['name' => $name, 'subject' => $subject, 'lists' => $lists, 'from_email' => $fromEmail, 'content_type' => $contentType, 'messenger' => $messenger, 'type' => $type, 'tags' => $tags, 'send_later' => $sendLater, 'send_at' => $sendAt], returnType: CreateCampaignResponse::class, decoder: 'json', operationId: 'createCampaign', requestOptions: $requestOptions), CreateCampaignResponse::class);
    }


    /**
     * Retrieves a campaign by its identifier. Use `id` to select the campaign, and set `no_body` to true if you want the response without body content.
     *
     * handles retrieval of campaigns. id: The id value of the campaign you want to get. · noBody: boolean flag for response with/without body
     *
     * @param int $id
     * @param bool|SdkNotGiven $noBody
     * @return GetCampaignByIdResponse
     */
    public static function getCampaignById(ClientConfig $clientConfig, int $id, bool|SdkNotGiven $noBody = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): GetCampaignByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('GET', "/campaigns/" . SdkClient::encodePathSegment($id) . "", $clientConfig, query: ['no_body' => new SdkQueryValue($noBody, "form", true)], returnType: GetCampaignByIdResponse::class, decoder: 'json', operationId: 'getCampaignById', requestOptions: $requestOptions), GetCampaignByIdResponse::class);
    }


    /**
     * Replaces campaign details for the campaign identified by `id`. Supply the campaign fields you want to set, such as `name`, `subject`, or `lists`; the schema does not require any particular body fields. A successful response contains the updated campaign object.
     *
     * handle updation of campaign id: the id value of campaign you want to update · name: Optional `string` value serialized in the `name` wire field. · subject: Optional `string` value serialized in the `subject` wire field. · lists: Optional array value serialized in the `lists` wire field. · fromEmail: Optional `string` value serialized in the `from_email` wire field. · contentType: Optional `string` value serialized in the `content_type` wire field. · messenger: Optional `string` value serialized in the `messenger` wire field. · type: Optional `string` value serialized in the `type` wire field. · tags: Optional array value serialized in the `tags` wire field. · sendLater: Optional `boolean` value serialized in the `send_later` wire field. · sendAt: Optional object value serialized in the `send_at` wire field.
     *
     * @param int $id
     * @param string|SdkNotGiven $name
     * @param string|SdkNotGiven $subject
     * @param list<float>|SdkNotGiven $lists
     * @param string|SdkNotGiven $fromEmail
     * @param string|SdkNotGiven $contentType
     * @param string|SdkNotGiven $messenger
     * @param string|SdkNotGiven $type
     * @param list<string>|SdkNotGiven $tags
     * @param bool|SdkNotGiven $sendLater
     * @param UpdateCampaignByIdSendAt|SdkNotGiven $sendAt
     * @return UpdateCampaignByIdResponse
     */
    public static function updateCampaignById(ClientConfig $clientConfig, int $id, string|SdkNotGiven $name = SdkNotGiven::Value, string|SdkNotGiven $subject = SdkNotGiven::Value, array|SdkNotGiven $lists = SdkNotGiven::Value, string|SdkNotGiven $fromEmail = SdkNotGiven::Value, string|SdkNotGiven $contentType = SdkNotGiven::Value, string|SdkNotGiven $messenger = SdkNotGiven::Value, string|SdkNotGiven $type = SdkNotGiven::Value, array|SdkNotGiven $tags = SdkNotGiven::Value, bool|SdkNotGiven $sendLater = SdkNotGiven::Value, UpdateCampaignByIdSendAt|SdkNotGiven $sendAt = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): UpdateCampaignByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('PUT', "/campaigns/" . SdkClient::encodePathSegment($id) . "", $clientConfig, body: ['name' => $name, 'subject' => $subject, 'lists' => $lists, 'from_email' => $fromEmail, 'content_type' => $contentType, 'messenger' => $messenger, 'type' => $type, 'tags' => $tags, 'send_later' => $sendLater, 'send_at' => $sendAt], returnType: UpdateCampaignByIdResponse::class, decoder: 'json', operationId: 'updateCampaignById', requestOptions: $requestOptions), UpdateCampaignByIdResponse::class);
    }


    /**
     * Deletes the campaign identified by `id`. Use the campaign's integer identifier to select the campaign to remove. The response contains a boolean result.
     *
     * deletes specified campaign id: The id value of the campaign you want to get.
     *
     * @param int $id
     * @return DeleteCampaignByIdResponse
     */
    public static function deleteCampaignById(ClientConfig $clientConfig, int $id, ?RequestOptions $requestOptions = null): DeleteCampaignByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('DELETE', "/campaigns/" . SdkClient::encodePathSegment($id) . "", $clientConfig, returnType: DeleteCampaignByIdResponse::class, decoder: 'json', operationId: 'deleteCampaignById', requestOptions: $requestOptions), DeleteCampaignByIdResponse::class);
    }


    /**
     * Lists statistics for the campaign identified by `campaign_id`. Supply the campaign ID as a number to retrieve its running campaign statistics. The response contains statistics for the requested campaign.
     *
     * returns stats of a given set of campaign IDs. campaignId: Campaign IDs to get stats for.
     *
     * @param float $campaignId
     * @return GetRunningCampaignStatsResponse
     */
    public static function getRunningCampaignStats(ClientConfig $clientConfig, float $campaignId, ?RequestOptions $requestOptions = null): GetRunningCampaignStatsResponse
    {

        return SdkClient::typedData(SdkClient::request('GET', "/campaigns/running/stats", $clientConfig, query: ['campaign_id' => new SdkQueryValue($campaignId, "form", true)], returnType: GetRunningCampaignStatsResponse::class, decoder: 'json', operationId: 'getRunningCampaignStats', requestOptions: $requestOptions), GetRunningCampaignStatsResponse::class);
    }


    /**
     * Retrieves campaign analytics for the requested statistic type and date range. Use `type` to select links, views, clicks, or bounces, and provide `from`, `to`, and `id` to scope the results. The response contains counts over time for the specified campaign ID or IDs.
     *
     * retrieves view counts for a campaign. type: type of stats, either links, view, click or bounce · from: start value of date range · to: end value of date range · id: campaign id/s to retrive view counts
     *
     * @param GetCampaignAnalyticsType $type
     * @param string $from
     * @param string $to
     * @param string $id
     * @return GetCampaignAnalyticsResponse
     */
    public static function getCampaignAnalytics(ClientConfig $clientConfig, GetCampaignAnalyticsType $type, string $from, string $to, string $id, ?RequestOptions $requestOptions = null): GetCampaignAnalyticsResponse
    {

        Validation::validateDate('from', $from);

        return SdkClient::typedData(SdkClient::request('GET', "/campaigns/analytics/" . SdkClient::encodePathSegment($type) . "", $clientConfig, query: ['from' => new SdkQueryValue($from, "form", true), 'to' => new SdkQueryValue($to, "form", true), 'id' => new SdkQueryValue($id, "form", true)], returnType: GetCampaignAnalyticsResponse::class, decoder: 'json', operationId: 'getCampaignAnalytics', requestOptions: $requestOptions), GetCampaignAnalyticsResponse::class);
    }


    /**
     * Retrieves the rendered HTML preview of a campaign's body. Supply the campaign's integer `id` to select the campaign whose preview you want to view.
     *
     * renders the HTML preview of a campaign body id: The id value of the campaign you want to get the preview of
     *
     * @param int $id
     * @return string
     */
    public static function previewCampaignById(ClientConfig $clientConfig, int $id, ?RequestOptions $requestOptions = null): string
    {

        return SdkClient::stringValue(SdkClient::request('GET', "/campaigns/" . SdkClient::encodePathSegment($id) . "/preview", $clientConfig, decoder: 'text', operationId: 'previewCampaignById', requestOptions: $requestOptions)->data);
    }


    /**
     * Renders an HTML preview of a campaign using the supplied template and content fields. Use `id` to identify the campaign and provide the preview inputs as form-encoded fields. The request body fields are optional in the schema.
     *
     * renders the HTML preview of a campaign body id: The id value of the campaign you want to get the preview of · templateId: template id · contentType: content type · body: template body
     *
     * @param int $id
     * @param int|SdkNotGiven $templateId
     * @param string|SdkNotGiven $contentType
     * @param string|SdkNotGiven $body
     * @return string
     */
    public static function updatePreviewCampaignById(ClientConfig $clientConfig, int $id, int|SdkNotGiven $templateId = SdkNotGiven::Value, string|SdkNotGiven $contentType = SdkNotGiven::Value, string|SdkNotGiven $body = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): string
    {

        return SdkClient::stringValue(SdkClient::request('POST', "/campaigns/" . SdkClient::encodePathSegment($id) . "/preview", $clientConfig, body: ['template_id' => $templateId, 'content_type' => $contentType, 'body' => $body], contentType: 'application/x-www-form-urlencoded', decoder: 'text', operationId: 'updatePreviewCampaignById', requestOptions: $requestOptions)->data);
    }


    /**
     * Renders a text preview of a campaign using the supplied template and content fields. Use `id` to identify the campaign and provide the preview inputs as form-encoded fields. The request body fields are optional in the schema.
     *
     * renders the HTML preview of a campaign body id: The id value of the campaign you want to get the preview of · templateId: template id · contentType: content type · body: campaign body
     *
     * @param int $id
     * @param int|SdkNotGiven $templateId
     * @param string|SdkNotGiven $contentType
     * @param string|SdkNotGiven $body
     * @return string
     */
    public static function previewCampaignTextById(ClientConfig $clientConfig, int $id, int|SdkNotGiven $templateId = SdkNotGiven::Value, string|SdkNotGiven $contentType = SdkNotGiven::Value, string|SdkNotGiven $body = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): string
    {

        return SdkClient::stringValue(SdkClient::request('POST', "/campaigns/" . SdkClient::encodePathSegment($id) . "/text", $clientConfig, body: ['template_id' => $templateId, 'content_type' => $contentType, 'body' => $body], contentType: 'application/x-www-form-urlencoded', decoder: 'text', operationId: 'previewCampaignTextById', requestOptions: $requestOptions)->data);
    }


    /**
     * Replaces the status of a campaign. Set `status` to `scheduled`, `running`, `paused`, or `cancelled` when you want to change the campaign's state.
     *
     * handles campaign status modification id: The id value of the campaign you want to get the preview of
     *
     * @param int $id
     * @param UpdateCampaignStatusByIdStatus|SdkNotGiven $status
     * @return UpdateCampaignStatusByIdResponse
     */
    public static function updateCampaignStatusById(ClientConfig $clientConfig, int $id, UpdateCampaignStatusByIdStatus|SdkNotGiven $status = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): UpdateCampaignStatusByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('PUT', "/campaigns/" . SdkClient::encodePathSegment($id) . "/status", $clientConfig, body: ['status' => $status], returnType: UpdateCampaignStatusByIdResponse::class, decoder: 'json', operationId: 'updateCampaignStatusById', requestOptions: $requestOptions), UpdateCampaignStatusByIdResponse::class);
    }


    /**
     * Replaces the archive settings for a campaign. Use `archive` to set the archive state and `archive_template_id` or `archive_meta` to provide related archive configuration.
     *
     * handles campaign status modification id: The id value of the campaign you want to get the preview of
     *
     * @param int $id
     * @param bool|SdkNotGiven $archive
     * @param int|SdkNotGiven $archiveTemplateId
     * @param array<array-key,mixed>|SdkNotGiven $archiveMeta
     * @return UpdateCampaignArchiveByIdResponse
     */
    public static function updateCampaignArchiveById(ClientConfig $clientConfig, int $id, bool|SdkNotGiven $archive = SdkNotGiven::Value, int|SdkNotGiven $archiveTemplateId = SdkNotGiven::Value, array|SdkNotGiven $archiveMeta = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): UpdateCampaignArchiveByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('PUT', "/campaigns/" . SdkClient::encodePathSegment($id) . "/archive", $clientConfig, body: ['archive' => $archive, 'archive_template_id' => $archiveTemplateId, 'archive_meta' => $archiveMeta], returnType: UpdateCampaignArchiveByIdResponse::class, decoder: 'json', operationId: 'updateCampaignArchiveById', requestOptions: $requestOptions), UpdateCampaignArchiveByIdResponse::class);
    }


    /**
     * Submits updated content for a campaign and converts it to the campaign's content format. Use the campaign identifier in the path and provide any campaign content fields you want to submit.
     *
     * handles campaign content (body) format conversions. id: ID of campaign that you choose to create content · id_2: Optional `integer` value serialized in the `id` wire field. · createdAt: Optional `string` value serialized in the `created_at` wire field. · updatedAt: Optional `string` value serialized in the `updated_at` wire field. · campaignId: Optional `integer` value serialized in the `CampaignID` wire field. · views: Optional `integer` value serialized in the `views` wire field. · clicks: Optional `integer` value serialized in the `clicks` wire field. · lists: Optional array value serialized in the `lists` wire field. · startedAt: Optional `string` value serialized in the `started_at` wire field. · toSend: Optional `integer` value serialized in the `to_send` wire field. · sent: Optional `integer` value serialized in the `sent` wire field. · uuid: Optional `string` value serialized in the `uuid` wire field. · type: Optional enumerated value serialized in the `type` wire field. · name: Optional `string` value serialized in the `name` wire field. · subject: Optional `string` value serialized in the `subject` wire field. · fromEmail: Optional `string` value serialized in the `from_email` wire field. · body: Optional `string` value serialized in the `body` wire field. · sendAt: Optional `string` value serialized in the `send_at` wire field. · status: Optional `string` value serialized in the `status` wire field. · contentType: Optional enumerated value serialized in the `content_type` wire field. · tags: Optional array value serialized in the `tags` wire field. · templateId: Optional `integer` value serialized in the `template_id` wire field. · messenger: Optional `string` value serialized in the `messenger` wire field. · from: Optional `string` value serialized in the `from` wire field. · to: Optional `string` value serialized in the `to` wire field.
     *
     * @param int $id
     * @param int|SdkNotGiven $id_2
     * @param string|SdkNotGiven $createdAt
     * @param string|SdkNotGiven $updatedAt
     * @param int|SdkNotGiven $campaignId
     * @param int|SdkNotGiven $views
     * @param int|SdkNotGiven $clicks
     * @param list<CreateCampaignContentByIdListsItem>|SdkNotGiven $lists
     * @param string|SdkNotGiven $startedAt
     * @param int|SdkNotGiven $toSend
     * @param int|SdkNotGiven $sent
     * @param string|SdkNotGiven $uuid
     * @param CreateCampaignContentByIdType|SdkNotGiven $type
     * @param string|SdkNotGiven $name
     * @param string|SdkNotGiven $subject
     * @param string|SdkNotGiven $fromEmail
     * @param string|SdkNotGiven $body
     * @param string|SdkNotGiven $sendAt
     * @param string|SdkNotGiven $status
     * @param CreateCampaignContentByIdContentType|SdkNotGiven $contentType
     * @param list<string>|SdkNotGiven $tags
     * @param int|SdkNotGiven $templateId
     * @param string|SdkNotGiven $messenger
     * @param string|SdkNotGiven $from
     * @param string|SdkNotGiven $to
     * @return CreateCampaignContentByIdResponse
     */
    public static function createCampaignContentById(ClientConfig $clientConfig, int $id, int|SdkNotGiven $id_2 = SdkNotGiven::Value, string|SdkNotGiven $createdAt = SdkNotGiven::Value, string|SdkNotGiven $updatedAt = SdkNotGiven::Value, int|SdkNotGiven $campaignId = SdkNotGiven::Value, int|SdkNotGiven $views = SdkNotGiven::Value, int|SdkNotGiven $clicks = SdkNotGiven::Value, array|SdkNotGiven $lists = SdkNotGiven::Value, string|SdkNotGiven $startedAt = SdkNotGiven::Value, int|SdkNotGiven $toSend = SdkNotGiven::Value, int|SdkNotGiven $sent = SdkNotGiven::Value, string|SdkNotGiven $uuid = SdkNotGiven::Value, CreateCampaignContentByIdType|SdkNotGiven $type = SdkNotGiven::Value, string|SdkNotGiven $name = SdkNotGiven::Value, string|SdkNotGiven $subject = SdkNotGiven::Value, string|SdkNotGiven $fromEmail = SdkNotGiven::Value, string|SdkNotGiven $body = SdkNotGiven::Value, string|SdkNotGiven $sendAt = SdkNotGiven::Value, string|SdkNotGiven $status = SdkNotGiven::Value, CreateCampaignContentByIdContentType|SdkNotGiven $contentType = SdkNotGiven::Value, array|SdkNotGiven $tags = SdkNotGiven::Value, int|SdkNotGiven $templateId = SdkNotGiven::Value, string|SdkNotGiven $messenger = SdkNotGiven::Value, string|SdkNotGiven $from = SdkNotGiven::Value, string|SdkNotGiven $to = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): CreateCampaignContentByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('POST', "/campaigns/" . SdkClient::encodePathSegment($id) . "/content", $clientConfig, body: ['id' => $id_2, 'created_at' => $createdAt, 'updated_at' => $updatedAt, 'CampaignID' => $campaignId, 'views' => $views, 'clicks' => $clicks, 'lists' => $lists, 'started_at' => $startedAt, 'to_send' => $toSend, 'sent' => $sent, 'uuid' => $uuid, 'type' => $type, 'name' => $name, 'subject' => $subject, 'from_email' => $fromEmail, 'body' => $body, 'send_at' => $sendAt, 'status' => $status, 'content_type' => $contentType, 'tags' => $tags, 'template_id' => $templateId, 'messenger' => $messenger, 'from' => $from, 'to' => $to], returnType: CreateCampaignContentByIdResponse::class, decoder: 'json', operationId: 'createCampaignContentById', requestOptions: $requestOptions), CreateCampaignContentByIdResponse::class);
    }


    /**
     * Submits a test campaign message to selected subscribers. Provide the campaign identifier and a request body with the test message configuration; the body can use JSON or form-encoded data.
     *
     * handles sending of campaign message to arbitrary subscribers for testing id: ID of campaign that you want to test · name: Optional `string` value serialized in the `name` wire field. · subject: Optional `string` value serialized in the `subject` wire field. · lists: Optional array value serialized in the `lists` wire field. · fromEmail: Optional `string` value serialized in the `from_email` wire field. · contentType: Optional `string` value serialized in the `content_type` wire field. · messenger: Optional `string` value serialized in the `messenger` wire field. · type: Optional `string` value serialized in the `type` wire field. · tags: Optional array value serialized in the `tags` wire field. · sendLater: Optional `boolean` value serialized in the `send_later` wire field. · sendAt: Optional object value serialized in the `send_at` wire field.
     *
     * @param int $id
     * @param string|SdkNotGiven $name
     * @param string|SdkNotGiven $subject
     * @param list<float>|SdkNotGiven $lists
     * @param string|SdkNotGiven $fromEmail
     * @param string|SdkNotGiven $contentType
     * @param string|SdkNotGiven $messenger
     * @param string|SdkNotGiven $type
     * @param list<string>|SdkNotGiven $tags
     * @param bool|SdkNotGiven $sendLater
     * @param TestCampaignByIdSendAt|SdkNotGiven $sendAt
     * @return TestCampaignByIdResponse
     */
    public static function testCampaignById(ClientConfig $clientConfig, int $id, string|SdkNotGiven $name = SdkNotGiven::Value, string|SdkNotGiven $subject = SdkNotGiven::Value, array|SdkNotGiven $lists = SdkNotGiven::Value, string|SdkNotGiven $fromEmail = SdkNotGiven::Value, string|SdkNotGiven $contentType = SdkNotGiven::Value, string|SdkNotGiven $messenger = SdkNotGiven::Value, string|SdkNotGiven $type = SdkNotGiven::Value, array|SdkNotGiven $tags = SdkNotGiven::Value, bool|SdkNotGiven $sendLater = SdkNotGiven::Value, TestCampaignByIdSendAt|SdkNotGiven $sendAt = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): TestCampaignByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('POST', "/campaigns/" . SdkClient::encodePathSegment($id) . "/test", $clientConfig, body: ['name' => $name, 'subject' => $subject, 'lists' => $lists, 'from_email' => $fromEmail, 'content_type' => $contentType, 'messenger' => $messenger, 'type' => $type, 'tags' => $tags, 'send_later' => $sendLater, 'send_at' => $sendAt], returnType: TestCampaignByIdResponse::class, decoder: 'json', operationId: 'testCampaignById', requestOptions: $requestOptions), TestCampaignByIdResponse::class);
    }


    /**
     * Submits a test campaign message to selected subscribers. Provide the campaign identifier and a request body with the test message configuration; the body can use JSON or form-encoded data.
     *
     * handles sending of campaign message to arbitrary subscribers for testing id: ID of campaign that you want to test · templateId: template id
     *
     * @param int $id
     * @param int|SdkNotGiven $templateId
     * @return TestCampaignByIdFormResponse
     */
    public static function testCampaignByIdForm(ClientConfig $clientConfig, int $id, int|SdkNotGiven $templateId = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): TestCampaignByIdFormResponse
    {

        return SdkClient::typedData(SdkClient::request('POST', "/campaigns/" . SdkClient::encodePathSegment($id) . "/test", $clientConfig, body: ['template_id' => $templateId], contentType: 'application/x-www-form-urlencoded', returnType: TestCampaignByIdFormResponse::class, decoder: 'json', operationId: 'testCampaignByIdForm', requestOptions: $requestOptions), TestCampaignByIdFormResponse::class);
    }
}
