<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

/**
 * Required object value serialized in the `lists[]` wire field.
 */
class CreateCampaignContentByIdListsItem implements \JsonSerializable
{
    /**
     * Optional `integer` value serialized in the `id` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $id;
    /**
     * Optional `string` value serialized in the `name` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $name;

    /**
     * @param int|SdkNotGiven $id
     * @param string|SdkNotGiven $name
     */
    public function __construct(
        int|SdkNotGiven $id = SdkNotGiven::Value,
        string|SdkNotGiven $name = SdkNotGiven::Value,
    ) {
        $this->id = $id;
        $this->name = $name;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->id !== SdkNotGiven::Value) {
            $values["id"] = $this->id;
        }
        if ($this->name !== SdkNotGiven::Value) {
            $values["name"] = $this->name;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            id: (property_exists($data, "id") ? SdkClient::intValue($data->id) : SdkNotGiven::Value),
            name: (property_exists($data, "name") ? SdkClient::stringValue($data->name) : SdkNotGiven::Value),
        );
    }
}

class CreateCampaignContentByIdResponse implements \JsonSerializable
{
    /** @var string|SdkNotGiven */
    public readonly string|SdkNotGiven $data;

    /**
     * @param string|SdkNotGiven $data
     */
    public function __construct(
        string|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::stringValue($data->data) : SdkNotGiven::Value),
        );
    }
}

/**
 * Optional object value serialized in the `send_at` wire field.
 */
class TestCampaignByIdSendAt implements \JsonSerializable
{
    /**
     * Optional array value serialized in the `headers` wire field.
     *
     * @var list<array<array-key,mixed>>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $headers;
    /**
     * Optional `number` value serialized in the `template_id` wire field.
     *
     * @var float|SdkNotGiven
     */
    public readonly float|SdkNotGiven $templateId;

    /**
     * @param list<array<array-key,mixed>>|SdkNotGiven $headers
     * @param float|SdkNotGiven $templateId
     */
    public function __construct(
        array|SdkNotGiven $headers = SdkNotGiven::Value,
        float|SdkNotGiven $templateId = SdkNotGiven::Value,
    ) {
        $this->headers = $headers;
        $this->templateId = $templateId;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->headers !== SdkNotGiven::Value) {
            $values["headers"] = $this->headers;
        }
        if ($this->templateId !== SdkNotGiven::Value) {
            $values["template_id"] = $this->templateId;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            headers: (property_exists($data, "headers") ? array_values(array_map(static fn ($item) => SdkClient::stringMapValue($item), SdkClient::arrayValue($data->headers))) : SdkNotGiven::Value),
            templateId: (property_exists($data, "template_id") ? SdkClient::floatValue($data->template_id) : SdkNotGiven::Value),
        );
    }
}

class TestCampaignByIdResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $data;

    /**
     * @param bool|SdkNotGiven $data
     */
    public function __construct(
        bool|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::boolValue($data->data) : SdkNotGiven::Value),
        );
    }
}

class TestCampaignByIdFormResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $data;

    /**
     * @param bool|SdkNotGiven $data
     */
    public function __construct(
        bool|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::boolValue($data->data) : SdkNotGiven::Value),
        );
    }
}
