<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

class GetCampaignByIdResponse implements \JsonSerializable
{
    /** @var Campaign|SdkNotGiven */
    public readonly Campaign|SdkNotGiven $data;

    /**
     * @param Campaign|SdkNotGiven $data
     */
    public function __construct(
        Campaign|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, Campaign::class) : SdkNotGiven::Value),
        );
    }
}

/**
 * Optional object value serialized in the `send_at` wire field.
 */
class UpdateCampaignByIdSendAt implements \JsonSerializable
{
    /**
     * Optional array value serialized in the `headers` wire field.
     *
     * @var list<array<array-key,mixed>>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $headers;
    /**
     * Optional `number` value serialized in the `template_id` wire field.
     *
     * @var float|SdkNotGiven
     */
    public readonly float|SdkNotGiven $templateId;

    /**
     * @param list<array<array-key,mixed>>|SdkNotGiven $headers
     * @param float|SdkNotGiven $templateId
     */
    public function __construct(
        array|SdkNotGiven $headers = SdkNotGiven::Value,
        float|SdkNotGiven $templateId = SdkNotGiven::Value,
    ) {
        $this->headers = $headers;
        $this->templateId = $templateId;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->headers !== SdkNotGiven::Value) {
            $values["headers"] = $this->headers;
        }
        if ($this->templateId !== SdkNotGiven::Value) {
            $values["template_id"] = $this->templateId;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            headers: (property_exists($data, "headers") ? array_values(array_map(static fn($item) => SdkClient::stringMapValue($item), SdkClient::arrayValue($data->headers))) : SdkNotGiven::Value),
            templateId: (property_exists($data, "template_id") ? SdkClient::floatValue($data->template_id) : SdkNotGiven::Value),
        );
    }
}

class UpdateCampaignByIdResponse implements \JsonSerializable
{
    /** @var CampaignUpdate|SdkNotGiven */
    public readonly CampaignUpdate|SdkNotGiven $data;

    /**
     * @param CampaignUpdate|SdkNotGiven $data
     */
    public function __construct(
        CampaignUpdate|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, CampaignUpdate::class) : SdkNotGiven::Value),
        );
    }
}

class DeleteCampaignByIdResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $data;

    /**
     * @param bool|SdkNotGiven $data
     */
    public function __construct(
        bool|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::boolValue($data->data) : SdkNotGiven::Value),
        );
    }
}

class GetRunningCampaignStatsResponse implements \JsonSerializable
{
    /** @var list<CampaignStats>|SdkNotGiven */
    public readonly array|SdkNotGiven $data;

    /**
     * @param list<CampaignStats>|SdkNotGiven $data
     */
    public function __construct(
        array|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? array_values(array_map(static fn($item) => SdkClient::hydrateClass($item, CampaignStats::class), SdkClient::arrayValue($data->data))) : SdkNotGiven::Value),
        );
    }
}

class GetCampaignAnalyticsResponse implements \JsonSerializable
{
    /** @var list<CampaignAnalyticsCount>|SdkNotGiven */
    public readonly array|SdkNotGiven $data;

    /**
     * @param list<CampaignAnalyticsCount>|SdkNotGiven $data
     */
    public function __construct(
        array|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? array_values(array_map(static fn($item) => SdkClient::hydrateClass($item, CampaignAnalyticsCount::class), SdkClient::arrayValue($data->data))) : SdkNotGiven::Value),
        );
    }
}

class UpdateCampaignStatusByIdResponse implements \JsonSerializable
{
    /** @var Campaign|SdkNotGiven */
    public readonly Campaign|SdkNotGiven $data;

    /**
     * @param Campaign|SdkNotGiven $data
     */
    public function __construct(
        Campaign|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, Campaign::class) : SdkNotGiven::Value),
        );
    }
}

class UpdateCampaignArchiveByIdResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $data;

    /**
     * @param bool|SdkNotGiven $data
     */
    public function __construct(
        bool|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::boolValue($data->data) : SdkNotGiven::Value),
        );
    }
}
