<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

final readonly class GetCampaignsOrder implements SdkOpenEnum
{
    public const ASC = "ASC";
    public const DESC = "DESC";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static { return new self((string) $value); }
    public static function tryFrom(string|int|null $value): ?static { return $value === null ? null : self::from($value); }
    public function getValue(): string { return $this->value; }
    public function jsonSerialize(): string { return $this->value; }
    public function __toString(): string { return (string) $this->value; }
}

final readonly class GetCampaignsOrderBy implements SdkOpenEnum
{
    public const NAME = "name";
    public const STATUS = "status";
    public const CREATED_AT = "created_at";
    public const UPDATED_AT = "updated_at";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static { return new self((string) $value); }
    public static function tryFrom(string|int|null $value): ?static { return $value === null ? null : self::from($value); }
    public function getValue(): string { return $this->value; }
    public function jsonSerialize(): string { return $this->value; }
    public function __toString(): string { return (string) $this->value; }
}

final readonly class GetCampaignAnalyticsType implements SdkOpenEnum
{
    public const LINKS = "links";
    public const VIEWS = "views";
    public const CLICKS = "clicks";
    public const BOUNCES = "bounces";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static { return new self((string) $value); }
    public static function tryFrom(string|int|null $value): ?static { return $value === null ? null : self::from($value); }
    public function getValue(): string { return $this->value; }
    public function jsonSerialize(): string { return $this->value; }
    public function __toString(): string { return (string) $this->value; }
}

final readonly class UpdateCampaignStatusByIdStatus implements SdkOpenEnum
{
    public const SCHEDULED = "scheduled";
    public const RUNNING = "running";
    public const PAUSED = "paused";
    public const CANCELLED = "cancelled";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static { return new self((string) $value); }
    public static function tryFrom(string|int|null $value): ?static { return $value === null ? null : self::from($value); }
    public function getValue(): string { return $this->value; }
    public function jsonSerialize(): string { return $this->value; }
    public function __toString(): string { return (string) $this->value; }
}

final readonly class CreateCampaignContentByIdType implements SdkOpenEnum
{
    public const REGULAR = "regular";
    public const OPTIN = "optin";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static { return new self((string) $value); }
    public static function tryFrom(string|int|null $value): ?static { return $value === null ? null : self::from($value); }
    public function getValue(): string { return $this->value; }
    public function jsonSerialize(): string { return $this->value; }
    public function __toString(): string { return (string) $this->value; }
}

final readonly class CreateCampaignContentByIdContentType implements SdkOpenEnum
{
    public const RICHTEXT = "richtext";
    public const HTML = "html";
    public const MARKDOWN = "markdown";
    public const PLAIN = "plain";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static { return new self((string) $value); }
    public static function tryFrom(string|int|null $value): ?static { return $value === null ? null : self::from($value); }
    public function getValue(): string { return $this->value; }
    public function jsonSerialize(): string { return $this->value; }
    public function __toString(): string { return (string) $this->value; }
}

/**
 * Return all results without pagination
 */
final readonly class GetCampaignsPerPageEnum implements SdkOpenEnum
{
    public const ALL = "all";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static { return new self((string) $value); }
    public static function tryFrom(string|int|null $value): ?static { return $value === null ? null : self::from($value); }
    public function getValue(): string { return $this->value; }
    public function jsonSerialize(): string { return $this->value; }
    public function __toString(): string { return (string) $this->value; }
}

class GetCampaignsResponseData implements \JsonSerializable
{
    /** @var list<Campaign>|SdkNotGiven */
    public readonly array|SdkNotGiven $results;
    /** @var string|SdkNotGiven */
    public readonly string|SdkNotGiven $query;
    /** @var int|SdkNotGiven */
    public readonly int|SdkNotGiven $total;
    /** @var int|SdkNotGiven */
    public readonly int|SdkNotGiven $perPage;
    /** @var int|SdkNotGiven */
    public readonly int|SdkNotGiven $page;

    /**
     * @param list<Campaign>|SdkNotGiven $results
     * @param string|SdkNotGiven $query
     * @param int|SdkNotGiven $total
     * @param int|SdkNotGiven $perPage
     * @param int|SdkNotGiven $page
     */
    public function __construct(
        array|SdkNotGiven $results = SdkNotGiven::Value,
        string|SdkNotGiven $query = SdkNotGiven::Value,
        int|SdkNotGiven $total = SdkNotGiven::Value,
        int|SdkNotGiven $perPage = SdkNotGiven::Value,
        int|SdkNotGiven $page = SdkNotGiven::Value,
    ) {
        $this->results = $results;
        $this->query = $query;
        $this->total = $total;
        $this->perPage = $perPage;
        $this->page = $page;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->results !== SdkNotGiven::Value) {
            $values["results"] = $this->results;
        }
        if ($this->query !== SdkNotGiven::Value) {
            $values["query"] = $this->query;
        }
        if ($this->total !== SdkNotGiven::Value) {
            $values["total"] = $this->total;
        }
        if ($this->perPage !== SdkNotGiven::Value) {
            $values["per_page"] = $this->perPage;
        }
        if ($this->page !== SdkNotGiven::Value) {
            $values["page"] = $this->page;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            results: (property_exists($data, "results") ? array_values(array_map(static fn ($item) => SdkClient::hydrateClass($item, Campaign::class), SdkClient::arrayValue($data->results))) : SdkNotGiven::Value),
            query: (property_exists($data, "query") ? SdkClient::stringValue($data->query) : SdkNotGiven::Value),
            total: (property_exists($data, "total") ? SdkClient::intValue($data->total) : SdkNotGiven::Value),
            perPage: (property_exists($data, "per_page") ? SdkClient::intValue($data->per_page) : SdkNotGiven::Value),
            page: (property_exists($data, "page") ? SdkClient::intValue($data->page) : SdkNotGiven::Value),
        );
    }
}

class GetCampaignsResponse implements \JsonSerializable
{
    /** @var GetCampaignsResponseData|SdkNotGiven */
    public readonly GetCampaignsResponseData|SdkNotGiven $data;

    /**
     * @param GetCampaignsResponseData|SdkNotGiven $data
     */
    public function __construct(
        GetCampaignsResponseData|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, GetCampaignsResponseData::class) : SdkNotGiven::Value),
        );
    }
}

/**
 * Optional object value serialized in the `send_at` wire field.
 */
class CreateCampaignSendAt implements \JsonSerializable
{
    /**
     * Optional array value serialized in the `headers` wire field.
     *
     * @var list<array<array-key,mixed>>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $headers;
    /**
     * Optional `number` value serialized in the `template_id` wire field.
     *
     * @var float|SdkNotGiven
     */
    public readonly float|SdkNotGiven $templateId;

    /**
     * @param list<array<array-key,mixed>>|SdkNotGiven $headers
     * @param float|SdkNotGiven $templateId
     */
    public function __construct(
        array|SdkNotGiven $headers = SdkNotGiven::Value,
        float|SdkNotGiven $templateId = SdkNotGiven::Value,
    ) {
        $this->headers = $headers;
        $this->templateId = $templateId;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->headers !== SdkNotGiven::Value) {
            $values["headers"] = $this->headers;
        }
        if ($this->templateId !== SdkNotGiven::Value) {
            $values["template_id"] = $this->templateId;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            headers: (property_exists($data, "headers") ? array_values(array_map(static fn ($item) => SdkClient::stringMapValue($item), SdkClient::arrayValue($data->headers))) : SdkNotGiven::Value),
            templateId: (property_exists($data, "template_id") ? SdkClient::floatValue($data->template_id) : SdkNotGiven::Value),
        );
    }
}

class CreateCampaignResponse implements \JsonSerializable
{
    /** @var CampaignUpdate|SdkNotGiven */
    public readonly CampaignUpdate|SdkNotGiven $data;

    /**
     * @param CampaignUpdate|SdkNotGiven $data
     */
    public function __construct(
        CampaignUpdate|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, CampaignUpdate::class) : SdkNotGiven::Value),
        );
    }
}
