<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

final readonly class GetListsOrderBy implements SdkOpenEnum
{
    public const NAME = "name";
    public const STATUS = "status";
    public const CREATED_AT = "created_at";
    public const UPDATED_AT = "updated_at";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static { return new self((string) $value); }
    public static function tryFrom(string|int|null $value): ?static { return $value === null ? null : self::from($value); }
    public function getValue(): string { return $this->value; }
    public function jsonSerialize(): string { return $this->value; }
    public function __toString(): string { return (string) $this->value; }
}

final readonly class GetListsOrder implements SdkOpenEnum
{
    public const ASC = "ASC";
    public const DESC = "DESC";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static { return new self((string) $value); }
    public static function tryFrom(string|int|null $value): ?static { return $value === null ? null : self::from($value); }
    public function getValue(): string { return $this->value; }
    public function jsonSerialize(): string { return $this->value; }
    public function __toString(): string { return (string) $this->value; }
}

final readonly class CreateListType implements SdkOpenEnum
{
    public const PUBLIC = "public";
    public const PRIVATE = "private";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static { return new self((string) $value); }
    public static function tryFrom(string|int|null $value): ?static { return $value === null ? null : self::from($value); }
    public function getValue(): string { return $this->value; }
    public function jsonSerialize(): string { return $this->value; }
    public function __toString(): string { return (string) $this->value; }
}

final readonly class CreateListOptin implements SdkOpenEnum
{
    public const SINGLE = "single";
    public const DOUBLE = "double";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static { return new self((string) $value); }
    public static function tryFrom(string|int|null $value): ?static { return $value === null ? null : self::from($value); }
    public function getValue(): string { return $this->value; }
    public function jsonSerialize(): string { return $this->value; }
    public function __toString(): string { return (string) $this->value; }
}

/**
 * Return all results without pagination
 */
final readonly class GetListsPerPageEnum implements SdkOpenEnum
{
    public const ALL = "all";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static { return new self((string) $value); }
    public static function tryFrom(string|int|null $value): ?static { return $value === null ? null : self::from($value); }
    public function getValue(): string { return $this->value; }
    public function jsonSerialize(): string { return $this->value; }
    public function __toString(): string { return (string) $this->value; }
}

class GetListsResponseData implements \JsonSerializable
{
    /** @var list<ListModel>|SdkNotGiven */
    public readonly array|SdkNotGiven $results;
    /** @var int|SdkNotGiven */
    public readonly int|SdkNotGiven $total;
    /** @var int|SdkNotGiven */
    public readonly int|SdkNotGiven $perPage;
    /** @var int|SdkNotGiven */
    public readonly int|SdkNotGiven $page;

    /**
     * @param list<ListModel>|SdkNotGiven $results
     * @param int|SdkNotGiven $total
     * @param int|SdkNotGiven $perPage
     * @param int|SdkNotGiven $page
     */
    public function __construct(
        array|SdkNotGiven $results = SdkNotGiven::Value,
        int|SdkNotGiven $total = SdkNotGiven::Value,
        int|SdkNotGiven $perPage = SdkNotGiven::Value,
        int|SdkNotGiven $page = SdkNotGiven::Value,
    ) {
        $this->results = $results;
        $this->total = $total;
        $this->perPage = $perPage;
        $this->page = $page;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->results !== SdkNotGiven::Value) {
            $values["results"] = $this->results;
        }
        if ($this->total !== SdkNotGiven::Value) {
            $values["total"] = $this->total;
        }
        if ($this->perPage !== SdkNotGiven::Value) {
            $values["per_page"] = $this->perPage;
        }
        if ($this->page !== SdkNotGiven::Value) {
            $values["page"] = $this->page;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            results: (property_exists($data, "results") ? array_values(array_map(static fn ($item) => SdkClient::hydrateClass($item, ListModel::class), SdkClient::arrayValue($data->results))) : SdkNotGiven::Value),
            total: (property_exists($data, "total") ? SdkClient::intValue($data->total) : SdkNotGiven::Value),
            perPage: (property_exists($data, "per_page") ? SdkClient::intValue($data->per_page) : SdkNotGiven::Value),
            page: (property_exists($data, "page") ? SdkClient::intValue($data->page) : SdkNotGiven::Value),
        );
    }
}

class GetListsResponse implements \JsonSerializable
{
    /** @var GetListsResponseData|SdkNotGiven */
    public readonly GetListsResponseData|SdkNotGiven $data;

    /**
     * @param GetListsResponseData|SdkNotGiven $data
     */
    public function __construct(
        GetListsResponseData|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, GetListsResponseData::class) : SdkNotGiven::Value),
        );
    }
}

class CreateListResponse implements \JsonSerializable
{
    /** @var ListModel|SdkNotGiven */
    public readonly ListModel|SdkNotGiven $data;

    /**
     * @param ListModel|SdkNotGiven $data
     */
    public function __construct(
        ListModel|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, ListModel::class) : SdkNotGiven::Value),
        );
    }
}

class GetListByIdResponse implements \JsonSerializable
{
    /** @var ListModel|SdkNotGiven */
    public readonly ListModel|SdkNotGiven $data;

    /**
     * @param ListModel|SdkNotGiven $data
     */
    public function __construct(
        ListModel|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, ListModel::class) : SdkNotGiven::Value),
        );
    }
}

class UpdateListByIdResponse implements \JsonSerializable
{
    /** @var ListModel|SdkNotGiven */
    public readonly ListModel|SdkNotGiven $data;

    /**
     * @param ListModel|SdkNotGiven $data
     */
    public function __construct(
        ListModel|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, ListModel::class) : SdkNotGiven::Value),
        );
    }
}

class DeleteListByIdResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $data;

    /**
     * @param bool|SdkNotGiven $data
     */
    public function __construct(
        bool|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::boolValue($data->data) : SdkNotGiven::Value),
        );
    }
}
