<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

trait ListsMethodsPart1
{
    /**
     * Lists mailing lists with metadata such as subscriber counts. Use `query` to search by list name, `tag` to filter by tags, and `order_by` and `order` to control sorting. Use `page` and `per_page` to paginate the results.
     *
     * retrieves lists with additional metadata like subscriber counts. This may be slow. page: total number of pages · perPage: number of items per page · query: Optional string to search a list by name. · orderBy: Field to sort results by. name|status|created_at|updated_at · order: ASC|DESC Sort by ascending or descending order. · minimal: When set to true, returns response without body content · tag: Tags to filter lists. Repeat in the query for multiple values.
     *
     * @param int|SdkNotGiven $page
     * @param int|GetListsPerPageEnum|SdkNotGiven $perPage
     * @param string|SdkNotGiven $query
     * @param GetListsOrderBy|SdkNotGiven $orderBy
     * @param GetListsOrder|SdkNotGiven $order
     * @param bool|SdkNotGiven $minimal
     * @param list<string>|SdkNotGiven $tag
     * @return GetListsResponse
     */
    public static function getLists(ClientConfig $clientConfig, int|SdkNotGiven $page = SdkNotGiven::Value, int|GetListsPerPageEnum|string|SdkNotGiven $perPage = SdkNotGiven::Value, string|SdkNotGiven $query = SdkNotGiven::Value, GetListsOrderBy|SdkNotGiven $orderBy = SdkNotGiven::Value, GetListsOrder|SdkNotGiven $order = SdkNotGiven::Value, bool|SdkNotGiven $minimal = SdkNotGiven::Value, array|SdkNotGiven $tag = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): GetListsResponse
    {

        return SdkClient::typedData(SdkClient::request('GET', "/lists", $clientConfig, query: ['page' => new SdkQueryValue($page, "form", true), 'per_page' => new SdkQueryValue($perPage, "form", true), 'query' => new SdkQueryValue($query, "form", true), 'order_by' => new SdkQueryValue($orderBy, "form", true), 'order' => new SdkQueryValue($order, "form", true), 'minimal' => new SdkQueryValue($minimal, "form", true), 'tag' => new SdkQueryValue($tag, "form", true)], returnType: GetListsResponse::class, decoder: 'json', operationId: 'getLists', requestOptions: $requestOptions), GetListsResponse::class);
    }


    /**
     * Creates a mailing list from the supplied list details. Provide `name`, `type`, `optin`, `tags`, or `description` as needed; `type` and `optin` have defined accepted values. The response includes the created list and its metadata.
     *
     * handles list creation name: Optional `string` value serialized in the `name` wire field. · type: Optional enumerated value serialized in the `type` wire field. · optin: Optional enumerated value serialized in the `optin` wire field. · tags: Optional array value serialized in the `tags` wire field. · description: Optional `string` value serialized in the `description` wire field.
     *
     * @param string|SdkNotGiven $name
     * @param CreateListType|SdkNotGiven $type
     * @param CreateListOptin|SdkNotGiven $optin
     * @param list<string>|SdkNotGiven $tags
     * @param string|SdkNotGiven $description
     * @return CreateListResponse
     */
    public static function createList(ClientConfig $clientConfig, string|SdkNotGiven $name = SdkNotGiven::Value, CreateListType|SdkNotGiven $type = SdkNotGiven::Value, CreateListOptin|SdkNotGiven $optin = SdkNotGiven::Value, array|SdkNotGiven $tags = SdkNotGiven::Value, string|SdkNotGiven $description = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): CreateListResponse
    {

        return SdkClient::typedData(SdkClient::request('POST', "/lists", $clientConfig, body: ['name' => $name, 'type' => $type, 'optin' => $optin, 'tags' => $tags, 'description' => $description], returnType: CreateListResponse::class, decoder: 'json', operationId: 'createList', requestOptions: $requestOptions), CreateListResponse::class);
    }


    /**
     * Retrieves a mailing list with metadata such as its subscriber count. Supply the list's integer `list_id` to identify the list to retrieve.
     *
     * retrieves lists with additional metadata like subscriber counts. This may be slow. listId: The id value of the list you want to retreive.
     *
     * @param int $listId
     * @return GetListByIdResponse
     */
    public static function getListById(ClientConfig $clientConfig, int $listId, ?RequestOptions $requestOptions = null): GetListByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('GET', "/lists/" . SdkClient::encodePathSegment($listId) . "", $clientConfig, returnType: GetListByIdResponse::class, decoder: 'json', operationId: 'getListById', requestOptions: $requestOptions), GetListByIdResponse::class);
    }


    /**
     * Replaces the supplied fields on a mailing list identified by its ID. The request body can include list settings, tags, and metadata; all body fields are optional in the schema.
     *
     * handles list modification listId: The id value of the list you want to update · id: Optional `integer` value serialized in the `id` wire field. · createdAt: Optional `string` value serialized in the `created_at` wire field. · updatedAt: Optional `string` value serialized in the `updated_at` wire field. · uuid: Optional `string` value serialized in the `uuid` wire field. · name: Optional `string` value serialized in the `name` wire field. · type: Optional `string` value serialized in the `type` wire field. · optin: Optional `string` value serialized in the `optin` wire field. · tags: Optional array value serialized in the `tags` wire field. · subscriberCount: Optional `integer` value serialized in the `subscriber_count` wire field. · description: Optional `string` value serialized in the `description` wire field.
     *
     * @param int $listId
     * @param int|SdkNotGiven $id
     * @param string|SdkNotGiven $createdAt
     * @param string|SdkNotGiven $updatedAt
     * @param string|SdkNotGiven $uuid
     * @param string|SdkNotGiven $name
     * @param string|SdkNotGiven $type
     * @param string|SdkNotGiven $optin
     * @param list<string>|SdkNotGiven $tags
     * @param int|SdkNotGiven $subscriberCount
     * @param string|SdkNotGiven $description
     * @return UpdateListByIdResponse
     */
    public static function updateListById(ClientConfig $clientConfig, int $listId, int|SdkNotGiven $id = SdkNotGiven::Value, string|SdkNotGiven $createdAt = SdkNotGiven::Value, string|SdkNotGiven $updatedAt = SdkNotGiven::Value, string|SdkNotGiven $uuid = SdkNotGiven::Value, string|SdkNotGiven $name = SdkNotGiven::Value, string|SdkNotGiven $type = SdkNotGiven::Value, string|SdkNotGiven $optin = SdkNotGiven::Value, array|SdkNotGiven $tags = SdkNotGiven::Value, int|SdkNotGiven $subscriberCount = SdkNotGiven::Value, string|SdkNotGiven $description = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): UpdateListByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('PUT', "/lists/" . SdkClient::encodePathSegment($listId) . "", $clientConfig, body: ['id' => $id, 'created_at' => $createdAt, 'updated_at' => $updatedAt, 'uuid' => $uuid, 'name' => $name, 'type' => $type, 'optin' => $optin, 'tags' => $tags, 'subscriber_count' => $subscriberCount, 'description' => $description], returnType: UpdateListByIdResponse::class, decoder: 'json', operationId: 'updateListById', requestOptions: $requestOptions), UpdateListByIdResponse::class);
    }


    /**
     * Deletes a mailing list identified by its ID in the URI. Supply the list's integer `list_id` to specify which list to remove.
     *
     * handles list deletion, either a single one (ID in the URI), or a list. listId: The id value of the lists you want to delete.
     *
     * @param int $listId
     * @return DeleteListByIdResponse
     */
    public static function deleteListById(ClientConfig $clientConfig, int $listId, ?RequestOptions $requestOptions = null): DeleteListByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('DELETE', "/lists/" . SdkClient::encodePathSegment($listId) . "", $clientConfig, returnType: DeleteListByIdResponse::class, decoder: 'json', operationId: 'deleteListById', requestOptions: $requestOptions), DeleteListByIdResponse::class);
    }
}
