<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk\Tests;

use listmonk_unofficial_sdk\ClientConfig;
use listmonk_unofficial_sdk\SdkClient;
use listmonk_unofficial_sdk\SdkQueryValue;
use listmonk_unofficial_sdk\SdkRawResponse;
use listmonk_unofficial_sdk\SdkRequest;
use PHPUnit\Framework\TestCase;
use ReflectionMethod;

final class SdkRuntimeTest extends TestCase
{
    public function testEncodesExactlyOnePathSegment(): void
    {
        self::assertSame('%2F%20%3F%23%25%E9%9B%AA', SdkClient::encodePathSegment('/ ?#%雪'));
    }

    public function testSerializesRepeatedAndCommaDelimitedQueries(): void
    {
        $buildUrl = new ReflectionMethod(SdkClient::class, 'buildUrl');
        $url = $buildUrl->invoke(null, 'https://example.test', '/resource', [
            'repeated' => new SdkQueryValue(['a', '雪'], 'form', true),
            'csv' => new SdkQueryValue(['a', 'b'], 'form', false),
        ]);

        self::assertIsString($url);
        self::assertStringContainsString('repeated=a&repeated=%E9%9B%AA', $url);
        self::assertStringContainsString('csv=a%2Cb', $url);

        $staticQueryUrl = $buildUrl->invoke(null, 'https://example.test', '/resource?beta=true', [
            'include' => new SdkQueryValue(['details'], 'form', true),
        ]);
        self::assertSame('https://example.test/resource?beta=true&include=details', $staticQueryUrl);
    }

    public function testResponseDecoderKeepsTextBytesAndEmptyDistinct(): void
    {
        $decode = new ReflectionMethod(SdkClient::class, 'decode');
        self::assertSame('hello', $decode->invoke(null, 'hello', 'text', null));
        self::assertSame("\0raw", $decode->invoke(null, "\0raw", 'bytes', null));
        self::assertNull($decode->invoke(null, '', 'empty', null));
    }

    public function testRequestLayerUsesFakeMiddleware(): void
    {
        $config = new ClientConfig();
        $config->baseUrl = 'https://example.test';
        $config->middleware = [
            static function (SdkRequest $request, callable $_next): SdkRawResponse {
                self::assertSame('GET', $request->method);
                self::assertSame('https://example.test/probe', $request->url);
                $raw = new SdkRawResponse();
                $raw->statusCode = 200;
                $raw->statusText = 'OK';
                $raw->headers = ['x-request-id' => 'fake-id'];
                $raw->body = '{"ok":true}';
                $raw->requestId = 'fake-id';
                $raw->latencySeconds = 0.001;
                $raw->attempt = $request->attempt;
                return $raw;
            },
        ];
        $response = SdkClient::request('GET', '/probe', config: $config, operationId: 'probe');
        $data = $response->data;
        self::assertInstanceOf(\stdClass::class, $data);
        self::assertTrue($data->ok);
        self::assertSame('fake-id', $response->requestId);
    }
}
