<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

class BouncesNamespace
{
    private ClientConfig $clientConfig;
    public function __construct(ClientConfig $clientConfig)
    {
        $this->clientConfig = $clientConfig;
    }
    /**
     * Lists bounce records, optionally filtered by campaign or source and sorted by a selected field. Use `page` and `per_page` to paginate the results; set `per_page` to `all` to retrieve all results without pagination.
     *
     * handles retrieval of bounce records. campaignId: Numeric identifier for retrieving bounce records associated with a specific campaign · page: Page number for paginated results. Start from 1 for the first page · perPage: Number of items per page. Use an integer for specific page size or 'all' to retrieve all results · source: Filter bounce records by their source of origin · orderBy: Specifies the field by which to sort the bounce records. Available options are 'email', 'campaign_name', 'source', and 'created_at' · order: Determines the sort order of results. Use 'asc' for ascending or 'desc' for descending order
     *
     * @param int|SdkNotGiven $campaignId
     * @param int|SdkNotGiven $page
     * @param int|GetBouncesPerPageEnum|SdkNotGiven $perPage
     * @param string|SdkNotGiven $source
     * @param GetBouncesOrderBy|SdkNotGiven $orderBy
     * @param GetBouncesOrder|SdkNotGiven $order
     * @return GetBouncesResponse
     */
    public function get(int|SdkNotGiven $campaignId = SdkNotGiven::Value, int|SdkNotGiven $page = SdkNotGiven::Value, int|GetBouncesPerPageEnum|string|SdkNotGiven $perPage = SdkNotGiven::Value, string|SdkNotGiven $source = SdkNotGiven::Value, GetBouncesOrderBy|SdkNotGiven $orderBy = SdkNotGiven::Value, GetBouncesOrder|SdkNotGiven $order = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): GetBouncesResponse
    {
        return Bounces::getBounces($this->clientConfig, $campaignId, $page, $perPage, $source, $orderBy, $order, $requestOptions);
    }
    /**
     * Deletes bounce records selected by a deletion flag or bounce identifiers. Use `all` to indicate bulk deletion or `id` to provide the bounce identifiers to delete.
     *
     * handles deletion of bounce records. all: flag for multiple bounce record deletion · id: list of bounce ids to delete
     *
     * @param bool|SdkNotGiven $all
     * @param string|SdkNotGiven $id
     * @return DeleteBouncesResponse
     */
    public function delete(bool|SdkNotGiven $all = SdkNotGiven::Value, string|SdkNotGiven $id = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): DeleteBouncesResponse
    {
        return Bounces::deleteBounces($this->clientConfig, $all, $id, $requestOptions);
    }
    /**
     * Retrieves a bounce record by its identifier. Supply the record's numeric `id` to look up the bounce you want to retrieve.
     *
     * handles retrieval of bounce record by id id: The id value of the bounce you want to retreive.
     *
     * @param int $id
     * @return GetBounceByIdResponse
     */
    public function getById(int $id, ?RequestOptions $requestOptions = null): GetBounceByIdResponse
    {
        return Bounces::getBounceById($this->clientConfig, $id, $requestOptions);
    }
    /**
     * Deletes a single bounce identified by its ID in the URI. Supply the integer `id` of the bounce you want to remove.
     *
     * handles bounce deletion, either a single one (ID in the URI), or a list. id: The id value of the bounce you want to delete.
     *
     * @param int $id
     * @return DeleteBounceByIdResponse
     */
    public function deleteById(int $id, ?RequestOptions $requestOptions = null): DeleteBounceByIdResponse
    {
        return Bounces::deleteBounceById($this->clientConfig, $id, $requestOptions);
    }
}
