<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

class ImportNamespace
{
    private ClientConfig $clientConfig;
    public function __construct(ClientConfig $clientConfig)
    {
        $this->clientConfig = $clientConfig;
    }
    /**
     * Retrieves the current status of subscriber imports. Use this endpoint to check the import status without submitting an import request.
     *
     * returns import status.
     *
     * @return GetImportSubscribersResponse
     */
    public function getSubscribers(?RequestOptions $requestOptions = null): GetImportSubscribersResponse
    {
        return Import::getImportSubscribers($this->clientConfig, $requestOptions);
    }
    /**
     * Uploads and imports a ZIP file containing one or more CSV files of subscribers. Send the upload as `multipart/form-data`; `params` can contain import settings as a JSON string. Use GET /import/subscribers to retrieve import status.
     *
     * handles the uploading and bulk importing of a ZIP file of one or more CSV files. params: JSON string containing import parameters for more detail https://listmonk.app/docs/apis/import/#params-json-string · file: File for upload.
     *
     * @param string|SdkNotGiven $params
     * @param SdkUploadFile|SdkNotGiven $file
     * @return ImportSubscribersResponse
     */
    public function subscribers(string|SdkNotGiven $params = SdkNotGiven::Value, SdkUploadFile|SdkNotGiven $file = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): ImportSubscribersResponse
    {
        return Import::importSubscribers($this->clientConfig, $params, $file, $requestOptions);
    }
    /**
     * Sends a stop signal to the subscriber importer. Use this endpoint to request that an ongoing import stop.
     *
     * sends a stop signal to the importer.
     *
     * @return StopImportSubscribersResponse
     */
    public function stopSubscribers(?RequestOptions $requestOptions = null): StopImportSubscribersResponse
    {
        return Import::stopImportSubscribers($this->clientConfig, $requestOptions);
    }
    /**
     * Retrieves logs from an ongoing subscriber import. Use this endpoint to inspect import activity while the import is running.
     *
     * returns import logs from an ongoing import
     *
     * @return GetImportSubscriberLogsResponse
     */
    public function getSubscriberLogs(?RequestOptions $requestOptions = null): GetImportSubscriberLogsResponse
    {
        return Import::getImportSubscriberLogs($this->clientConfig, $requestOptions);
    }
}
