<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

class LogsNamespace
{
    private ClientConfig $clientConfig;
    public function __construct(ClientConfig $clientConfig)
    {
        $this->clientConfig = $clientConfig;
    }
    /**
     * Lists log entries currently stored in the log buffer. Use this endpoint to retrieve the buffered entries as an array of strings.
     *
     * returns the log entries stored in the log buffer
     *
     * @return GetLogsResponse
     */
    public function get(?RequestOptions $requestOptions = null): GetLogsResponse
    {
        return Logs::getLogs($this->clientConfig, $requestOptions);
    }
}
