<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

class MaintenanceNamespace
{
    private ClientConfig $clientConfig;
    public function __construct(ClientConfig $clientConfig)
    {
        $this->clientConfig = $clientConfig;
    }
    /**
     * Deletes orphaned or blocklisted subscribers through garbage collection. Specify the subscriber category to collect with the `type` path parameter.
     *
     * garbage collects (deletes) orphaned or blocklisted subscribers. type: type of GC collected subscribers
     *
     * @param string $type
     * @return DeleteGCSubscribersResponse
     */
    public function deleteGcSubscribers(string $type, ?RequestOptions $requestOptions = null): DeleteGCSubscribersResponse
    {
        return Maintenance::deleteGcSubscribers($this->clientConfig, $type, $requestOptions);
    }
    /**
     * Deletes campaign analytics of the specified type. Use `before_date` to set the date cutoff for the analytics to remove.
     *
     * garbage collects (deletes) campaign analytics. type: type of GC collected subscribers
     *
     * @param string $type
     * @param string|SdkNotGiven $beforeDate
     * @return DeleteCampaignAnalyticsByTypeResponse
     */
    public function deleteCampaignAnalyticsByType(string $type, string|SdkNotGiven $beforeDate = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): DeleteCampaignAnalyticsByTypeResponse
    {
        return Maintenance::deleteCampaignAnalyticsByType($this->clientConfig, $type, $beforeDate, $requestOptions);
    }
    /**
     * Deletes unconfirmed subscriptions through garbage collection. Use `before_date` to set the cutoff date for the subscriptions to remove.
     *
     * garbage collects (deletes) orphaned or blocklisted subscribers.
     *
     * @param string|SdkNotGiven $beforeDate
     * @return DeleteUnconfirmedSubscriptionsResponse
     */
    public function deleteUnconfirmedSubscriptions(string|SdkNotGiven $beforeDate = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): DeleteUnconfirmedSubscriptionsResponse
    {
        return Maintenance::deleteUnconfirmedSubscriptions($this->clientConfig, $beforeDate, $requestOptions);
    }
}
