<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

class MediaNamespace
{
    private ClientConfig $clientConfig;
    public function __construct(ClientConfig $clientConfig)
    {
        $this->clientConfig = $clientConfig;
    }
    /**
     * Lists uploaded media. Use this endpoint to retrieve the available media records and their file details.
     *
     * handles retrieval of uploaded media.
     *
     * @return GetMediaResponse
     */
    public function get(?RequestOptions $requestOptions = null): GetMediaResponse
    {
        return Media::getMedia($this->clientConfig, $requestOptions);
    }
    /**
     * Uploads a media file. Send the file as a binary value using `multipart/form-data`; the request body schema does not define additional metadata fields.
     *
     * handles media file uploads.
     *
     * @param string|SdkNotGiven $body
     * @return UploadMediaResponse
     */
    public function upload(string|SdkNotGiven $body = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): UploadMediaResponse
    {
        return Media::uploadMedia($this->clientConfig, $body, $requestOptions);
    }
    /**
     * Retrieves an uploaded media record by its identifier. Use the media identifier to access the record's file details and URLs.
     *
     * handles retrieval of uploaded media. id: media file id
     *
     * @param int $id
     * @return GetMediaByIdResponse
     */
    public function getById(int $id, ?RequestOptions $requestOptions = null): GetMediaByIdResponse
    {
        return Media::getMediaById($this->clientConfig, $id, $requestOptions);
    }
    /**
     * Deletes an uploaded media record. Supply the media identifier for the record you want to remove.
     *
     * handles deletion of uploaded media. id: The id value of the list you want to delete.
     *
     * @param int $id
     * @return DeleteMediaByIdResponse
     */
    public function deleteById(int $id, ?RequestOptions $requestOptions = null): DeleteMediaByIdResponse
    {
        return Media::deleteMediaById($this->clientConfig, $id, $requestOptions);
    }
}
