<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

class MiscellaneousNamespace
{
    private ClientConfig $clientConfig;
    public function __construct(ClientConfig $clientConfig)
    {
        $this->clientConfig = $clientConfig;
    }
    /**
     * Returns the service health-check result. Use the boolean `data` value to determine whether the service is responding.
     *
     * healthcheck endpoint
     *
     * @return GetHealthCheckResponse
     */
    public function getHealthCheck(?RequestOptions $requestOptions = null): GetHealthCheckResponse
    {
        return Miscellaneous::getHealthCheck($this->clientConfig, $requestOptions);
    }
    /**
     * Returns the general server configuration. Use this endpoint to retrieve the configuration object exposed by the server.
     *
     * returns general server config.
     *
     * @return GetServerConfigResponse
     */
    public function getServerConfig(?RequestOptions $requestOptions = null): GetServerConfigResponse
    {
        return Miscellaneous::getServerConfig($this->clientConfig, $requestOptions);
    }
    /**
     * Returns the JSON language pack for the requested language code. Supply `lang` to select the language pack to retrieve.
     *
     * returns the JSON language pack given the language code lang: JSON language pack required
     *
     * @param string $lang
     * @return GetI18nLangResponse
     */
    public function getI18nLang(string $lang, ?RequestOptions $requestOptions = null): GetI18nLangResponse
    {
        return Miscellaneous::getI18nLang($this->clientConfig, $lang, $requestOptions);
    }
    /**
     * Returns chart data points for the dashboard. Use the `link_clicks` and `campaign_views` data to render the corresponding dashboard charts.
     *
     * returns chart data points to render on the dashboard.
     *
     * @return GetDashboardChartsResponse
     */
    public function getDashboardCharts(?RequestOptions $requestOptions = null): GetDashboardChartsResponse
    {
        return Miscellaneous::getDashboardCharts($this->clientConfig, $requestOptions);
    }
    /**
     * Returns statistics counts for the dashboard. Use the returned counts to display summary statistics in the dashboard.
     *
     * returns stats counts to show on the dashboard
     *
     * @return GetDashboardCountsResponse
     */
    public function getDashboardCounts(?RequestOptions $requestOptions = null): GetDashboardCountsResponse
    {
        return Miscellaneous::getDashboardCounts($this->clientConfig, $requestOptions);
    }
}
