<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

class TemplatesNamespace
{
    private ClientConfig $clientConfig;
    public function __construct(ClientConfig $clientConfig)
    {
        $this->clientConfig = $clientConfig;
    }
    /**
     * Lists templates. Set `no_body` to control whether template bodies are included in the response.
     *
     * handles retrieval of templates noBody: boolean flag for response with/without body
     *
     * @param bool $noBody
     * @return GetTemplatesResponse
     */
    public function get(bool $noBody, ?RequestOptions $requestOptions = null): GetTemplatesResponse
    {
        return Templates::getTemplates($this->clientConfig, $noBody, $requestOptions);
    }
    /**
     * Creates a new template. Supply `name`, `type`, and `body`; choose `type` from `campaign`, `campaign_visual`, or `tx`, and include `subject` or `body_source` when relevant to that template type.
     *
     * handles template creation name: Name of the template · type: Type of the template · body: HTML body of the template · subject: Subject line for the template (only for tx) · bodySource: JSON source for the email-builder template (only for campaign_visual)
     *
     * @param string $name
     * @param CreateTemplateType $type
     * @param string $body
     * @param string|SdkNotGiven $subject
     * @param string|SdkNotGiven $bodySource
     * @return CreateTemplateResponse
     */
    public function create(string $name, CreateTemplateType $type, string $body, string|SdkNotGiven $subject = SdkNotGiven::Value, string|SdkNotGiven $bodySource = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): CreateTemplateResponse
    {
        return Templates::createTemplate($this->clientConfig, $name, $type, $body, $subject, $bodySource, $requestOptions);
    }
    /**
     * Retrieves a template by its identifier. Use the `no_body` query parameter to request a response with or without the template body.
     *
     * handles retrieval of templates id: The id value of the template you want to get. · noBody: boolean flag for response with/without body
     *
     * @param int $id
     * @param bool|SdkNotGiven $noBody
     * @return GetTemplateByIdResponse
     */
    public function getById(int $id, bool|SdkNotGiven $noBody = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): GetTemplateByIdResponse
    {
        return Templates::getTemplateById($this->clientConfig, $id, $noBody, $requestOptions);
    }
    /**
     * Replaces a template's configuration. Supply the template properties you want to set, and use `type` to choose campaign, visual campaign, or transactional template behavior.
     *
     * handles template modification id: The id value of the template you want to update. · name: Name of the template · type: Type of the template · subject: Subject line for the template (only for tx) · bodySource: JSON source for the email-builder template (only for campaign_visual) · body: HTML body of the template
     *
     * @param int $id
     * @param string|SdkNotGiven $name
     * @param UpdateTemplateByIdType|SdkNotGiven $type
     * @param string|SdkNotGiven $subject
     * @param string|SdkNotGiven $bodySource
     * @param string|SdkNotGiven $body
     * @return UpdateTemplateByIdResponse
     */
    public function updateById(int $id, string|SdkNotGiven $name = SdkNotGiven::Value, UpdateTemplateByIdType|SdkNotGiven $type = SdkNotGiven::Value, string|SdkNotGiven $subject = SdkNotGiven::Value, string|SdkNotGiven $bodySource = SdkNotGiven::Value, string|SdkNotGiven $body = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): UpdateTemplateByIdResponse
    {
        return Templates::updateTemplateById($this->clientConfig, $id, $name, $type, $subject, $bodySource, $body, $requestOptions);
    }
    /**
     * Deletes a template by its identifier. Use this operation when you no longer need the template; the response indicates whether the deletion succeeded.
     *
     * handles deletion of templates id: The id value of the template you want to delete.
     *
     * @param int $id
     * @return DeleteTemplateByIdResponse
     */
    public function deleteById(int $id, ?RequestOptions $requestOptions = null): DeleteTemplateByIdResponse
    {
        return Templates::deleteTemplateById($this->clientConfig, $id, $requestOptions);
    }
    /**
     * Generates an HTML preview from the supplied template parameters. Provide `template_type` to identify the template type and `body` to supply the template content.
     *
     * get the HTML preview of a template. templateType: type of template · body: template body
     *
     * @param string|SdkNotGiven $templateType
     * @param string|SdkNotGiven $body
     * @return string
     */
    public function preview(string|SdkNotGiven $templateType = SdkNotGiven::Value, string|SdkNotGiven $body = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): string
    {
        return Templates::previewTemplate($this->clientConfig, $templateType, $body, $requestOptions);
    }
    /**
     * Renders an HTML preview for a template identified by its integer ID. Supply `template_type` and `body` as form-encoded preview parameters.
     *
     * renders the HTML preview of a template. id: The id value of the template you want to get.
     *
     * @param int $id
     * @return string
     */
    public function previewById(int $id, ?RequestOptions $requestOptions = null): string
    {
        return Templates::previewTemplateById($this->clientConfig, $id, $requestOptions);
    }
    /**
     * Sets the specified template as the default template. Use the template's integer identifier to select which template to make the default.
     *
     * handles template modification. id: The id value of the template you want to set to the default template.
     *
     * @param int $id
     * @return Template
     */
    public function setDefaultById(int $id, ?RequestOptions $requestOptions = null): Template
    {
        return Templates::setDefaultTemplateById($this->clientConfig, $id, $requestOptions);
    }
}
