<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

class TransactionalNamespace
{
    private ClientConfig $clientConfig;
    public function __construct(ClientConfig $clientConfig)
    {
        $this->clientConfig = $clientConfig;
    }
    /**
     * Sends a transactional message to a subscriber. Use `subscriber_email` or `subscriber_id` to identify the recipient, and provide message content or a `template_id` as needed.
     *
     * send message to a subscriber subscriberEmail: Optional `string` value serialized in the `subscriber_email` wire field. · subscriberId: Optional `integer` value serialized in the `subscriber_id` wire field. · templateId: Optional `integer` value serialized in the `template_id` wire field. · fromEmail: Optional `string` value serialized in the `from_email` wire field. · data: Optional object value serialized in the `data` wire field. · headers: Optional array value serialized in the `headers` wire field. · messenger: Optional `string` value serialized in the `messenger` wire field. · contentType: Optional `string` value serialized in the `content_type` wire field.
     *
     * @param string|SdkNotGiven $subscriberEmail
     * @param int|SdkNotGiven $subscriberId
     * @param int|SdkNotGiven $templateId
     * @param string|SdkNotGiven $fromEmail
     * @param array<array-key,mixed>|SdkNotGiven $data
     * @param list<mixed>|SdkNotGiven $headers
     * @param string|SdkNotGiven $messenger
     * @param string|SdkNotGiven $contentType
     * @return TransactWithSubscriberResponse
     */
    public function transactWithSubscriber(string|SdkNotGiven $subscriberEmail = SdkNotGiven::Value, int|SdkNotGiven $subscriberId = SdkNotGiven::Value, int|SdkNotGiven $templateId = SdkNotGiven::Value, string|SdkNotGiven $fromEmail = SdkNotGiven::Value, array|SdkNotGiven $data = SdkNotGiven::Value, array|SdkNotGiven $headers = SdkNotGiven::Value, string|SdkNotGiven $messenger = SdkNotGiven::Value, string|SdkNotGiven $contentType = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): TransactWithSubscriberResponse
    {
        return Transactional::transactWithSubscriber($this->clientConfig, $subscriberEmail, $subscriberId, $templateId, $fromEmail, $data, $headers, $messenger, $contentType, $requestOptions);
    }
}
