<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

class GetSubscribersResponse implements \JsonSerializable
{
    /** @var GetSubscribersResponseData|SdkNotGiven */
    public readonly GetSubscribersResponseData|SdkNotGiven $data;

    /**
     * @param GetSubscribersResponseData|SdkNotGiven $data
     */
    public function __construct(
        GetSubscribersResponseData|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, GetSubscribersResponseData::class) : SdkNotGiven::Value),
        );
    }
}

class CreateSubscriberResponse implements \JsonSerializable
{
    /** @var Subscriber|SdkNotGiven */
    public readonly Subscriber|SdkNotGiven $data;

    /**
     * @param Subscriber|SdkNotGiven $data
     */
    public function __construct(
        Subscriber|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, Subscriber::class) : SdkNotGiven::Value),
        );
    }
}

class DeleteSubscriberByListResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $data;

    /**
     * @param bool|SdkNotGiven $data
     */
    public function __construct(
        bool|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::boolValue($data->data) : SdkNotGiven::Value),
        );
    }
}

class GetSubscriberByIdResponse implements \JsonSerializable
{
    /** @var Subscriber|SdkNotGiven */
    public readonly Subscriber|SdkNotGiven $data;

    /**
     * @param Subscriber|SdkNotGiven $data
     */
    public function __construct(
        Subscriber|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, Subscriber::class) : SdkNotGiven::Value),
        );
    }
}

class UpdateSubscriberByIdResponse implements \JsonSerializable
{
    /** @var Subscriber|SdkNotGiven */
    public readonly Subscriber|SdkNotGiven $data;

    /**
     * @param Subscriber|SdkNotGiven $data
     */
    public function __construct(
        Subscriber|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, Subscriber::class) : SdkNotGiven::Value),
        );
    }
}

class DeleteSubscriberByIdResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $data;

    /**
     * @param bool|SdkNotGiven $data
     */
    public function __construct(
        bool|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::boolValue($data->data) : SdkNotGiven::Value),
        );
    }
}

class ManageSubscriberListsResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $data;

    /**
     * @param bool|SdkNotGiven $data
     */
    public function __construct(
        bool|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::boolValue($data->data) : SdkNotGiven::Value),
        );
    }
}

class ManageSubscriberListByIdResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $data;

    /**
     * @param bool|SdkNotGiven $data
     */
    public function __construct(
        bool|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::boolValue($data->data) : SdkNotGiven::Value),
        );
    }
}
