<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

trait SubscribersMethodsPart1
{
    /**
     * Lists subscribers, with options to filter and sort the results. Use `query` to filter with an SQL expression, `list_id` to filter by lists, and `order_by` and `order` to control sorting. Use `page` and `per_page` to paginate the results.
     *
     * returns all subscribers. page: Page number for paginated results. · perPage: Number of items per page. Use an integer for specific page size or 'all' to retrieve all results · query: query subscribers with an SQL expression. · orderBy: Result sorting field. Options are name, status, created_at, updated_at · order: ASC|DESC Sort by ascending or descending order. · subscriptionStatus: Subscription status to filter by if there are one or more list_ids. · listId: ID of lists to filter by. Repeat in the query for multiple values.
     *
     * @param int|SdkNotGiven $page
     * @param int|GetSubscribersPerPageEnum|SdkNotGiven $perPage
     * @param string|SdkNotGiven $query
     * @param GetSubscribersOrderBy|SdkNotGiven $orderBy
     * @param GetSubscribersOrder|SdkNotGiven $order
     * @param string|SdkNotGiven $subscriptionStatus
     * @param list<int>|SdkNotGiven $listId
     * @return GetSubscribersResponse
     */
    public static function getSubscribers(ClientConfig $clientConfig, int|SdkNotGiven $page = SdkNotGiven::Value, int|GetSubscribersPerPageEnum|string|SdkNotGiven $perPage = SdkNotGiven::Value, string|SdkNotGiven $query = SdkNotGiven::Value, GetSubscribersOrderBy|SdkNotGiven $orderBy = SdkNotGiven::Value, GetSubscribersOrder|SdkNotGiven $order = SdkNotGiven::Value, string|SdkNotGiven $subscriptionStatus = SdkNotGiven::Value, array|SdkNotGiven $listId = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): GetSubscribersResponse
    {

        return SdkClient::typedData(SdkClient::request('GET', "/subscribers", $clientConfig, query: ['page' => new SdkQueryValue($page, "form", true), 'per_page' => new SdkQueryValue($perPage, "form", true), 'query' => new SdkQueryValue($query, "form", true), 'order_by' => new SdkQueryValue($orderBy, "form", true), 'order' => new SdkQueryValue($order, "form", true), 'subscription_status' => new SdkQueryValue($subscriptionStatus, "form", true), 'list_id' => new SdkQueryValue($listId, "form", true)], returnType: GetSubscribersResponse::class, decoder: 'json', operationId: 'getSubscribers', requestOptions: $requestOptions), GetSubscribersResponse::class);
    }


    /**
     * Creates a subscriber from the supplied subscriber details. The request body may be omitted, and no fields are required by the schema; include values such as `email`, `name`, or `lists` to set subscriber data.
     *
     * handles creation of new subscriber email: Optional `string` value serialized in the `email` wire field. · name: Optional `string` value serialized in the `name` wire field. · status: Optional `string` value serialized in the `status` wire field. · lists: Optional array value serialized in the `lists` wire field. · listUuids: Optional array value serialized in the `list_uuids` wire field. · preconfirmSubscriptions: Optional `boolean` value serialized in the `preconfirm_subscriptions` wire field. · attribs: Optional object value serialized in the `attribs` wire field.
     *
     * @param string|SdkNotGiven $email
     * @param string|SdkNotGiven $name
     * @param string|SdkNotGiven $status
     * @param list<int>|SdkNotGiven $lists
     * @param list<string>|SdkNotGiven $listUuids
     * @param bool|SdkNotGiven $preconfirmSubscriptions
     * @param array<string,mixed>|SdkNotGiven $attribs
     * @return CreateSubscriberResponse
     */
    public static function createSubscriber(ClientConfig $clientConfig, string|SdkNotGiven $email = SdkNotGiven::Value, string|SdkNotGiven $name = SdkNotGiven::Value, string|SdkNotGiven $status = SdkNotGiven::Value, array|SdkNotGiven $lists = SdkNotGiven::Value, array|SdkNotGiven $listUuids = SdkNotGiven::Value, bool|SdkNotGiven $preconfirmSubscriptions = SdkNotGiven::Value, array|SdkNotGiven $attribs = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): CreateSubscriberResponse
    {

        return SdkClient::typedData(SdkClient::request('POST', "/subscribers", $clientConfig, body: ['email' => $email, 'name' => $name, 'status' => $status, 'lists' => $lists, 'list_uuids' => $listUuids, 'preconfirm_subscriptions' => $preconfirmSubscriptions, 'attribs' => $attribs], returnType: CreateSubscriberResponse::class, decoder: 'json', operationId: 'createSubscriber', requestOptions: $requestOptions), CreateSubscriberResponse::class);
    }


    /**
     * Deletes one or more subscribers identified by the `id` query parameter. Supply the subscriber ID or IDs as a string, with each ID identifying a subscriber to delete.
     *
     * handles subscribers deletion id: subscriber id/s to be deleted
     *
     * @param string $id
     * @return DeleteSubscriberByListResponse
     */
    public static function deleteSubscriberByList(ClientConfig $clientConfig, string $id, ?RequestOptions $requestOptions = null): DeleteSubscriberByListResponse
    {

        return SdkClient::typedData(SdkClient::request('DELETE', "/subscribers", $clientConfig, query: ['id' => new SdkQueryValue($id, "form", true)], returnType: DeleteSubscriberByListResponse::class, decoder: 'json', operationId: 'deleteSubscriberByList', requestOptions: $requestOptions), DeleteSubscriberByListResponse::class);
    }


    /**
     * Retrieves a subscriber by its identifier. Use the `id` path parameter to select the subscriber whose details you want to view.
     *
     * handles the retrieval of a single subscriber by ID. id: The id value of the subscriber you want to get.
     *
     * @param int $id
     * @return GetSubscriberByIdResponse
     */
    public static function getSubscriberById(ClientConfig $clientConfig, int $id, ?RequestOptions $requestOptions = null): GetSubscriberByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('GET', "/subscribers/" . SdkClient::encodePathSegment($id) . "", $clientConfig, returnType: GetSubscriberByIdResponse::class, decoder: 'json', operationId: 'getSubscriberById', requestOptions: $requestOptions), GetSubscriberByIdResponse::class);
    }


    /**
     * Replaces subscriber data for the subscriber identified by the path parameter. The request body may be omitted, and the schema does not require any fields; supply the subscriber properties you want included in the update.
     *
     * modify subscriber data id: The id of subscriber to update · email: Optional `string` value serialized in the `email` wire field. · name: Optional `string` value serialized in the `name` wire field. · status: Optional `string` value serialized in the `status` wire field. · lists: Optional array value serialized in the `lists` wire field. · listUuids: Optional array value serialized in the `list_uuids` wire field. · preconfirmSubscriptions: Optional `boolean` value serialized in the `preconfirm_subscriptions` wire field. · attribs: Optional object value serialized in the `attribs` wire field.
     *
     * @param int $id
     * @param string|SdkNotGiven $email
     * @param string|SdkNotGiven $name
     * @param string|SdkNotGiven $status
     * @param list<int>|SdkNotGiven $lists
     * @param list<string>|SdkNotGiven $listUuids
     * @param bool|SdkNotGiven $preconfirmSubscriptions
     * @param array<string,mixed>|SdkNotGiven $attribs
     * @return UpdateSubscriberByIdResponse
     */
    public static function updateSubscriberById(ClientConfig $clientConfig, int $id, string|SdkNotGiven $email = SdkNotGiven::Value, string|SdkNotGiven $name = SdkNotGiven::Value, string|SdkNotGiven $status = SdkNotGiven::Value, array|SdkNotGiven $lists = SdkNotGiven::Value, array|SdkNotGiven $listUuids = SdkNotGiven::Value, bool|SdkNotGiven $preconfirmSubscriptions = SdkNotGiven::Value, array|SdkNotGiven $attribs = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): UpdateSubscriberByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('PUT', "/subscribers/" . SdkClient::encodePathSegment($id) . "", $clientConfig, body: ['email' => $email, 'name' => $name, 'status' => $status, 'lists' => $lists, 'list_uuids' => $listUuids, 'preconfirm_subscriptions' => $preconfirmSubscriptions, 'attribs' => $attribs], returnType: UpdateSubscriberByIdResponse::class, decoder: 'json', operationId: 'updateSubscriberById', requestOptions: $requestOptions), UpdateSubscriberByIdResponse::class);
    }


    /**
     * Deletes a subscriber identified by its path parameter. Use the subscriber's integer `id` to select the record to remove.
     *
     * handles subscriber deletion based on id id: The id value of the subscriber you want to get.
     *
     * @param int $id
     * @return DeleteSubscriberByIdResponse
     */
    public static function deleteSubscriberById(ClientConfig $clientConfig, int $id, ?RequestOptions $requestOptions = null): DeleteSubscriberByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('DELETE', "/subscribers/" . SdkClient::encodePathSegment($id) . "", $clientConfig, returnType: DeleteSubscriberByIdResponse::class, decoder: 'json', operationId: 'deleteSubscriberById', requestOptions: $requestOptions), DeleteSubscriberByIdResponse::class);
    }


    /**
     * Manages subscriber membership across lists by adding, removing, or unsubscribing subscribers. Supply `action` and the subscriber or list selectors that define which records to modify; `action` must be `add`, `remove`, or `unsubscribe`.
     *
     * handles bulk addition or removal of subscribers query: Optional `string` value serialized in the `query` wire field. · ids: The ids of the subscribers to be modified. · action: Whether to add, remove, or unsubscribe the users. · targetListIds: The ids of the lists to be modified. · status: confirmed, unconfirmed, or unsubscribed status.
     *
     * @param string|SdkNotGiven $query
     * @param list<int>|SdkNotGiven $ids
     * @param ManageSubscriberListsAction|SdkNotGiven $action
     * @param int|SdkNotGiven $targetListIds
     * @param ManageSubscriberListsStatus|SdkNotGiven $status
     * @return ManageSubscriberListsResponse
     */
    public static function manageSubscriberLists(ClientConfig $clientConfig, string|SdkNotGiven $query = SdkNotGiven::Value, array|SdkNotGiven $ids = SdkNotGiven::Value, ManageSubscriberListsAction|SdkNotGiven $action = SdkNotGiven::Value, int|SdkNotGiven $targetListIds = SdkNotGiven::Value, ManageSubscriberListsStatus|SdkNotGiven $status = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): ManageSubscriberListsResponse
    {

        return SdkClient::typedData(SdkClient::request('PUT', "/subscribers/lists", $clientConfig, body: ['query' => $query, 'ids' => $ids, 'action' => $action, 'target_list_ids' => $targetListIds, 'status' => $status], returnType: ManageSubscriberListsResponse::class, decoder: 'json', operationId: 'manageSubscriberLists', requestOptions: $requestOptions), ManageSubscriberListsResponse::class);
    }


    /**
     * Manages subscriber membership in a specified list by adding, removing, or unsubscribing subscribers. Use the `id` path parameter to select the list and provide the subscriber selectors and `action` in the request body.
     *
     * handles bulk addition or removal of subscribers for a specified list id id: The id of list you want to update · query: Optional `string` value serialized in the `query` wire field. · ids: The ids of the subscribers to be modified. · action: Whether to add, remove, or unsubscribe the users. · targetListIds: The ids of the lists to be modified. · status: confirmed, unconfirmed, or unsubscribed status.
     *
     * @param int $id
     * @param string|SdkNotGiven $query
     * @param list<int>|SdkNotGiven $ids
     * @param ManageSubscriberListByIdAction|SdkNotGiven $action
     * @param int|SdkNotGiven $targetListIds
     * @param ManageSubscriberListByIdStatus|SdkNotGiven $status
     * @return ManageSubscriberListByIdResponse
     */
    public static function manageSubscriberListById(ClientConfig $clientConfig, int $id, string|SdkNotGiven $query = SdkNotGiven::Value, array|SdkNotGiven $ids = SdkNotGiven::Value, ManageSubscriberListByIdAction|SdkNotGiven $action = SdkNotGiven::Value, int|SdkNotGiven $targetListIds = SdkNotGiven::Value, ManageSubscriberListByIdStatus|SdkNotGiven $status = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): ManageSubscriberListByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('PUT', "/subscribers/lists/" . SdkClient::encodePathSegment($id) . "", $clientConfig, body: ['query' => $query, 'ids' => $ids, 'action' => $action, 'target_list_ids' => $targetListIds, 'status' => $status], returnType: ManageSubscriberListByIdResponse::class, decoder: 'json', operationId: 'manageSubscriberListById', requestOptions: $requestOptions), ManageSubscriberListByIdResponse::class);
    }


    /**
     * Manages subscribers on the blocklist using subscriber selectors and list settings. Provide `action` to specify whether to add, remove, or unsubscribe the selected subscribers.
     *
     * handles blocklisting of subscriber list query: Optional `string` value serialized in the `query` wire field. · ids: The ids of the subscribers to be modified. · action: Whether to add, remove, or unsubscribe the users. · targetListIds: The ids of the lists to be modified. · status: confirmed, unconfirmed, or unsubscribed status.
     *
     * @param string|SdkNotGiven $query
     * @param list<int>|SdkNotGiven $ids
     * @param ManageBlocklistBySubscriberListAction|SdkNotGiven $action
     * @param int|SdkNotGiven $targetListIds
     * @param ManageBlocklistBySubscriberListStatus|SdkNotGiven $status
     * @return ManageBlocklistBySubscriberListResponse
     */
    public static function manageBlocklistBySubscriberList(ClientConfig $clientConfig, string|SdkNotGiven $query = SdkNotGiven::Value, array|SdkNotGiven $ids = SdkNotGiven::Value, ManageBlocklistBySubscriberListAction|SdkNotGiven $action = SdkNotGiven::Value, int|SdkNotGiven $targetListIds = SdkNotGiven::Value, ManageBlocklistBySubscriberListStatus|SdkNotGiven $status = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): ManageBlocklistBySubscriberListResponse
    {

        return SdkClient::typedData(SdkClient::request('PUT', "/subscribers/blocklist", $clientConfig, body: ['query' => $query, 'ids' => $ids, 'action' => $action, 'target_list_ids' => $targetListIds, 'status' => $status], returnType: ManageBlocklistBySubscriberListResponse::class, decoder: 'json', operationId: 'manageBlocklistBySubscriberList', requestOptions: $requestOptions), ManageBlocklistBySubscriberListResponse::class);
    }


    /**
     * Manages the blocklist for the subscriber identified by the path parameter. Use the `id` path parameter to select the subscriber and provide the action and any additional selectors in the request body.
     *
     * handles the blocklisting of one or more subscribers. id: The id value of the subscriber you want to blocklist. · query: Optional `string` value serialized in the `query` wire field. · ids: The ids of the subscribers to be modified. · action: Whether to add, remove, or unsubscribe the users. · targetListIds: The ids of the lists to be modified. · status: confirmed, unconfirmed, or unsubscribed status.
     *
     * @param int $id
     * @param string|SdkNotGiven $query
     * @param list<int>|SdkNotGiven $ids
     * @param ManageBlocklistSubscribersByIdAction|SdkNotGiven $action
     * @param int|SdkNotGiven $targetListIds
     * @param ManageBlocklistSubscribersByIdStatus|SdkNotGiven $status
     * @return ManageBlocklistSubscribersByIdResponse
     */
    public static function manageBlocklistSubscribersById(ClientConfig $clientConfig, int $id, string|SdkNotGiven $query = SdkNotGiven::Value, array|SdkNotGiven $ids = SdkNotGiven::Value, ManageBlocklistSubscribersByIdAction|SdkNotGiven $action = SdkNotGiven::Value, int|SdkNotGiven $targetListIds = SdkNotGiven::Value, ManageBlocklistSubscribersByIdStatus|SdkNotGiven $status = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): ManageBlocklistSubscribersByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('PUT', "/subscribers/" . SdkClient::encodePathSegment($id) . "/blocklist", $clientConfig, body: ['query' => $query, 'ids' => $ids, 'action' => $action, 'target_list_ids' => $targetListIds, 'status' => $status], returnType: ManageBlocklistSubscribersByIdResponse::class, decoder: 'json', operationId: 'manageBlocklistSubscribersById', requestOptions: $requestOptions), ManageBlocklistSubscribersByIdResponse::class);
    }


    /**
     * Retrieves a subscriber's profile and related activity data for export. Supply the subscriber's numeric `id` to retrieve profile details, subscriptions, campaign views, and link clicks.
     *
     * retrieves a subscriber's profile id: The id value of subscriber profile you want to export
     *
     * @param int $id
     * @return SubscriberData
     */
    public static function exportSubscriberDataById(ClientConfig $clientConfig, int $id, ?RequestOptions $requestOptions = null): SubscriberData
    {

        return SdkClient::typedData(SdkClient::request('GET', "/subscribers/" . SdkClient::encodePathSegment($id) . "/export", $clientConfig, returnType: SubscriberData::class, decoder: 'json', operationId: 'exportSubscriberDataById', requestOptions: $requestOptions), SubscriberData::class);
    }


    /**
     * Retrieves bounce records associated with a specific subscriber. Supply the subscriber's numeric `id` to look up the records for that subscriber.
     *
     * retrieves a subscriber's bounce records id: subscriber id
     *
     * @param int $id
     * @return GetSubscriberBouncesByIdResponse
     */
    public static function getSubscriberBouncesById(ClientConfig $clientConfig, int $id, ?RequestOptions $requestOptions = null): GetSubscriberBouncesByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('GET', "/subscribers/" . SdkClient::encodePathSegment($id) . "/bounces", $clientConfig, returnType: GetSubscriberBouncesByIdResponse::class, decoder: 'json', operationId: 'getSubscriberBouncesById', requestOptions: $requestOptions), GetSubscriberBouncesByIdResponse::class);
    }


    /**
     * Deletes the bounce records associated with a specific subscriber. Supply the subscriber's numeric `id` to identify whose bounce records to delete.
     *
     * deletes a subscriber's bounce records id: subscriber id
     *
     * @param int $id
     * @return DeleteSubscriberBouncesByIdResponse
     */
    public static function deleteSubscriberBouncesById(ClientConfig $clientConfig, int $id, ?RequestOptions $requestOptions = null): DeleteSubscriberBouncesByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('DELETE', "/subscribers/" . SdkClient::encodePathSegment($id) . "/bounces", $clientConfig, returnType: DeleteSubscriberBouncesByIdResponse::class, decoder: 'json', operationId: 'deleteSubscriberBouncesById', requestOptions: $requestOptions), DeleteSubscriberBouncesByIdResponse::class);
    }


    /**
     * Sends an opt-in confirmation email to a subscriber. Supply the subscriber's numeric `id` to identify the recipient of the confirmation email.
     *
     * sends an optin confirmation e-mail to a subscriber. id: sends an optin confirmation e-mail to a subscriber
     *
     * @param int $id
     * @return SubscriberSendOptinByIdResponse
     */
    public static function subscriberSendOptinById(ClientConfig $clientConfig, int $id, ?RequestOptions $requestOptions = null): SubscriberSendOptinByIdResponse
    {

        return SdkClient::typedData(SdkClient::request('POST', "/subscribers/" . SdkClient::encodePathSegment($id) . "/optin", $clientConfig, returnType: SubscriberSendOptinByIdResponse::class, decoder: 'json', operationId: 'subscriberSendOptinById', requestOptions: $requestOptions), SubscriberSendOptinByIdResponse::class);
    }


    /**
     * Deletes subscribers selected by an SQL expression or subscriber identifiers. Provide the expression as plain text or use a JSON body to specify `query`, `ids`, and any applicable `action`, `target_list_ids`, or `status` filters.
     *
     * bulk deletes based on an arbitrary SQL expression. query: Optional `string` value serialized in the `query` wire field. · ids: The ids of the subscribers to be modified. · action: Whether to add, remove, or unsubscribe the users. · targetListIds: The ids of the lists to be modified. · status: confirmed, unconfirmed, or unsubscribed status.
     *
     * @param string|SdkNotGiven $query
     * @param list<int>|SdkNotGiven $ids
     * @param DeleteSubscriberByQueryAction|SdkNotGiven $action
     * @param int|SdkNotGiven $targetListIds
     * @param DeleteSubscriberByQueryStatus|SdkNotGiven $status
     * @return DeleteSubscriberByQueryResponse
     */
    public static function deleteSubscriberByQuery(ClientConfig $clientConfig, string|SdkNotGiven $query = SdkNotGiven::Value, array|SdkNotGiven $ids = SdkNotGiven::Value, DeleteSubscriberByQueryAction|SdkNotGiven $action = SdkNotGiven::Value, int|SdkNotGiven $targetListIds = SdkNotGiven::Value, DeleteSubscriberByQueryStatus|SdkNotGiven $status = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): DeleteSubscriberByQueryResponse
    {

        return SdkClient::typedData(SdkClient::request('POST', "/subscribers/query/delete", $clientConfig, body: ['query' => $query, 'ids' => $ids, 'action' => $action, 'target_list_ids' => $targetListIds, 'status' => $status], returnType: DeleteSubscriberByQueryResponse::class, decoder: 'json', operationId: 'deleteSubscriberByQuery', requestOptions: $requestOptions), DeleteSubscriberByQueryResponse::class);
    }


    /**
     * Deletes subscribers selected by an SQL expression or subscriber identifiers. Provide the expression as plain text or use a JSON body to specify `query`, `ids`, and any applicable `action`, `target_list_ids`, or `status` filters.
     *
     * bulk deletes based on an arbitrary SQL expression.
     *
     * @param string|SdkNotGiven $body
     * @return DeleteSubscriberByQueryTextResponse
     */
    public static function deleteSubscriberByQueryText(ClientConfig $clientConfig, string|SdkNotGiven $body = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): DeleteSubscriberByQueryTextResponse
    {

        return SdkClient::typedData(SdkClient::request('POST', "/subscribers/query/delete", $clientConfig, body: $body, contentType: 'text/plain', returnType: DeleteSubscriberByQueryTextResponse::class, decoder: 'json', operationId: 'deleteSubscriberByQueryText', requestOptions: $requestOptions), DeleteSubscriberByQueryTextResponse::class);
    }


    /**
     * Adds or removes subscribers from the blocklist based on an SQL expression or subscriber identifiers. Provide the expression as plain text or use a JSON body to specify `query`, `ids`, and any applicable `action`, `target_list_ids`, or `status` filters.
     *
     * bulk blocklists subscribers based on an arbitrary SQL expression. query: Optional `string` value serialized in the `query` wire field. · ids: The ids of the subscribers to be modified. · action: Whether to add, remove, or unsubscribe the users. · targetListIds: The ids of the lists to be modified. · status: confirmed, unconfirmed, or unsubscribed status.
     *
     * @param string|SdkNotGiven $query
     * @param list<int>|SdkNotGiven $ids
     * @param BlocklistSubscribersQueryAction|SdkNotGiven $action
     * @param int|SdkNotGiven $targetListIds
     * @param BlocklistSubscribersQueryStatus|SdkNotGiven $status
     * @return BlocklistSubscribersQueryResponse
     */
    public static function blocklistSubscribersQuery(ClientConfig $clientConfig, string|SdkNotGiven $query = SdkNotGiven::Value, array|SdkNotGiven $ids = SdkNotGiven::Value, BlocklistSubscribersQueryAction|SdkNotGiven $action = SdkNotGiven::Value, int|SdkNotGiven $targetListIds = SdkNotGiven::Value, BlocklistSubscribersQueryStatus|SdkNotGiven $status = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): BlocklistSubscribersQueryResponse
    {

        return SdkClient::typedData(SdkClient::request('PUT', "/subscribers/query/blocklist", $clientConfig, body: ['query' => $query, 'ids' => $ids, 'action' => $action, 'target_list_ids' => $targetListIds, 'status' => $status], returnType: BlocklistSubscribersQueryResponse::class, decoder: 'json', operationId: 'blocklistSubscribersQuery', requestOptions: $requestOptions), BlocklistSubscribersQueryResponse::class);
    }
}
