<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

class ManageBlocklistBySubscriberListResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $data;

    /**
     * @param bool|SdkNotGiven $data
     */
    public function __construct(
        bool|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::boolValue($data->data) : SdkNotGiven::Value),
        );
    }
}

class ManageBlocklistSubscribersByIdResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $data;

    /**
     * @param bool|SdkNotGiven $data
     */
    public function __construct(
        bool|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::boolValue($data->data) : SdkNotGiven::Value),
        );
    }
}

class GetSubscriberBouncesByIdResponse implements \JsonSerializable
{
    /** @var list<Bounce>|SdkNotGiven */
    public readonly array|SdkNotGiven $data;

    /**
     * @param list<Bounce>|SdkNotGiven $data
     */
    public function __construct(
        array|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? array_values(array_map(static fn($item) => SdkClient::hydrateClass($item, Bounce::class), SdkClient::arrayValue($data->data))) : SdkNotGiven::Value),
        );
    }
}

class DeleteSubscriberBouncesByIdResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $data;

    /**
     * @param bool|SdkNotGiven $data
     */
    public function __construct(
        bool|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::boolValue($data->data) : SdkNotGiven::Value),
        );
    }
}

class SubscriberSendOptinByIdResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $data;

    /**
     * @param bool|SdkNotGiven $data
     */
    public function __construct(
        bool|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::boolValue($data->data) : SdkNotGiven::Value),
        );
    }
}

class DeleteSubscriberByQueryResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $data;

    /**
     * @param bool|SdkNotGiven $data
     */
    public function __construct(
        bool|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::boolValue($data->data) : SdkNotGiven::Value),
        );
    }
}

class DeleteSubscriberByQueryTextResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $data;

    /**
     * @param bool|SdkNotGiven $data
     */
    public function __construct(
        bool|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::boolValue($data->data) : SdkNotGiven::Value),
        );
    }
}

class BlocklistSubscribersQueryResponse implements \JsonSerializable
{
    /** @var bool|SdkNotGiven */
    public readonly bool|SdkNotGiven $data;

    /**
     * @param bool|SdkNotGiven $data
     */
    public function __construct(
        bool|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::boolValue($data->data) : SdkNotGiven::Value),
        );
    }
}
