<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

final readonly class GetSubscribersOrderBy implements SdkOpenEnum
{
    public const NAME = "name";
    public const STATUS = "status";
    public const CREATED_AT = "created_at";
    public const UPDATED_AT = "updated_at";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}

final readonly class GetSubscribersOrder implements SdkOpenEnum
{
    public const ASC = "ASC";
    public const DESC = "DESC";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}

final readonly class ManageSubscriberListsAction implements SdkOpenEnum
{
    public const ADD = "add";
    public const REMOVE = "remove";
    public const UNSUBSCRIBE = "unsubscribe";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}

final readonly class ManageSubscriberListsStatus implements SdkOpenEnum
{
    public const CONFIRMED = "confirmed";
    public const UNCONFIRMED = "unconfirmed";
    public const UNSUBSCRIBED = "unsubscribed";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}

final readonly class ManageSubscriberListByIdAction implements SdkOpenEnum
{
    public const ADD = "add";
    public const REMOVE = "remove";
    public const UNSUBSCRIBE = "unsubscribe";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}

final readonly class ManageSubscriberListByIdStatus implements SdkOpenEnum
{
    public const CONFIRMED = "confirmed";
    public const UNCONFIRMED = "unconfirmed";
    public const UNSUBSCRIBED = "unsubscribed";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}

final readonly class ManageBlocklistBySubscriberListAction implements SdkOpenEnum
{
    public const ADD = "add";
    public const REMOVE = "remove";
    public const UNSUBSCRIBE = "unsubscribe";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}

final readonly class ManageBlocklistBySubscriberListStatus implements SdkOpenEnum
{
    public const CONFIRMED = "confirmed";
    public const UNCONFIRMED = "unconfirmed";
    public const UNSUBSCRIBED = "unsubscribed";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}

final readonly class ManageBlocklistSubscribersByIdAction implements SdkOpenEnum
{
    public const ADD = "add";
    public const REMOVE = "remove";
    public const UNSUBSCRIBE = "unsubscribe";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}

final readonly class ManageBlocklistSubscribersByIdStatus implements SdkOpenEnum
{
    public const CONFIRMED = "confirmed";
    public const UNCONFIRMED = "unconfirmed";
    public const UNSUBSCRIBED = "unsubscribed";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}

final readonly class DeleteSubscriberByQueryAction implements SdkOpenEnum
{
    public const ADD = "add";
    public const REMOVE = "remove";
    public const UNSUBSCRIBE = "unsubscribe";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}

final readonly class DeleteSubscriberByQueryStatus implements SdkOpenEnum
{
    public const CONFIRMED = "confirmed";
    public const UNCONFIRMED = "unconfirmed";
    public const UNSUBSCRIBED = "unsubscribed";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}

final readonly class BlocklistSubscribersQueryAction implements SdkOpenEnum
{
    public const ADD = "add";
    public const REMOVE = "remove";
    public const UNSUBSCRIBE = "unsubscribe";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}

final readonly class BlocklistSubscribersQueryStatus implements SdkOpenEnum
{
    public const CONFIRMED = "confirmed";
    public const UNCONFIRMED = "unconfirmed";
    public const UNSUBSCRIBED = "unsubscribed";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}

final readonly class ManageSubscriberListsByQueryAction implements SdkOpenEnum
{
    public const ADD = "add";
    public const REMOVE = "remove";
    public const UNSUBSCRIBE = "unsubscribe";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}

final readonly class ManageSubscriberListsByQueryStatus implements SdkOpenEnum
{
    public const CONFIRMED = "confirmed";
    public const UNCONFIRMED = "unconfirmed";
    public const UNSUBSCRIBED = "unsubscribed";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}

/**
 * Return all results without pagination
 */
final readonly class GetSubscribersPerPageEnum implements SdkOpenEnum
{
    public const ALL = "all";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}

class GetSubscribersResponseData implements \JsonSerializable
{
    /** @var list<Subscriber>|SdkNotGiven */
    public readonly array|SdkNotGiven $results;
    /** @var string|SdkNotGiven */
    public readonly string|SdkNotGiven $query;
    /** @var int|SdkNotGiven */
    public readonly int|SdkNotGiven $total;
    /** @var int|SdkNotGiven */
    public readonly int|SdkNotGiven $perPage;
    /** @var int|SdkNotGiven */
    public readonly int|SdkNotGiven $page;

    /**
     * @param list<Subscriber>|SdkNotGiven $results
     * @param string|SdkNotGiven $query
     * @param int|SdkNotGiven $total
     * @param int|SdkNotGiven $perPage
     * @param int|SdkNotGiven $page
     */
    public function __construct(
        array|SdkNotGiven $results = SdkNotGiven::Value,
        string|SdkNotGiven $query = SdkNotGiven::Value,
        int|SdkNotGiven $total = SdkNotGiven::Value,
        int|SdkNotGiven $perPage = SdkNotGiven::Value,
        int|SdkNotGiven $page = SdkNotGiven::Value,
    ) {
        $this->results = $results;
        $this->query = $query;
        $this->total = $total;
        $this->perPage = $perPage;
        $this->page = $page;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->results !== SdkNotGiven::Value) {
            $values["results"] = $this->results;
        }
        if ($this->query !== SdkNotGiven::Value) {
            $values["query"] = $this->query;
        }
        if ($this->total !== SdkNotGiven::Value) {
            $values["total"] = $this->total;
        }
        if ($this->perPage !== SdkNotGiven::Value) {
            $values["per_page"] = $this->perPage;
        }
        if ($this->page !== SdkNotGiven::Value) {
            $values["page"] = $this->page;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            results: (property_exists($data, "results") ? array_values(array_map(static fn($item) => SdkClient::hydrateClass($item, Subscriber::class), SdkClient::arrayValue($data->results))) : SdkNotGiven::Value),
            query: (property_exists($data, "query") ? SdkClient::stringValue($data->query) : SdkNotGiven::Value),
            total: (property_exists($data, "total") ? SdkClient::intValue($data->total) : SdkNotGiven::Value),
            perPage: (property_exists($data, "per_page") ? SdkClient::intValue($data->per_page) : SdkNotGiven::Value),
            page: (property_exists($data, "page") ? SdkClient::intValue($data->page) : SdkNotGiven::Value),
        );
    }
}
