<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

trait SubscribersMethodsPart2
{
    /**
     * Adds or removes subscribers from the blocklist based on an SQL expression or subscriber identifiers. Provide the expression as plain text or use a JSON body to specify `query`, `ids`, and any applicable `action`, `target_list_ids`, or `status` filters.
     *
     * bulk blocklists subscribers based on an arbitrary SQL expression.
     *
     * @param string|SdkNotGiven $body
     * @return BlocklistSubscribersQueryTextResponse
     */
    public static function blocklistSubscribersQueryText(ClientConfig $clientConfig, string|SdkNotGiven $body = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): BlocklistSubscribersQueryTextResponse
    {

        return SdkClient::typedData(SdkClient::request('PUT', "/subscribers/query/blocklist", $clientConfig, body: $body, contentType: 'text/plain', returnType: BlocklistSubscribersQueryTextResponse::class, decoder: 'json', operationId: 'blocklistSubscribersQueryText', requestOptions: $requestOptions), BlocklistSubscribersQueryTextResponse::class);
    }


    /**
     * Adds, removes, or unsubscribes subscribers from lists based on an SQL expression or subscriber identifiers. Provide the expression as plain text or use a JSON body to specify `query`, `ids`, and the applicable `action`, `target_list_ids`, or `status` filters.
     *
     * bulk adds/removes/unsubscribes subscribers from one or more lists based on an arbitrary SQL expression. query: Optional `string` value serialized in the `query` wire field. · ids: The ids of the subscribers to be modified. · action: Whether to add, remove, or unsubscribe the users. · targetListIds: The ids of the lists to be modified. · status: confirmed, unconfirmed, or unsubscribed status.
     *
     * @param string|SdkNotGiven $query
     * @param list<int>|SdkNotGiven $ids
     * @param ManageSubscriberListsByQueryAction|SdkNotGiven $action
     * @param int|SdkNotGiven $targetListIds
     * @param ManageSubscriberListsByQueryStatus|SdkNotGiven $status
     * @return ManageSubscriberListsByQueryResponse
     */
    public static function manageSubscriberListsByQuery(ClientConfig $clientConfig, string|SdkNotGiven $query = SdkNotGiven::Value, array|SdkNotGiven $ids = SdkNotGiven::Value, ManageSubscriberListsByQueryAction|SdkNotGiven $action = SdkNotGiven::Value, int|SdkNotGiven $targetListIds = SdkNotGiven::Value, ManageSubscriberListsByQueryStatus|SdkNotGiven $status = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): ManageSubscriberListsByQueryResponse
    {

        return SdkClient::typedData(SdkClient::request('PUT', "/subscribers/query/lists", $clientConfig, body: ['query' => $query, 'ids' => $ids, 'action' => $action, 'target_list_ids' => $targetListIds, 'status' => $status], returnType: ManageSubscriberListsByQueryResponse::class, decoder: 'json', operationId: 'manageSubscriberListsByQuery', requestOptions: $requestOptions), ManageSubscriberListsByQueryResponse::class);
    }


    /**
     * Adds, removes, or unsubscribes subscribers from lists based on an SQL expression or subscriber identifiers. Provide the expression as plain text or use a JSON body to specify `query`, `ids`, and the applicable `action`, `target_list_ids`, or `status` filters.
     *
     * bulk adds/removes/unsubscribes subscribers from one or more lists based on an arbitrary SQL expression.
     *
     * @param string|SdkNotGiven $body
     * @return ManageSubscriberListsByQueryTextResponse
     */
    public static function manageSubscriberListsByQueryText(ClientConfig $clientConfig, string|SdkNotGiven $body = SdkNotGiven::Value, ?RequestOptions $requestOptions = null): ManageSubscriberListsByQueryTextResponse
    {

        return SdkClient::typedData(SdkClient::request('PUT', "/subscribers/query/lists", $clientConfig, body: $body, contentType: 'text/plain', returnType: ManageSubscriberListsByQueryTextResponse::class, decoder: 'json', operationId: 'manageSubscriberListsByQueryText', requestOptions: $requestOptions), ManageSubscriberListsByQueryTextResponse::class);
    }
}
