<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

/**
 * Typed representation of the `CampaignStats` API schema.
 */
class CampaignStats implements \JsonSerializable
{
    /**
     * Optional `integer` value serialized in the `id` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $id;
    /**
     * Optional `string` value serialized in the `status` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $status;
    /**
     * Optional `integer` value serialized in the `to_send` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $toSend;
    /**
     * Optional `integer` value serialized in the `sent` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $sent;
    /**
     * Optional `date`-formatted value serialized in the `started_at` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $startedAt;
    /**
     * Optional `date`-formatted value serialized in the `updated_at` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $updatedAt;
    /**
     * Optional `integer` value serialized in the `rate` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $rate;
    /**
     * Optional `integer` value serialized in the `net_rate` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $netRate;

    /**
     * @param int|SdkNotGiven $id
     * @param string|SdkNotGiven $status
     * @param int|SdkNotGiven $toSend
     * @param int|SdkNotGiven $sent
     * @param string|SdkNotGiven $startedAt
     * @param string|SdkNotGiven $updatedAt
     * @param int|SdkNotGiven $rate
     * @param int|SdkNotGiven $netRate
     */
    public function __construct(
        int|SdkNotGiven $id = SdkNotGiven::Value,
        string|SdkNotGiven $status = SdkNotGiven::Value,
        int|SdkNotGiven $toSend = SdkNotGiven::Value,
        int|SdkNotGiven $sent = SdkNotGiven::Value,
        string|SdkNotGiven $startedAt = SdkNotGiven::Value,
        string|SdkNotGiven $updatedAt = SdkNotGiven::Value,
        int|SdkNotGiven $rate = SdkNotGiven::Value,
        int|SdkNotGiven $netRate = SdkNotGiven::Value,
    ) {
        $this->id = $id;
        $this->status = $status;
        $this->toSend = $toSend;
        $this->sent = $sent;
        $this->startedAt = $startedAt;
        $this->updatedAt = $updatedAt;
        $this->rate = $rate;
        $this->netRate = $netRate;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->id !== SdkNotGiven::Value) {
            $values["id"] = $this->id;
        }
        if ($this->status !== SdkNotGiven::Value) {
            $values["status"] = $this->status;
        }
        if ($this->toSend !== SdkNotGiven::Value) {
            $values["to_send"] = $this->toSend;
        }
        if ($this->sent !== SdkNotGiven::Value) {
            $values["sent"] = $this->sent;
        }
        if ($this->startedAt !== SdkNotGiven::Value) {
            $values["started_at"] = $this->startedAt;
        }
        if ($this->updatedAt !== SdkNotGiven::Value) {
            $values["updated_at"] = $this->updatedAt;
        }
        if ($this->rate !== SdkNotGiven::Value) {
            $values["rate"] = $this->rate;
        }
        if ($this->netRate !== SdkNotGiven::Value) {
            $values["net_rate"] = $this->netRate;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            id: (property_exists($data, "id") ? SdkClient::intValue($data->id) : SdkNotGiven::Value),
            status: (property_exists($data, "status") ? SdkClient::stringValue($data->status) : SdkNotGiven::Value),
            toSend: (property_exists($data, "to_send") ? SdkClient::intValue($data->to_send) : SdkNotGiven::Value),
            sent: (property_exists($data, "sent") ? SdkClient::intValue($data->sent) : SdkNotGiven::Value),
            startedAt: (property_exists($data, "started_at") ? SdkClient::stringValue($data->started_at) : SdkNotGiven::Value),
            updatedAt: (property_exists($data, "updated_at") ? SdkClient::stringValue($data->updated_at) : SdkNotGiven::Value),
            rate: (property_exists($data, "rate") ? SdkClient::intValue($data->rate) : SdkNotGiven::Value),
            netRate: (property_exists($data, "net_rate") ? SdkClient::intValue($data->net_rate) : SdkNotGiven::Value),
        );
    }
}
