<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

/**
 * Typed representation of the `CampaignContentRequest` API schema.
 */
class CampaignContentRequest implements \JsonSerializable
{
    /**
     * Optional `integer` value serialized in the `id` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $id;
    /**
     * Optional `string` value serialized in the `created_at` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $createdAt;
    /**
     * Optional `string` value serialized in the `updated_at` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $updatedAt;
    /**
     * Optional `integer` value serialized in the `CampaignID` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $campaignId;
    /**
     * Optional `integer` value serialized in the `views` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $views;
    /**
     * Optional `integer` value serialized in the `clicks` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $clicks;
    /**
     * Optional array value serialized in the `lists` wire field.
     *
     * @var list<CampaignContentRequestListsItem>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $lists;
    /**
     * Optional `string` value serialized in the `started_at` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $startedAt;
    /**
     * Optional `integer` value serialized in the `to_send` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $toSend;
    /**
     * Optional `integer` value serialized in the `sent` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $sent;
    /**
     * Optional `string` value serialized in the `uuid` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $uuid;
    /**
     * Optional enumerated value serialized in the `type` wire field.
     *
     * @var CampaignContentRequestTypeEnum|string|SdkNotGiven
     */
    public readonly CampaignContentRequestTypeEnum|string|SdkNotGiven $type;
    /**
     * Optional `string` value serialized in the `name` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $name;
    /**
     * Optional `string` value serialized in the `subject` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $subject;
    /**
     * Optional `string` value serialized in the `from_email` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $fromEmail;
    /**
     * Optional `string` value serialized in the `body` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $body;
    /**
     * Optional `string` value serialized in the `send_at` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $sendAt;
    /**
     * Optional `string` value serialized in the `status` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $status;
    /**
     * Optional enumerated value serialized in the `content_type` wire field.
     *
     * @var CampaignContentRequestContentTypeEnum|string|SdkNotGiven
     */
    public readonly CampaignContentRequestContentTypeEnum|string|SdkNotGiven $contentType;
    /**
     * Optional array value serialized in the `tags` wire field.
     *
     * @var list<string>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $tags;
    /**
     * Optional `integer` value serialized in the `template_id` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $templateId;
    /**
     * Optional `string` value serialized in the `messenger` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $messenger;
    /**
     * Optional `string` value serialized in the `from` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $from;
    /**
     * Optional `string` value serialized in the `to` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $to;

    /**
     * @param int|SdkNotGiven $id
     * @param string|SdkNotGiven $createdAt
     * @param string|SdkNotGiven $updatedAt
     * @param int|SdkNotGiven $campaignId
     * @param int|SdkNotGiven $views
     * @param int|SdkNotGiven $clicks
     * @param list<CampaignContentRequestListsItem>|SdkNotGiven $lists
     * @param string|SdkNotGiven $startedAt
     * @param int|SdkNotGiven $toSend
     * @param int|SdkNotGiven $sent
     * @param string|SdkNotGiven $uuid
     * @param CampaignContentRequestTypeEnum|string|SdkNotGiven $type
     * @param string|SdkNotGiven $name
     * @param string|SdkNotGiven $subject
     * @param string|SdkNotGiven $fromEmail
     * @param string|SdkNotGiven $body
     * @param string|SdkNotGiven $sendAt
     * @param string|SdkNotGiven $status
     * @param CampaignContentRequestContentTypeEnum|string|SdkNotGiven $contentType
     * @param list<string>|SdkNotGiven $tags
     * @param int|SdkNotGiven $templateId
     * @param string|SdkNotGiven $messenger
     * @param string|SdkNotGiven $from
     * @param string|SdkNotGiven $to
     */
    public function __construct(
        int|SdkNotGiven $id = SdkNotGiven::Value,
        string|SdkNotGiven $createdAt = SdkNotGiven::Value,
        string|SdkNotGiven $updatedAt = SdkNotGiven::Value,
        int|SdkNotGiven $campaignId = SdkNotGiven::Value,
        int|SdkNotGiven $views = SdkNotGiven::Value,
        int|SdkNotGiven $clicks = SdkNotGiven::Value,
        array|SdkNotGiven $lists = SdkNotGiven::Value,
        string|SdkNotGiven $startedAt = SdkNotGiven::Value,
        int|SdkNotGiven $toSend = SdkNotGiven::Value,
        int|SdkNotGiven $sent = SdkNotGiven::Value,
        string|SdkNotGiven $uuid = SdkNotGiven::Value,
        CampaignContentRequestTypeEnum|string|SdkNotGiven $type = SdkNotGiven::Value,
        string|SdkNotGiven $name = SdkNotGiven::Value,
        string|SdkNotGiven $subject = SdkNotGiven::Value,
        string|SdkNotGiven $fromEmail = SdkNotGiven::Value,
        string|SdkNotGiven $body = SdkNotGiven::Value,
        string|SdkNotGiven $sendAt = SdkNotGiven::Value,
        string|SdkNotGiven $status = SdkNotGiven::Value,
        CampaignContentRequestContentTypeEnum|string|SdkNotGiven $contentType = SdkNotGiven::Value,
        array|SdkNotGiven $tags = SdkNotGiven::Value,
        int|SdkNotGiven $templateId = SdkNotGiven::Value,
        string|SdkNotGiven $messenger = SdkNotGiven::Value,
        string|SdkNotGiven $from = SdkNotGiven::Value,
        string|SdkNotGiven $to = SdkNotGiven::Value,
    ) {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->campaignId = $campaignId;
        $this->views = $views;
        $this->clicks = $clicks;
        $this->lists = $lists;
        $this->startedAt = $startedAt;
        $this->toSend = $toSend;
        $this->sent = $sent;
        $this->uuid = $uuid;
        $this->type = $type;
        $this->name = $name;
        $this->subject = $subject;
        $this->fromEmail = $fromEmail;
        $this->body = $body;
        $this->sendAt = $sendAt;
        $this->status = $status;
        $this->contentType = $contentType;
        $this->tags = $tags;
        $this->templateId = $templateId;
        $this->messenger = $messenger;
        $this->from = $from;
        $this->to = $to;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->id !== SdkNotGiven::Value) {
            $values["id"] = $this->id;
        }
        if ($this->createdAt !== SdkNotGiven::Value) {
            $values["created_at"] = $this->createdAt;
        }
        if ($this->updatedAt !== SdkNotGiven::Value) {
            $values["updated_at"] = $this->updatedAt;
        }
        if ($this->campaignId !== SdkNotGiven::Value) {
            $values["CampaignID"] = $this->campaignId;
        }
        if ($this->views !== SdkNotGiven::Value) {
            $values["views"] = $this->views;
        }
        if ($this->clicks !== SdkNotGiven::Value) {
            $values["clicks"] = $this->clicks;
        }
        if ($this->lists !== SdkNotGiven::Value) {
            $values["lists"] = $this->lists;
        }
        if ($this->startedAt !== SdkNotGiven::Value) {
            $values["started_at"] = $this->startedAt;
        }
        if ($this->toSend !== SdkNotGiven::Value) {
            $values["to_send"] = $this->toSend;
        }
        if ($this->sent !== SdkNotGiven::Value) {
            $values["sent"] = $this->sent;
        }
        if ($this->uuid !== SdkNotGiven::Value) {
            $values["uuid"] = $this->uuid;
        }
        if ($this->type !== SdkNotGiven::Value) {
            $values["type"] = $this->type;
        }
        if ($this->name !== SdkNotGiven::Value) {
            $values["name"] = $this->name;
        }
        if ($this->subject !== SdkNotGiven::Value) {
            $values["subject"] = $this->subject;
        }
        if ($this->fromEmail !== SdkNotGiven::Value) {
            $values["from_email"] = $this->fromEmail;
        }
        if ($this->body !== SdkNotGiven::Value) {
            $values["body"] = $this->body;
        }
        if ($this->sendAt !== SdkNotGiven::Value) {
            $values["send_at"] = $this->sendAt;
        }
        if ($this->status !== SdkNotGiven::Value) {
            $values["status"] = $this->status;
        }
        if ($this->contentType !== SdkNotGiven::Value) {
            $values["content_type"] = $this->contentType;
        }
        if ($this->tags !== SdkNotGiven::Value) {
            $values["tags"] = $this->tags;
        }
        if ($this->templateId !== SdkNotGiven::Value) {
            $values["template_id"] = $this->templateId;
        }
        if ($this->messenger !== SdkNotGiven::Value) {
            $values["messenger"] = $this->messenger;
        }
        if ($this->from !== SdkNotGiven::Value) {
            $values["from"] = $this->from;
        }
        if ($this->to !== SdkNotGiven::Value) {
            $values["to"] = $this->to;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            id: (property_exists($data, "id") ? SdkClient::intValue($data->id) : SdkNotGiven::Value),
            createdAt: (property_exists($data, "created_at") ? SdkClient::stringValue($data->created_at) : SdkNotGiven::Value),
            updatedAt: (property_exists($data, "updated_at") ? SdkClient::stringValue($data->updated_at) : SdkNotGiven::Value),
            campaignId: (property_exists($data, "CampaignID") ? SdkClient::intValue($data->CampaignID) : SdkNotGiven::Value),
            views: (property_exists($data, "views") ? SdkClient::intValue($data->views) : SdkNotGiven::Value),
            clicks: (property_exists($data, "clicks") ? SdkClient::intValue($data->clicks) : SdkNotGiven::Value),
            lists: (property_exists($data, "lists") ? array_values(array_map(static fn ($item) => SdkClient::hydrateClass($item, CampaignContentRequestListsItem::class), SdkClient::arrayValue($data->lists))) : SdkNotGiven::Value),
            startedAt: (property_exists($data, "started_at") ? SdkClient::stringValue($data->started_at) : SdkNotGiven::Value),
            toSend: (property_exists($data, "to_send") ? SdkClient::intValue($data->to_send) : SdkNotGiven::Value),
            sent: (property_exists($data, "sent") ? SdkClient::intValue($data->sent) : SdkNotGiven::Value),
            uuid: (property_exists($data, "uuid") ? SdkClient::stringValue($data->uuid) : SdkNotGiven::Value),
            type: (property_exists($data, "type") ? SdkClient::hydrateStringEnumOrString($data->type, CampaignContentRequestTypeEnum::class) : SdkNotGiven::Value),
            name: (property_exists($data, "name") ? SdkClient::stringValue($data->name) : SdkNotGiven::Value),
            subject: (property_exists($data, "subject") ? SdkClient::stringValue($data->subject) : SdkNotGiven::Value),
            fromEmail: (property_exists($data, "from_email") ? SdkClient::stringValue($data->from_email) : SdkNotGiven::Value),
            body: (property_exists($data, "body") ? SdkClient::stringValue($data->body) : SdkNotGiven::Value),
            sendAt: (property_exists($data, "send_at") ? SdkClient::stringValue($data->send_at) : SdkNotGiven::Value),
            status: (property_exists($data, "status") ? SdkClient::stringValue($data->status) : SdkNotGiven::Value),
            contentType: (property_exists($data, "content_type") ? SdkClient::hydrateStringEnumOrString($data->content_type, CampaignContentRequestContentTypeEnum::class) : SdkNotGiven::Value),
            tags: (property_exists($data, "tags") ? array_values(array_map(static fn ($item) => SdkClient::stringValue($item), SdkClient::arrayValue($data->tags))) : SdkNotGiven::Value),
            templateId: (property_exists($data, "template_id") ? SdkClient::intValue($data->template_id) : SdkNotGiven::Value),
            messenger: (property_exists($data, "messenger") ? SdkClient::stringValue($data->messenger) : SdkNotGiven::Value),
            from: (property_exists($data, "from") ? SdkClient::stringValue($data->from) : SdkNotGiven::Value),
            to: (property_exists($data, "to") ? SdkClient::stringValue($data->to) : SdkNotGiven::Value),
        );
    }
}
