<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

/**
 * Optional object value serialized in the `send_at` wire field.
 */
class CampaignRequestSendAt implements \JsonSerializable
{
    /**
     * Optional array value serialized in the `headers` wire field.
     *
     * @var list<array<array-key,mixed>>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $headers;
    /**
     * Optional `number` value serialized in the `template_id` wire field.
     *
     * @var float|SdkNotGiven
     */
    public readonly float|SdkNotGiven $templateId;

    /**
     * @param list<array<array-key,mixed>>|SdkNotGiven $headers
     * @param float|SdkNotGiven $templateId
     */
    public function __construct(
        array|SdkNotGiven $headers = SdkNotGiven::Value,
        float|SdkNotGiven $templateId = SdkNotGiven::Value,
    ) {
        $this->headers = $headers;
        $this->templateId = $templateId;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->headers !== SdkNotGiven::Value) {
            $values["headers"] = $this->headers;
        }
        if ($this->templateId !== SdkNotGiven::Value) {
            $values["template_id"] = $this->templateId;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            headers: (property_exists($data, "headers") ? array_values(array_map(static fn($item) => SdkClient::stringMapValue($item), SdkClient::arrayValue($data->headers))) : SdkNotGiven::Value),
            templateId: (property_exists($data, "template_id") ? SdkClient::floatValue($data->template_id) : SdkNotGiven::Value),
        );
    }
}

/**
 * Typed representation of the `CampaignRequest` API schema.
 */
class CampaignRequest implements \JsonSerializable
{
    /**
     * Optional `string` value serialized in the `name` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $name;
    /**
     * Optional `string` value serialized in the `subject` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $subject;
    /**
     * Optional array value serialized in the `lists` wire field.
     *
     * @var list<float>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $lists;
    /**
     * Optional `string` value serialized in the `from_email` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $fromEmail;
    /**
     * Optional `string` value serialized in the `content_type` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $contentType;
    /**
     * Optional `string` value serialized in the `messenger` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $messenger;
    /**
     * Optional `string` value serialized in the `type` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $type;
    /**
     * Optional array value serialized in the `tags` wire field.
     *
     * @var list<string>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $tags;
    /**
     * Optional `boolean` value serialized in the `send_later` wire field.
     *
     * @var bool|SdkNotGiven
     */
    public readonly bool|SdkNotGiven $sendLater;
    /**
     * Optional object value serialized in the `send_at` wire field.
     *
     * @var CampaignRequestSendAt|SdkNotGiven
     */
    public readonly CampaignRequestSendAt|SdkNotGiven $sendAt;

    /**
     * @param string|SdkNotGiven $name
     * @param string|SdkNotGiven $subject
     * @param list<float>|SdkNotGiven $lists
     * @param string|SdkNotGiven $fromEmail
     * @param string|SdkNotGiven $contentType
     * @param string|SdkNotGiven $messenger
     * @param string|SdkNotGiven $type
     * @param list<string>|SdkNotGiven $tags
     * @param bool|SdkNotGiven $sendLater
     * @param CampaignRequestSendAt|SdkNotGiven $sendAt
     */
    public function __construct(
        string|SdkNotGiven $name = SdkNotGiven::Value,
        string|SdkNotGiven $subject = SdkNotGiven::Value,
        array|SdkNotGiven $lists = SdkNotGiven::Value,
        string|SdkNotGiven $fromEmail = SdkNotGiven::Value,
        string|SdkNotGiven $contentType = SdkNotGiven::Value,
        string|SdkNotGiven $messenger = SdkNotGiven::Value,
        string|SdkNotGiven $type = SdkNotGiven::Value,
        array|SdkNotGiven $tags = SdkNotGiven::Value,
        bool|SdkNotGiven $sendLater = SdkNotGiven::Value,
        CampaignRequestSendAt|SdkNotGiven $sendAt = SdkNotGiven::Value,
    ) {
        $this->name = $name;
        $this->subject = $subject;
        $this->lists = $lists;
        $this->fromEmail = $fromEmail;
        $this->contentType = $contentType;
        $this->messenger = $messenger;
        $this->type = $type;
        $this->tags = $tags;
        $this->sendLater = $sendLater;
        $this->sendAt = $sendAt;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->name !== SdkNotGiven::Value) {
            $values["name"] = $this->name;
        }
        if ($this->subject !== SdkNotGiven::Value) {
            $values["subject"] = $this->subject;
        }
        if ($this->lists !== SdkNotGiven::Value) {
            $values["lists"] = $this->lists;
        }
        if ($this->fromEmail !== SdkNotGiven::Value) {
            $values["from_email"] = $this->fromEmail;
        }
        if ($this->contentType !== SdkNotGiven::Value) {
            $values["content_type"] = $this->contentType;
        }
        if ($this->messenger !== SdkNotGiven::Value) {
            $values["messenger"] = $this->messenger;
        }
        if ($this->type !== SdkNotGiven::Value) {
            $values["type"] = $this->type;
        }
        if ($this->tags !== SdkNotGiven::Value) {
            $values["tags"] = $this->tags;
        }
        if ($this->sendLater !== SdkNotGiven::Value) {
            $values["send_later"] = $this->sendLater;
        }
        if ($this->sendAt !== SdkNotGiven::Value) {
            $values["send_at"] = $this->sendAt;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            name: (property_exists($data, "name") ? SdkClient::stringValue($data->name) : SdkNotGiven::Value),
            subject: (property_exists($data, "subject") ? SdkClient::stringValue($data->subject) : SdkNotGiven::Value),
            lists: (property_exists($data, "lists") ? array_values(array_map(static fn($item) => SdkClient::floatValue($item), SdkClient::arrayValue($data->lists))) : SdkNotGiven::Value),
            fromEmail: (property_exists($data, "from_email") ? SdkClient::stringValue($data->from_email) : SdkNotGiven::Value),
            contentType: (property_exists($data, "content_type") ? SdkClient::stringValue($data->content_type) : SdkNotGiven::Value),
            messenger: (property_exists($data, "messenger") ? SdkClient::stringValue($data->messenger) : SdkNotGiven::Value),
            type: (property_exists($data, "type") ? SdkClient::stringValue($data->type) : SdkNotGiven::Value),
            tags: (property_exists($data, "tags") ? array_values(array_map(static fn($item) => SdkClient::stringValue($item), SdkClient::arrayValue($data->tags))) : SdkNotGiven::Value),
            sendLater: (property_exists($data, "send_later") ? SdkClient::boolValue($data->send_later) : SdkNotGiven::Value),
            sendAt: (property_exists($data, "send_at") ? SdkClient::hydrateClass($data->send_at, CampaignRequestSendAt::class) : SdkNotGiven::Value),
        );
    }
}
