<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

/**
 * Typed representation of the `CampaignAnalyticsCount` API schema.
 */
class CampaignAnalyticsCount implements \JsonSerializable
{
    /**
     * Optional `integer` value serialized in the `campaign_id` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $campaignId;
    /**
     * Optional `integer` value serialized in the `count` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $count;
    /**
     * Optional `date-time`-formatted value serialized in the `timestamp` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $timestamp;

    /**
     * @param int|SdkNotGiven $campaignId
     * @param int|SdkNotGiven $count
     * @param string|SdkNotGiven $timestamp
     */
    public function __construct(
        int|SdkNotGiven $campaignId = SdkNotGiven::Value,
        int|SdkNotGiven $count = SdkNotGiven::Value,
        string|SdkNotGiven $timestamp = SdkNotGiven::Value,
    ) {
        $this->campaignId = $campaignId;
        $this->count = $count;
        $this->timestamp = $timestamp;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->campaignId !== SdkNotGiven::Value) {
            $values["campaign_id"] = $this->campaignId;
        }
        if ($this->count !== SdkNotGiven::Value) {
            $values["count"] = $this->count;
        }
        if ($this->timestamp !== SdkNotGiven::Value) {
            $values["timestamp"] = $this->timestamp;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            campaignId: (property_exists($data, "campaign_id") ? SdkClient::intValue($data->campaign_id) : SdkNotGiven::Value),
            count: (property_exists($data, "count") ? SdkClient::intValue($data->count) : SdkNotGiven::Value),
            timestamp: (property_exists($data, "timestamp") ? SdkClient::stringValue($data->timestamp) : SdkNotGiven::Value),
        );
    }
}

/**
 * Required object value serialized in the `lists[]` wire field.
 */
class CampaignContentRequestListsItem implements \JsonSerializable
{
    /**
     * Optional `integer` value serialized in the `id` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $id;
    /**
     * Optional `string` value serialized in the `name` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $name;

    /**
     * @param int|SdkNotGiven $id
     * @param string|SdkNotGiven $name
     */
    public function __construct(
        int|SdkNotGiven $id = SdkNotGiven::Value,
        string|SdkNotGiven $name = SdkNotGiven::Value,
    ) {
        $this->id = $id;
        $this->name = $name;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->id !== SdkNotGiven::Value) {
            $values["id"] = $this->id;
        }
        if ($this->name !== SdkNotGiven::Value) {
            $values["name"] = $this->name;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            id: (property_exists($data, "id") ? SdkClient::intValue($data->id) : SdkNotGiven::Value),
            name: (property_exists($data, "name") ? SdkClient::stringValue($data->name) : SdkNotGiven::Value),
        );
    }
}

/**
 * Optional enumerated value serialized in the `type` wire field.
 */
final readonly class CampaignContentRequestTypeEnum implements SdkOpenEnum
{
    public const REGULAR = "regular";
    public const OPTIN = "optin";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}

/**
 * Optional enumerated value serialized in the `content_type` wire field.
 */
final readonly class CampaignContentRequestContentTypeEnum implements SdkOpenEnum
{
    public const RICHTEXT = "richtext";
    public const HTML = "html";
    public const MARKDOWN = "markdown";
    public const PLAIN = "plain";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static
    {
        return new self((string) $value);
    }
    public static function tryFrom(string|int|null $value): ?static
    {
        return $value === null ? null : self::from($value);
    }
    public function getValue(): string
    {
        return $this->value;
    }
    public function jsonSerialize(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return (string) $this->value;
    }
}
