<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

/**
 * Optional object value serialized in the `data` wire field.
 */
class ImportStatusData implements \JsonSerializable
{
    /**
     * Optional `string` value serialized in the `name` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $name;
    /**
     * Optional `integer` value serialized in the `total` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $total;
    /**
     * Optional `integer` value serialized in the `imported` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $imported;
    /**
     * Optional `string` value serialized in the `status` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $status;

    /**
     * @param string|SdkNotGiven $name
     * @param int|SdkNotGiven $total
     * @param int|SdkNotGiven $imported
     * @param string|SdkNotGiven $status
     */
    public function __construct(
        string|SdkNotGiven $name = SdkNotGiven::Value,
        int|SdkNotGiven $total = SdkNotGiven::Value,
        int|SdkNotGiven $imported = SdkNotGiven::Value,
        string|SdkNotGiven $status = SdkNotGiven::Value,
    ) {
        $this->name = $name;
        $this->total = $total;
        $this->imported = $imported;
        $this->status = $status;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->name !== SdkNotGiven::Value) {
            $values["name"] = $this->name;
        }
        if ($this->total !== SdkNotGiven::Value) {
            $values["total"] = $this->total;
        }
        if ($this->imported !== SdkNotGiven::Value) {
            $values["imported"] = $this->imported;
        }
        if ($this->status !== SdkNotGiven::Value) {
            $values["status"] = $this->status;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            name: (property_exists($data, "name") ? SdkClient::stringValue($data->name) : SdkNotGiven::Value),
            total: (property_exists($data, "total") ? SdkClient::intValue($data->total) : SdkNotGiven::Value),
            imported: (property_exists($data, "imported") ? SdkClient::intValue($data->imported) : SdkNotGiven::Value),
            status: (property_exists($data, "status") ? SdkClient::stringValue($data->status) : SdkNotGiven::Value),
        );
    }
}

/**
 * Typed representation of the `ImportStatus` API schema.
 */
class ImportStatus implements \JsonSerializable
{
    /**
     * Optional object value serialized in the `data` wire field.
     *
     * @var ImportStatusData|SdkNotGiven
     */
    public readonly ImportStatusData|SdkNotGiven $data;

    /**
     * @param ImportStatusData|SdkNotGiven $data
     */
    public function __construct(
        ImportStatusData|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, ImportStatusData::class) : SdkNotGiven::Value),
        );
    }
}
