<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

/**
 * Typed representation of the `ListModel` API schema.
 */
class ListModel implements \JsonSerializable
{
    /**
     * Optional `integer` value serialized in the `id` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $id;
    /**
     * Optional `string` value serialized in the `created_at` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $createdAt;
    /**
     * Optional `string` value serialized in the `updated_at` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $updatedAt;
    /**
     * Optional `string` value serialized in the `uuid` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $uuid;
    /**
     * Optional `string` value serialized in the `name` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $name;
    /**
     * Optional `string` value serialized in the `type` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $type;
    /**
     * Optional `string` value serialized in the `optin` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $optin;
    /**
     * Optional array value serialized in the `tags` wire field.
     *
     * @var list<string>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $tags;
    /**
     * Optional `integer` value serialized in the `subscriber_count` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $subscriberCount;
    /**
     * Optional `string` value serialized in the `description` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $description;

    /**
     * @param int|SdkNotGiven $id
     * @param string|SdkNotGiven $createdAt
     * @param string|SdkNotGiven $updatedAt
     * @param string|SdkNotGiven $uuid
     * @param string|SdkNotGiven $name
     * @param string|SdkNotGiven $type
     * @param string|SdkNotGiven $optin
     * @param list<string>|SdkNotGiven $tags
     * @param int|SdkNotGiven $subscriberCount
     * @param string|SdkNotGiven $description
     */
    public function __construct(
        int|SdkNotGiven $id = SdkNotGiven::Value,
        string|SdkNotGiven $createdAt = SdkNotGiven::Value,
        string|SdkNotGiven $updatedAt = SdkNotGiven::Value,
        string|SdkNotGiven $uuid = SdkNotGiven::Value,
        string|SdkNotGiven $name = SdkNotGiven::Value,
        string|SdkNotGiven $type = SdkNotGiven::Value,
        string|SdkNotGiven $optin = SdkNotGiven::Value,
        array|SdkNotGiven $tags = SdkNotGiven::Value,
        int|SdkNotGiven $subscriberCount = SdkNotGiven::Value,
        string|SdkNotGiven $description = SdkNotGiven::Value,
    ) {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->uuid = $uuid;
        $this->name = $name;
        $this->type = $type;
        $this->optin = $optin;
        $this->tags = $tags;
        $this->subscriberCount = $subscriberCount;
        $this->description = $description;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->id !== SdkNotGiven::Value) {
            $values["id"] = $this->id;
        }
        if ($this->createdAt !== SdkNotGiven::Value) {
            $values["created_at"] = $this->createdAt;
        }
        if ($this->updatedAt !== SdkNotGiven::Value) {
            $values["updated_at"] = $this->updatedAt;
        }
        if ($this->uuid !== SdkNotGiven::Value) {
            $values["uuid"] = $this->uuid;
        }
        if ($this->name !== SdkNotGiven::Value) {
            $values["name"] = $this->name;
        }
        if ($this->type !== SdkNotGiven::Value) {
            $values["type"] = $this->type;
        }
        if ($this->optin !== SdkNotGiven::Value) {
            $values["optin"] = $this->optin;
        }
        if ($this->tags !== SdkNotGiven::Value) {
            $values["tags"] = $this->tags;
        }
        if ($this->subscriberCount !== SdkNotGiven::Value) {
            $values["subscriber_count"] = $this->subscriberCount;
        }
        if ($this->description !== SdkNotGiven::Value) {
            $values["description"] = $this->description;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            id: (property_exists($data, "id") ? SdkClient::intValue($data->id) : SdkNotGiven::Value),
            createdAt: (property_exists($data, "created_at") ? SdkClient::stringValue($data->created_at) : SdkNotGiven::Value),
            updatedAt: (property_exists($data, "updated_at") ? SdkClient::stringValue($data->updated_at) : SdkNotGiven::Value),
            uuid: (property_exists($data, "uuid") ? SdkClient::stringValue($data->uuid) : SdkNotGiven::Value),
            name: (property_exists($data, "name") ? SdkClient::stringValue($data->name) : SdkNotGiven::Value),
            type: (property_exists($data, "type") ? SdkClient::stringValue($data->type) : SdkNotGiven::Value),
            optin: (property_exists($data, "optin") ? SdkClient::stringValue($data->optin) : SdkNotGiven::Value),
            tags: (property_exists($data, "tags") ? array_values(array_map(static fn ($item) => SdkClient::stringValue($item), SdkClient::arrayValue($data->tags))) : SdkNotGiven::Value),
            subscriberCount: (property_exists($data, "subscriber_count") ? SdkClient::intValue($data->subscriber_count) : SdkNotGiven::Value),
            description: (property_exists($data, "description") ? SdkClient::stringValue($data->description) : SdkNotGiven::Value),
        );
    }
}

/**
 * Optional enumerated value serialized in the `type` wire field.
 */
final readonly class NewListTypeEnum implements SdkOpenEnum
{
    public const PUBLIC = "public";
    public const PRIVATE = "private";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static { return new self((string) $value); }
    public static function tryFrom(string|int|null $value): ?static { return $value === null ? null : self::from($value); }
    public function getValue(): string { return $this->value; }
    public function jsonSerialize(): string { return $this->value; }
    public function __toString(): string { return (string) $this->value; }
}

/**
 * Optional enumerated value serialized in the `optin` wire field.
 */
final readonly class NewListOptinEnum implements SdkOpenEnum
{
    public const SINGLE = "single";
    public const DOUBLE = "double";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static { return new self((string) $value); }
    public static function tryFrom(string|int|null $value): ?static { return $value === null ? null : self::from($value); }
    public function getValue(): string { return $this->value; }
    public function jsonSerialize(): string { return $this->value; }
    public function __toString(): string { return (string) $this->value; }
}

/**
 * Typed representation of the `NewList` API schema.
 */
class NewList implements \JsonSerializable
{
    /**
     * Optional `string` value serialized in the `name` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $name;
    /**
     * Optional enumerated value serialized in the `type` wire field.
     *
     * @var NewListTypeEnum|string|SdkNotGiven
     */
    public readonly NewListTypeEnum|string|SdkNotGiven $type;
    /**
     * Optional enumerated value serialized in the `optin` wire field.
     *
     * @var NewListOptinEnum|string|SdkNotGiven
     */
    public readonly NewListOptinEnum|string|SdkNotGiven $optin;
    /**
     * Optional array value serialized in the `tags` wire field.
     *
     * @var list<string>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $tags;
    /**
     * Optional `string` value serialized in the `description` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $description;

    /**
     * @param string|SdkNotGiven $name
     * @param NewListTypeEnum|string|SdkNotGiven $type
     * @param NewListOptinEnum|string|SdkNotGiven $optin
     * @param list<string>|SdkNotGiven $tags
     * @param string|SdkNotGiven $description
     */
    public function __construct(
        string|SdkNotGiven $name = SdkNotGiven::Value,
        NewListTypeEnum|string|SdkNotGiven $type = SdkNotGiven::Value,
        NewListOptinEnum|string|SdkNotGiven $optin = SdkNotGiven::Value,
        array|SdkNotGiven $tags = SdkNotGiven::Value,
        string|SdkNotGiven $description = SdkNotGiven::Value,
    ) {
        $this->name = $name;
        $this->type = $type;
        $this->optin = $optin;
        $this->tags = $tags;
        $this->description = $description;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->name !== SdkNotGiven::Value) {
            $values["name"] = $this->name;
        }
        if ($this->type !== SdkNotGiven::Value) {
            $values["type"] = $this->type;
        }
        if ($this->optin !== SdkNotGiven::Value) {
            $values["optin"] = $this->optin;
        }
        if ($this->tags !== SdkNotGiven::Value) {
            $values["tags"] = $this->tags;
        }
        if ($this->description !== SdkNotGiven::Value) {
            $values["description"] = $this->description;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            name: (property_exists($data, "name") ? SdkClient::stringValue($data->name) : SdkNotGiven::Value),
            type: (property_exists($data, "type") ? SdkClient::hydrateStringEnumOrString($data->type, NewListTypeEnum::class) : SdkNotGiven::Value),
            optin: (property_exists($data, "optin") ? SdkClient::hydrateStringEnumOrString($data->optin, NewListOptinEnum::class) : SdkNotGiven::Value),
            tags: (property_exists($data, "tags") ? array_values(array_map(static fn ($item) => SdkClient::stringValue($item), SdkClient::arrayValue($data->tags))) : SdkNotGiven::Value),
            description: (property_exists($data, "description") ? SdkClient::stringValue($data->description) : SdkNotGiven::Value),
        );
    }
}
