<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

/**
 * Typed representation of the `MediaFileObject` API schema.
 */
class MediaFileObject implements \JsonSerializable
{
    /**
     * Optional `integer` value serialized in the `id` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $id;
    /**
     * Optional `string` value serialized in the `uuid` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $uuid;
    /**
     * Optional `string` value serialized in the `filename` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $filename;
    /**
     * Optional `string` value serialized in the `content_type` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $contentType;
    /**
     * Optional `string` value serialized in the `created_at` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $createdAt;
    /**
     * Optional `string` value serialized in the `thumb_url` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $thumbUrl;
    /**
     * Optional `string` value serialized in the `thumb_uri` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $thumbUri;
    /**
     * Optional `string` value serialized in the `provider` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $provider;
    /**
     * Optional object value serialized in the `meta` wire field.
     *
     * @var array<array-key,mixed>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $meta;
    /**
     * Optional `string` value serialized in the `url` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $url;
    /**
     * Optional `string` value serialized in the `uri` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $uri;

    /**
     * @param int|SdkNotGiven $id
     * @param string|SdkNotGiven $uuid
     * @param string|SdkNotGiven $filename
     * @param string|SdkNotGiven $contentType
     * @param string|SdkNotGiven $createdAt
     * @param string|SdkNotGiven $thumbUrl
     * @param string|SdkNotGiven $thumbUri
     * @param string|SdkNotGiven $provider
     * @param array<array-key,mixed>|SdkNotGiven $meta
     * @param string|SdkNotGiven $url
     * @param string|SdkNotGiven $uri
     */
    public function __construct(
        int|SdkNotGiven $id = SdkNotGiven::Value,
        string|SdkNotGiven $uuid = SdkNotGiven::Value,
        string|SdkNotGiven $filename = SdkNotGiven::Value,
        string|SdkNotGiven $contentType = SdkNotGiven::Value,
        string|SdkNotGiven $createdAt = SdkNotGiven::Value,
        string|SdkNotGiven $thumbUrl = SdkNotGiven::Value,
        string|SdkNotGiven $thumbUri = SdkNotGiven::Value,
        string|SdkNotGiven $provider = SdkNotGiven::Value,
        array|SdkNotGiven $meta = SdkNotGiven::Value,
        string|SdkNotGiven $url = SdkNotGiven::Value,
        string|SdkNotGiven $uri = SdkNotGiven::Value,
    ) {
        $this->id = $id;
        $this->uuid = $uuid;
        $this->filename = $filename;
        $this->contentType = $contentType;
        $this->createdAt = $createdAt;
        $this->thumbUrl = $thumbUrl;
        $this->thumbUri = $thumbUri;
        $this->provider = $provider;
        $this->meta = $meta;
        $this->url = $url;
        $this->uri = $uri;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->id !== SdkNotGiven::Value) {
            $values["id"] = $this->id;
        }
        if ($this->uuid !== SdkNotGiven::Value) {
            $values["uuid"] = $this->uuid;
        }
        if ($this->filename !== SdkNotGiven::Value) {
            $values["filename"] = $this->filename;
        }
        if ($this->contentType !== SdkNotGiven::Value) {
            $values["content_type"] = $this->contentType;
        }
        if ($this->createdAt !== SdkNotGiven::Value) {
            $values["created_at"] = $this->createdAt;
        }
        if ($this->thumbUrl !== SdkNotGiven::Value) {
            $values["thumb_url"] = $this->thumbUrl;
        }
        if ($this->thumbUri !== SdkNotGiven::Value) {
            $values["thumb_uri"] = $this->thumbUri;
        }
        if ($this->provider !== SdkNotGiven::Value) {
            $values["provider"] = $this->provider;
        }
        if ($this->meta !== SdkNotGiven::Value) {
            $values["meta"] = $this->meta;
        }
        if ($this->url !== SdkNotGiven::Value) {
            $values["url"] = $this->url;
        }
        if ($this->uri !== SdkNotGiven::Value) {
            $values["uri"] = $this->uri;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            id: (property_exists($data, "id") ? SdkClient::intValue($data->id) : SdkNotGiven::Value),
            uuid: (property_exists($data, "uuid") ? SdkClient::stringValue($data->uuid) : SdkNotGiven::Value),
            filename: (property_exists($data, "filename") ? SdkClient::stringValue($data->filename) : SdkNotGiven::Value),
            contentType: (property_exists($data, "content_type") ? SdkClient::stringValue($data->content_type) : SdkNotGiven::Value),
            createdAt: (property_exists($data, "created_at") ? SdkClient::stringValue($data->created_at) : SdkNotGiven::Value),
            thumbUrl: (property_exists($data, "thumb_url") ? SdkClient::stringValue($data->thumb_url) : SdkNotGiven::Value),
            thumbUri: (property_exists($data, "thumb_uri") ? SdkClient::stringValue($data->thumb_uri) : SdkNotGiven::Value),
            provider: (property_exists($data, "provider") ? SdkClient::stringValue($data->provider) : SdkNotGiven::Value),
            meta: (property_exists($data, "meta") ? SdkClient::stringMapValue($data->meta) : SdkNotGiven::Value),
            url: (property_exists($data, "url") ? SdkClient::stringValue($data->url) : SdkNotGiven::Value),
            uri: (property_exists($data, "uri") ? SdkClient::stringValue($data->uri) : SdkNotGiven::Value),
        );
    }
}
