<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

/**
 * Optional object value serialized in the `by_status` wire field.
 */
class DashboardCountDataCampaignsByStatus implements \JsonSerializable
{
    /**
     * Optional `integer` value serialized in the `draft` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $draft;

    /**
     * @param int|SdkNotGiven $draft
     */
    public function __construct(
        int|SdkNotGiven $draft = SdkNotGiven::Value,
    ) {
        $this->draft = $draft;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->draft !== SdkNotGiven::Value) {
            $values["draft"] = $this->draft;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            draft: (property_exists($data, "draft") ? SdkClient::intValue($data->draft) : SdkNotGiven::Value),
        );
    }
}

/**
 * Optional object value serialized in the `campaigns` wire field.
 */
class DashboardCountDataCampaigns implements \JsonSerializable
{
    /**
     * Optional `integer` value serialized in the `total` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $total;
    /**
     * Optional object value serialized in the `by_status` wire field.
     *
     * @var DashboardCountDataCampaignsByStatus|SdkNotGiven
     */
    public readonly DashboardCountDataCampaignsByStatus|SdkNotGiven $byStatus;

    /**
     * @param int|SdkNotGiven $total
     * @param DashboardCountDataCampaignsByStatus|SdkNotGiven $byStatus
     */
    public function __construct(
        int|SdkNotGiven $total = SdkNotGiven::Value,
        DashboardCountDataCampaignsByStatus|SdkNotGiven $byStatus = SdkNotGiven::Value,
    ) {
        $this->total = $total;
        $this->byStatus = $byStatus;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->total !== SdkNotGiven::Value) {
            $values["total"] = $this->total;
        }
        if ($this->byStatus !== SdkNotGiven::Value) {
            $values["by_status"] = $this->byStatus;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            total: (property_exists($data, "total") ? SdkClient::intValue($data->total) : SdkNotGiven::Value),
            byStatus: (property_exists($data, "by_status") ? SdkClient::hydrateClass($data->by_status, DashboardCountDataCampaignsByStatus::class) : SdkNotGiven::Value),
        );
    }
}

/**
 * Optional object value serialized in the `data` wire field.
 */
class DashboardCountData implements \JsonSerializable
{
    /**
     * Optional object value serialized in the `subscribers` wire field.
     *
     * @var DashboardCountDataSubscribers|SdkNotGiven
     */
    public readonly DashboardCountDataSubscribers|SdkNotGiven $subscribers;
    /**
     * Optional object value serialized in the `lists` wire field.
     *
     * @var DashboardCountDataLists|SdkNotGiven
     */
    public readonly DashboardCountDataLists|SdkNotGiven $lists;
    /**
     * Optional object value serialized in the `campaigns` wire field.
     *
     * @var DashboardCountDataCampaigns|SdkNotGiven
     */
    public readonly DashboardCountDataCampaigns|SdkNotGiven $campaigns;
    /**
     * Optional `integer` value serialized in the `messages` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $messages;

    /**
     * @param DashboardCountDataSubscribers|SdkNotGiven $subscribers
     * @param DashboardCountDataLists|SdkNotGiven $lists
     * @param DashboardCountDataCampaigns|SdkNotGiven $campaigns
     * @param int|SdkNotGiven $messages
     */
    public function __construct(
        DashboardCountDataSubscribers|SdkNotGiven $subscribers = SdkNotGiven::Value,
        DashboardCountDataLists|SdkNotGiven $lists = SdkNotGiven::Value,
        DashboardCountDataCampaigns|SdkNotGiven $campaigns = SdkNotGiven::Value,
        int|SdkNotGiven $messages = SdkNotGiven::Value,
    ) {
        $this->subscribers = $subscribers;
        $this->lists = $lists;
        $this->campaigns = $campaigns;
        $this->messages = $messages;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->subscribers !== SdkNotGiven::Value) {
            $values["subscribers"] = $this->subscribers;
        }
        if ($this->lists !== SdkNotGiven::Value) {
            $values["lists"] = $this->lists;
        }
        if ($this->campaigns !== SdkNotGiven::Value) {
            $values["campaigns"] = $this->campaigns;
        }
        if ($this->messages !== SdkNotGiven::Value) {
            $values["messages"] = $this->messages;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            subscribers: (property_exists($data, "subscribers") ? SdkClient::hydrateClass($data->subscribers, DashboardCountDataSubscribers::class) : SdkNotGiven::Value),
            lists: (property_exists($data, "lists") ? SdkClient::hydrateClass($data->lists, DashboardCountDataLists::class) : SdkNotGiven::Value),
            campaigns: (property_exists($data, "campaigns") ? SdkClient::hydrateClass($data->campaigns, DashboardCountDataCampaigns::class) : SdkNotGiven::Value),
            messages: (property_exists($data, "messages") ? SdkClient::intValue($data->messages) : SdkNotGiven::Value),
        );
    }
}

/**
 * Typed representation of the `DashboardCount` API schema.
 */
class DashboardCount implements \JsonSerializable
{
    /**
     * Optional object value serialized in the `data` wire field.
     *
     * @var DashboardCountData|SdkNotGiven
     */
    public readonly DashboardCountData|SdkNotGiven $data;

    /**
     * @param DashboardCountData|SdkNotGiven $data
     */
    public function __construct(
        DashboardCountData|SdkNotGiven $data = SdkNotGiven::Value,
    ) {
        $this->data = $data;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            data: (property_exists($data, "data") ? SdkClient::hydrateClass($data->data, DashboardCountData::class) : SdkNotGiven::Value),
        );
    }
}
