<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

/**
 * Typed representation of the `SMTPTest` API schema.
 */
class SMTPTest implements \JsonSerializable
{
    /**
     * Optional `string` value serialized in the `uuid` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $uuid;
    /**
     * Optional `boolean` value serialized in the `enabled` wire field.
     *
     * @var bool|SdkNotGiven
     */
    public readonly bool|SdkNotGiven $enabled;
    /**
     * Optional `string` value serialized in the `host` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $host;
    /**
     * Optional `string` value serialized in the `hello_hostname` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $helloHostname;
    /**
     * Optional `integer` value serialized in the `port` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $port;
    /**
     * Optional `string` value serialized in the `auth_protocol` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $authProtocol;
    /**
     * Optional `string` value serialized in the `username` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $username;
    /**
     * Optional array value serialized in the `email_headers` wire field.
     *
     * @var list<array<array-key,mixed>>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $emailHeaders;
    /**
     * Optional `integer` value serialized in the `max_conns` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $maxConns;
    /**
     * Optional `integer` value serialized in the `max_msg_retries` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $maxMsgRetries;
    /**
     * Optional `string` value serialized in the `idle_timeout` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $idleTimeout;
    /**
     * Optional `string` value serialized in the `wait_timeout` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $waitTimeout;
    /**
     * Optional `string` value serialized in the `tls_type` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $tlsType;
    /**
     * Optional `boolean` value serialized in the `tls_skip_verify` wire field.
     *
     * @var bool|SdkNotGiven
     */
    public readonly bool|SdkNotGiven $tlsSkipVerify;
    /**
     * Optional `string` value serialized in the `strEmailHeaders` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $strEmailHeaders;
    /**
     * Optional `string` value serialized in the `password` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $password;
    /**
     * Optional `string` value serialized in the `email` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $email;

    /**
     * @param string|SdkNotGiven $uuid
     * @param bool|SdkNotGiven $enabled
     * @param string|SdkNotGiven $host
     * @param string|SdkNotGiven $helloHostname
     * @param int|SdkNotGiven $port
     * @param string|SdkNotGiven $authProtocol
     * @param string|SdkNotGiven $username
     * @param list<array<array-key,mixed>>|SdkNotGiven $emailHeaders
     * @param int|SdkNotGiven $maxConns
     * @param int|SdkNotGiven $maxMsgRetries
     * @param string|SdkNotGiven $idleTimeout
     * @param string|SdkNotGiven $waitTimeout
     * @param string|SdkNotGiven $tlsType
     * @param bool|SdkNotGiven $tlsSkipVerify
     * @param string|SdkNotGiven $strEmailHeaders
     * @param string|SdkNotGiven $password
     * @param string|SdkNotGiven $email
     */
    public function __construct(
        string|SdkNotGiven $uuid = SdkNotGiven::Value,
        bool|SdkNotGiven $enabled = SdkNotGiven::Value,
        string|SdkNotGiven $host = SdkNotGiven::Value,
        string|SdkNotGiven $helloHostname = SdkNotGiven::Value,
        int|SdkNotGiven $port = SdkNotGiven::Value,
        string|SdkNotGiven $authProtocol = SdkNotGiven::Value,
        string|SdkNotGiven $username = SdkNotGiven::Value,
        array|SdkNotGiven $emailHeaders = SdkNotGiven::Value,
        int|SdkNotGiven $maxConns = SdkNotGiven::Value,
        int|SdkNotGiven $maxMsgRetries = SdkNotGiven::Value,
        string|SdkNotGiven $idleTimeout = SdkNotGiven::Value,
        string|SdkNotGiven $waitTimeout = SdkNotGiven::Value,
        string|SdkNotGiven $tlsType = SdkNotGiven::Value,
        bool|SdkNotGiven $tlsSkipVerify = SdkNotGiven::Value,
        string|SdkNotGiven $strEmailHeaders = SdkNotGiven::Value,
        string|SdkNotGiven $password = SdkNotGiven::Value,
        string|SdkNotGiven $email = SdkNotGiven::Value,
    ) {
        $this->uuid = $uuid;
        $this->enabled = $enabled;
        $this->host = $host;
        $this->helloHostname = $helloHostname;
        $this->port = $port;
        $this->authProtocol = $authProtocol;
        $this->username = $username;
        $this->emailHeaders = $emailHeaders;
        $this->maxConns = $maxConns;
        $this->maxMsgRetries = $maxMsgRetries;
        $this->idleTimeout = $idleTimeout;
        $this->waitTimeout = $waitTimeout;
        $this->tlsType = $tlsType;
        $this->tlsSkipVerify = $tlsSkipVerify;
        $this->strEmailHeaders = $strEmailHeaders;
        $this->password = $password;
        $this->email = $email;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->uuid !== SdkNotGiven::Value) {
            $values["uuid"] = $this->uuid;
        }
        if ($this->enabled !== SdkNotGiven::Value) {
            $values["enabled"] = $this->enabled;
        }
        if ($this->host !== SdkNotGiven::Value) {
            $values["host"] = $this->host;
        }
        if ($this->helloHostname !== SdkNotGiven::Value) {
            $values["hello_hostname"] = $this->helloHostname;
        }
        if ($this->port !== SdkNotGiven::Value) {
            $values["port"] = $this->port;
        }
        if ($this->authProtocol !== SdkNotGiven::Value) {
            $values["auth_protocol"] = $this->authProtocol;
        }
        if ($this->username !== SdkNotGiven::Value) {
            $values["username"] = $this->username;
        }
        if ($this->emailHeaders !== SdkNotGiven::Value) {
            $values["email_headers"] = $this->emailHeaders;
        }
        if ($this->maxConns !== SdkNotGiven::Value) {
            $values["max_conns"] = $this->maxConns;
        }
        if ($this->maxMsgRetries !== SdkNotGiven::Value) {
            $values["max_msg_retries"] = $this->maxMsgRetries;
        }
        if ($this->idleTimeout !== SdkNotGiven::Value) {
            $values["idle_timeout"] = $this->idleTimeout;
        }
        if ($this->waitTimeout !== SdkNotGiven::Value) {
            $values["wait_timeout"] = $this->waitTimeout;
        }
        if ($this->tlsType !== SdkNotGiven::Value) {
            $values["tls_type"] = $this->tlsType;
        }
        if ($this->tlsSkipVerify !== SdkNotGiven::Value) {
            $values["tls_skip_verify"] = $this->tlsSkipVerify;
        }
        if ($this->strEmailHeaders !== SdkNotGiven::Value) {
            $values["strEmailHeaders"] = $this->strEmailHeaders;
        }
        if ($this->password !== SdkNotGiven::Value) {
            $values["password"] = $this->password;
        }
        if ($this->email !== SdkNotGiven::Value) {
            $values["email"] = $this->email;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            uuid: (property_exists($data, "uuid") ? SdkClient::stringValue($data->uuid) : SdkNotGiven::Value),
            enabled: (property_exists($data, "enabled") ? SdkClient::boolValue($data->enabled) : SdkNotGiven::Value),
            host: (property_exists($data, "host") ? SdkClient::stringValue($data->host) : SdkNotGiven::Value),
            helloHostname: (property_exists($data, "hello_hostname") ? SdkClient::stringValue($data->hello_hostname) : SdkNotGiven::Value),
            port: (property_exists($data, "port") ? SdkClient::intValue($data->port) : SdkNotGiven::Value),
            authProtocol: (property_exists($data, "auth_protocol") ? SdkClient::stringValue($data->auth_protocol) : SdkNotGiven::Value),
            username: (property_exists($data, "username") ? SdkClient::stringValue($data->username) : SdkNotGiven::Value),
            emailHeaders: (property_exists($data, "email_headers") ? array_values(array_map(static fn($item) => SdkClient::stringMapValue($item), SdkClient::arrayValue($data->email_headers))) : SdkNotGiven::Value),
            maxConns: (property_exists($data, "max_conns") ? SdkClient::intValue($data->max_conns) : SdkNotGiven::Value),
            maxMsgRetries: (property_exists($data, "max_msg_retries") ? SdkClient::intValue($data->max_msg_retries) : SdkNotGiven::Value),
            idleTimeout: (property_exists($data, "idle_timeout") ? SdkClient::stringValue($data->idle_timeout) : SdkNotGiven::Value),
            waitTimeout: (property_exists($data, "wait_timeout") ? SdkClient::stringValue($data->wait_timeout) : SdkNotGiven::Value),
            tlsType: (property_exists($data, "tls_type") ? SdkClient::stringValue($data->tls_type) : SdkNotGiven::Value),
            tlsSkipVerify: (property_exists($data, "tls_skip_verify") ? SdkClient::boolValue($data->tls_skip_verify) : SdkNotGiven::Value),
            strEmailHeaders: (property_exists($data, "strEmailHeaders") ? SdkClient::stringValue($data->strEmailHeaders) : SdkNotGiven::Value),
            password: (property_exists($data, "password") ? SdkClient::stringValue($data->password) : SdkNotGiven::Value),
            email: (property_exists($data, "email") ? SdkClient::stringValue($data->email) : SdkNotGiven::Value),
        );
    }
}
