<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

/**
 * Optional object value serialized in the `campaign` wire field.
 */
class BounceResultsItemCampaign implements \JsonSerializable
{
    /**
     * Optional `integer` value serialized in the `id` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $id;
    /**
     * Optional `string` value serialized in the `name` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $name;

    /**
     * @param int|SdkNotGiven $id
     * @param string|SdkNotGiven $name
     */
    public function __construct(
        int|SdkNotGiven $id = SdkNotGiven::Value,
        string|SdkNotGiven $name = SdkNotGiven::Value,
    ) {
        $this->id = $id;
        $this->name = $name;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->id !== SdkNotGiven::Value) {
            $values["id"] = $this->id;
        }
        if ($this->name !== SdkNotGiven::Value) {
            $values["name"] = $this->name;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            id: (property_exists($data, "id") ? SdkClient::intValue($data->id) : SdkNotGiven::Value),
            name: (property_exists($data, "name") ? SdkClient::stringValue($data->name) : SdkNotGiven::Value),
        );
    }
}

/**
 * Required object value serialized in the `results[]` wire field.
 */
class BounceResultsItem implements \JsonSerializable
{
    /**
     * Optional `integer` value serialized in the `id` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $id;
    /**
     * Optional `string` value serialized in the `type` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $type;
    /**
     * Optional `string` value serialized in the `source` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $source;
    /**
     * Optional object value serialized in the `meta` wire field.
     *
     * @var array<array-key,mixed>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $meta;
    /**
     * Optional `string` value serialized in the `created_at` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $createdAt;
    /**
     * Optional `string` value serialized in the `email` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $email;
    /**
     * Optional `string` value serialized in the `subscriber_uuid` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $subscriberUuid;
    /**
     * Optional `integer` value serialized in the `subscriber_id` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $subscriberId;
    /**
     * Optional object value serialized in the `campaign` wire field.
     *
     * @var BounceResultsItemCampaign|SdkNotGiven
     */
    public readonly BounceResultsItemCampaign|SdkNotGiven $campaign;
    /**
     * Optional `string` value serialized in the `campaign_uuid` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $campaignUuid;
    /**
     * Optional `integer` value serialized in the `total` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $total;

    /**
     * @param int|SdkNotGiven $id
     * @param string|SdkNotGiven $type
     * @param string|SdkNotGiven $source
     * @param array<array-key,mixed>|SdkNotGiven $meta
     * @param string|SdkNotGiven $createdAt
     * @param string|SdkNotGiven $email
     * @param string|SdkNotGiven $subscriberUuid
     * @param int|SdkNotGiven $subscriberId
     * @param BounceResultsItemCampaign|SdkNotGiven $campaign
     * @param string|SdkNotGiven $campaignUuid
     * @param int|SdkNotGiven $total
     */
    public function __construct(
        int|SdkNotGiven $id = SdkNotGiven::Value,
        string|SdkNotGiven $type = SdkNotGiven::Value,
        string|SdkNotGiven $source = SdkNotGiven::Value,
        array|SdkNotGiven $meta = SdkNotGiven::Value,
        string|SdkNotGiven $createdAt = SdkNotGiven::Value,
        string|SdkNotGiven $email = SdkNotGiven::Value,
        string|SdkNotGiven $subscriberUuid = SdkNotGiven::Value,
        int|SdkNotGiven $subscriberId = SdkNotGiven::Value,
        BounceResultsItemCampaign|SdkNotGiven $campaign = SdkNotGiven::Value,
        string|SdkNotGiven $campaignUuid = SdkNotGiven::Value,
        int|SdkNotGiven $total = SdkNotGiven::Value,
    ) {
        $this->id = $id;
        $this->type = $type;
        $this->source = $source;
        $this->meta = $meta;
        $this->createdAt = $createdAt;
        $this->email = $email;
        $this->subscriberUuid = $subscriberUuid;
        $this->subscriberId = $subscriberId;
        $this->campaign = $campaign;
        $this->campaignUuid = $campaignUuid;
        $this->total = $total;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->id !== SdkNotGiven::Value) {
            $values["id"] = $this->id;
        }
        if ($this->type !== SdkNotGiven::Value) {
            $values["type"] = $this->type;
        }
        if ($this->source !== SdkNotGiven::Value) {
            $values["source"] = $this->source;
        }
        if ($this->meta !== SdkNotGiven::Value) {
            $values["meta"] = $this->meta;
        }
        if ($this->createdAt !== SdkNotGiven::Value) {
            $values["created_at"] = $this->createdAt;
        }
        if ($this->email !== SdkNotGiven::Value) {
            $values["email"] = $this->email;
        }
        if ($this->subscriberUuid !== SdkNotGiven::Value) {
            $values["subscriber_uuid"] = $this->subscriberUuid;
        }
        if ($this->subscriberId !== SdkNotGiven::Value) {
            $values["subscriber_id"] = $this->subscriberId;
        }
        if ($this->campaign !== SdkNotGiven::Value) {
            $values["campaign"] = $this->campaign;
        }
        if ($this->campaignUuid !== SdkNotGiven::Value) {
            $values["campaign_uuid"] = $this->campaignUuid;
        }
        if ($this->total !== SdkNotGiven::Value) {
            $values["total"] = $this->total;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            id: (property_exists($data, "id") ? SdkClient::intValue($data->id) : SdkNotGiven::Value),
            type: (property_exists($data, "type") ? SdkClient::stringValue($data->type) : SdkNotGiven::Value),
            source: (property_exists($data, "source") ? SdkClient::stringValue($data->source) : SdkNotGiven::Value),
            meta: (property_exists($data, "meta") ? SdkClient::stringMapValue($data->meta) : SdkNotGiven::Value),
            createdAt: (property_exists($data, "created_at") ? SdkClient::stringValue($data->created_at) : SdkNotGiven::Value),
            email: (property_exists($data, "email") ? SdkClient::stringValue($data->email) : SdkNotGiven::Value),
            subscriberUuid: (property_exists($data, "subscriber_uuid") ? SdkClient::stringValue($data->subscriber_uuid) : SdkNotGiven::Value),
            subscriberId: (property_exists($data, "subscriber_id") ? SdkClient::intValue($data->subscriber_id) : SdkNotGiven::Value),
            campaign: (property_exists($data, "campaign") ? SdkClient::hydrateClass($data->campaign, BounceResultsItemCampaign::class) : SdkNotGiven::Value),
            campaignUuid: (property_exists($data, "campaign_uuid") ? SdkClient::stringValue($data->campaign_uuid) : SdkNotGiven::Value),
            total: (property_exists($data, "total") ? SdkClient::intValue($data->total) : SdkNotGiven::Value),
        );
    }
}

/**
 * Typed representation of the `Bounce` API schema.
 */
class Bounce implements \JsonSerializable
{
    /**
     * Optional array value serialized in the `results` wire field.
     *
     * @var list<BounceResultsItem>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $results;

    /**
     * @param list<BounceResultsItem>|SdkNotGiven $results
     */
    public function __construct(
        array|SdkNotGiven $results = SdkNotGiven::Value,
    ) {
        $this->results = $results;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->results !== SdkNotGiven::Value) {
            $values["results"] = $this->results;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            results: (property_exists($data, "results") ? array_values(array_map(static fn($item) => SdkClient::hydrateClass($item, BounceResultsItem::class), SdkClient::arrayValue($data->results))) : SdkNotGiven::Value),
        );
    }
}
