<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

/**
 * Typed representation of the `Subscriptions` API schema.
 */
class Subscriptions implements \JsonSerializable
{
    /**
     * Optional `string` value serialized in the `subscription_status` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $subscriptionStatus;
    /**
     * Optional `string` value serialized in the `name` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $name;
    /**
     * Optional `string` value serialized in the `type` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $type;
    /**
     * Optional `string` value serialized in the `created_at` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $createdAt;

    /**
     * @param string|SdkNotGiven $subscriptionStatus
     * @param string|SdkNotGiven $name
     * @param string|SdkNotGiven $type
     * @param string|SdkNotGiven $createdAt
     */
    public function __construct(
        string|SdkNotGiven $subscriptionStatus = SdkNotGiven::Value,
        string|SdkNotGiven $name = SdkNotGiven::Value,
        string|SdkNotGiven $type = SdkNotGiven::Value,
        string|SdkNotGiven $createdAt = SdkNotGiven::Value,
    ) {
        $this->subscriptionStatus = $subscriptionStatus;
        $this->name = $name;
        $this->type = $type;
        $this->createdAt = $createdAt;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->subscriptionStatus !== SdkNotGiven::Value) {
            $values["subscription_status"] = $this->subscriptionStatus;
        }
        if ($this->name !== SdkNotGiven::Value) {
            $values["name"] = $this->name;
        }
        if ($this->type !== SdkNotGiven::Value) {
            $values["type"] = $this->type;
        }
        if ($this->createdAt !== SdkNotGiven::Value) {
            $values["created_at"] = $this->createdAt;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            subscriptionStatus: (property_exists($data, "subscription_status") ? SdkClient::stringValue($data->subscription_status) : SdkNotGiven::Value),
            name: (property_exists($data, "name") ? SdkClient::stringValue($data->name) : SdkNotGiven::Value),
            type: (property_exists($data, "type") ? SdkClient::stringValue($data->type) : SdkNotGiven::Value),
            createdAt: (property_exists($data, "created_at") ? SdkClient::stringValue($data->created_at) : SdkNotGiven::Value),
        );
    }
}

/**
 * Typed representation of the `UpdateSubscriber` API schema.
 */
class UpdateSubscriber implements \JsonSerializable
{
    /**
     * Optional `string` value serialized in the `email` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $email;
    /**
     * Optional `string` value serialized in the `name` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $name;
    /**
     * Optional `string` value serialized in the `status` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $status;
    /**
     * Optional array value serialized in the `lists` wire field.
     *
     * @var list<int>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $lists;
    /**
     * Optional array value serialized in the `list_uuids` wire field.
     *
     * @var list<string>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $listUuids;
    /**
     * Optional `boolean` value serialized in the `preconfirm_subscriptions` wire field.
     *
     * @var bool|SdkNotGiven
     */
    public readonly bool|SdkNotGiven $preconfirmSubscriptions;
    /**
     * Optional object value serialized in the `attribs` wire field.
     *
     * @var array<string,mixed>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $attribs;

    /**
     * @param string|SdkNotGiven $email
     * @param string|SdkNotGiven $name
     * @param string|SdkNotGiven $status
     * @param list<int>|SdkNotGiven $lists
     * @param list<string>|SdkNotGiven $listUuids
     * @param bool|SdkNotGiven $preconfirmSubscriptions
     * @param array<string,mixed>|SdkNotGiven $attribs
     */
    public function __construct(
        string|SdkNotGiven $email = SdkNotGiven::Value,
        string|SdkNotGiven $name = SdkNotGiven::Value,
        string|SdkNotGiven $status = SdkNotGiven::Value,
        array|SdkNotGiven $lists = SdkNotGiven::Value,
        array|SdkNotGiven $listUuids = SdkNotGiven::Value,
        bool|SdkNotGiven $preconfirmSubscriptions = SdkNotGiven::Value,
        array|SdkNotGiven $attribs = SdkNotGiven::Value,
    ) {
        $this->email = $email;
        $this->name = $name;
        $this->status = $status;
        $this->lists = $lists;
        $this->listUuids = $listUuids;
        $this->preconfirmSubscriptions = $preconfirmSubscriptions;
        $this->attribs = $attribs;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->email !== SdkNotGiven::Value) {
            $values["email"] = $this->email;
        }
        if ($this->name !== SdkNotGiven::Value) {
            $values["name"] = $this->name;
        }
        if ($this->status !== SdkNotGiven::Value) {
            $values["status"] = $this->status;
        }
        if ($this->lists !== SdkNotGiven::Value) {
            $values["lists"] = $this->lists;
        }
        if ($this->listUuids !== SdkNotGiven::Value) {
            $values["list_uuids"] = $this->listUuids;
        }
        if ($this->preconfirmSubscriptions !== SdkNotGiven::Value) {
            $values["preconfirm_subscriptions"] = $this->preconfirmSubscriptions;
        }
        if ($this->attribs !== SdkNotGiven::Value) {
            $values["attribs"] = $this->attribs;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            email: (property_exists($data, "email") ? SdkClient::stringValue($data->email) : SdkNotGiven::Value),
            name: (property_exists($data, "name") ? SdkClient::stringValue($data->name) : SdkNotGiven::Value),
            status: (property_exists($data, "status") ? SdkClient::stringValue($data->status) : SdkNotGiven::Value),
            lists: (property_exists($data, "lists") ? array_values(array_map(static fn($item) => SdkClient::intValue($item), SdkClient::arrayValue($data->lists))) : SdkNotGiven::Value),
            listUuids: (property_exists($data, "list_uuids") ? array_values(array_map(static fn($item) => SdkClient::stringValue($item), SdkClient::arrayValue($data->list_uuids))) : SdkNotGiven::Value),
            preconfirmSubscriptions: (property_exists($data, "preconfirm_subscriptions") ? SdkClient::boolValue($data->preconfirm_subscriptions) : SdkNotGiven::Value),
            attribs: (property_exists($data, "attribs") ? SdkClient::stringMapValue($data->attribs) : SdkNotGiven::Value),
        );
    }
}
