<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

/**
 * Type of the template
 */
final readonly class NewTemplateTypeEnum implements SdkOpenEnum
{
    public const CAMPAIGN = "campaign";
    public const CAMPAIGN_VISUAL = "campaign_visual";
    public const TX = "tx";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static { return new self((string) $value); }
    public static function tryFrom(string|int|null $value): ?static { return $value === null ? null : self::from($value); }
    public function getValue(): string { return $this->value; }
    public function jsonSerialize(): string { return $this->value; }
    public function __toString(): string { return (string) $this->value; }
}

/**
 * Typed representation of the `NewTemplate` API schema.
 */
class NewTemplate implements \JsonSerializable
{
    /**
     * Name of the template
     *
     * @var string
     */
    public readonly string $name;
    /**
     * Type of the template
     *
     * @var NewTemplateTypeEnum|string
     */
    public readonly NewTemplateTypeEnum|string $type;
    /**
     * Subject line for the template (only for tx)
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $subject;
    /**
     * JSON source for the email-builder template (only for campaign_visual)
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $bodySource;
    /**
     * HTML body of the template
     *
     * @var string
     */
    public readonly string $body;

    /**
     * @param string $name
     * @param NewTemplateTypeEnum|string $type
     * @param string $body
     * @param string|SdkNotGiven $subject
     * @param string|SdkNotGiven $bodySource
     */
    public function __construct(
        string $name,
        NewTemplateTypeEnum|string $type,
        string $body,
        string|SdkNotGiven $subject = SdkNotGiven::Value,
        string|SdkNotGiven $bodySource = SdkNotGiven::Value,
    ) {
        $this->name = $name;
        $this->type = $type;
        $this->body = $body;
        $this->subject = $subject;
        $this->bodySource = $bodySource;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
            "name" => $this->name,
            "type" => $this->type,
            "body" => $this->body,
        ];
        if ($this->subject !== SdkNotGiven::Value) {
            $values["subject"] = $this->subject;
        }
        if ($this->bodySource !== SdkNotGiven::Value) {
            $values["body_source"] = $this->bodySource;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        if (!property_exists($data, "name")) { throw new SdkValidationError("name", 'required', "Missing required property 'name'"); }
        if (!property_exists($data, "type")) { throw new SdkValidationError("type", 'required', "Missing required property 'type'"); }
        if (!property_exists($data, "body")) { throw new SdkValidationError("body", 'required', "Missing required property 'body'"); }
        return new self(
            name: SdkClient::stringValue($data->name),
            type: SdkClient::hydrateStringEnumOrString($data->type, NewTemplateTypeEnum::class),
            body: SdkClient::stringValue($data->body),
            subject: (property_exists($data, "subject") ? SdkClient::stringValue($data->subject) : SdkNotGiven::Value),
            bodySource: (property_exists($data, "body_source") ? SdkClient::stringValue($data->body_source) : SdkNotGiven::Value),
        );
    }
}

/**
 * Typed representation of the `Template` API schema.
 */
class Template implements \JsonSerializable
{
    /**
     * Optional `integer` value serialized in the `id` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $id;
    /**
     * Optional `string` value serialized in the `created_at` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $createdAt;
    /**
     * Optional `string` value serialized in the `updated_at` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $updatedAt;
    /**
     * Optional `string` value serialized in the `name` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $name;
    /**
     * Optional `string` value serialized in the `body` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $body;
    /**
     * Optional `string` value serialized in the `body_source` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $bodySource;
    /**
     * Optional `string` value serialized in the `subject` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $subject;
    /**
     * Optional `string` value serialized in the `type` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $type;
    /**
     * Optional `boolean` value serialized in the `is_default` wire field.
     *
     * @var bool|SdkNotGiven
     */
    public readonly bool|SdkNotGiven $isDefault;

    /**
     * @param int|SdkNotGiven $id
     * @param string|SdkNotGiven $createdAt
     * @param string|SdkNotGiven $updatedAt
     * @param string|SdkNotGiven $name
     * @param string|SdkNotGiven $body
     * @param string|SdkNotGiven $bodySource
     * @param string|SdkNotGiven $subject
     * @param string|SdkNotGiven $type
     * @param bool|SdkNotGiven $isDefault
     */
    public function __construct(
        int|SdkNotGiven $id = SdkNotGiven::Value,
        string|SdkNotGiven $createdAt = SdkNotGiven::Value,
        string|SdkNotGiven $updatedAt = SdkNotGiven::Value,
        string|SdkNotGiven $name = SdkNotGiven::Value,
        string|SdkNotGiven $body = SdkNotGiven::Value,
        string|SdkNotGiven $bodySource = SdkNotGiven::Value,
        string|SdkNotGiven $subject = SdkNotGiven::Value,
        string|SdkNotGiven $type = SdkNotGiven::Value,
        bool|SdkNotGiven $isDefault = SdkNotGiven::Value,
    ) {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->name = $name;
        $this->body = $body;
        $this->bodySource = $bodySource;
        $this->subject = $subject;
        $this->type = $type;
        $this->isDefault = $isDefault;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->id !== SdkNotGiven::Value) {
            $values["id"] = $this->id;
        }
        if ($this->createdAt !== SdkNotGiven::Value) {
            $values["created_at"] = $this->createdAt;
        }
        if ($this->updatedAt !== SdkNotGiven::Value) {
            $values["updated_at"] = $this->updatedAt;
        }
        if ($this->name !== SdkNotGiven::Value) {
            $values["name"] = $this->name;
        }
        if ($this->body !== SdkNotGiven::Value) {
            $values["body"] = $this->body;
        }
        if ($this->bodySource !== SdkNotGiven::Value) {
            $values["body_source"] = $this->bodySource;
        }
        if ($this->subject !== SdkNotGiven::Value) {
            $values["subject"] = $this->subject;
        }
        if ($this->type !== SdkNotGiven::Value) {
            $values["type"] = $this->type;
        }
        if ($this->isDefault !== SdkNotGiven::Value) {
            $values["is_default"] = $this->isDefault;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            id: (property_exists($data, "id") ? SdkClient::intValue($data->id) : SdkNotGiven::Value),
            createdAt: (property_exists($data, "created_at") ? SdkClient::stringValue($data->created_at) : SdkNotGiven::Value),
            updatedAt: (property_exists($data, "updated_at") ? SdkClient::stringValue($data->updated_at) : SdkNotGiven::Value),
            name: (property_exists($data, "name") ? SdkClient::stringValue($data->name) : SdkNotGiven::Value),
            body: (property_exists($data, "body") ? SdkClient::stringValue($data->body) : SdkNotGiven::Value),
            bodySource: (property_exists($data, "body_source") ? SdkClient::stringValue($data->body_source) : SdkNotGiven::Value),
            subject: (property_exists($data, "subject") ? SdkClient::stringValue($data->subject) : SdkNotGiven::Value),
            type: (property_exists($data, "type") ? SdkClient::stringValue($data->type) : SdkNotGiven::Value),
            isDefault: (property_exists($data, "is_default") ? SdkClient::boolValue($data->is_default) : SdkNotGiven::Value),
        );
    }
}

/**
 * Type of the template
 */
final readonly class UpdateTemplateTypeEnum implements SdkOpenEnum
{
    public const CAMPAIGN = "campaign";
    public const CAMPAIGN_VISUAL = "campaign_visual";
    public const TX = "tx";
    private function __construct(public string $value) {}
    public static function from(string|int $value): static { return new self((string) $value); }
    public static function tryFrom(string|int|null $value): ?static { return $value === null ? null : self::from($value); }
    public function getValue(): string { return $this->value; }
    public function jsonSerialize(): string { return $this->value; }
    public function __toString(): string { return (string) $this->value; }
}
