<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

/**
 * Typed representation of the `TransactionalMessage` API schema.
 */
class TransactionalMessage implements \JsonSerializable
{
    /**
     * Optional `string` value serialized in the `subscriber_email` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $subscriberEmail;
    /**
     * Optional `integer` value serialized in the `subscriber_id` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $subscriberId;
    /**
     * Optional `integer` value serialized in the `template_id` wire field.
     *
     * @var int|SdkNotGiven
     */
    public readonly int|SdkNotGiven $templateId;
    /**
     * Optional `string` value serialized in the `from_email` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $fromEmail;
    /**
     * Optional object value serialized in the `data` wire field.
     *
     * @var array<array-key,mixed>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $data;
    /**
     * Optional array value serialized in the `headers` wire field.
     *
     * @var list<array<array-key,mixed>>|SdkNotGiven
     */
    public readonly array|SdkNotGiven $headers;
    /**
     * Optional `string` value serialized in the `messenger` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $messenger;
    /**
     * Optional `string` value serialized in the `content_type` wire field.
     *
     * @var string|SdkNotGiven
     */
    public readonly string|SdkNotGiven $contentType;

    /**
     * @param string|SdkNotGiven $subscriberEmail
     * @param int|SdkNotGiven $subscriberId
     * @param int|SdkNotGiven $templateId
     * @param string|SdkNotGiven $fromEmail
     * @param array<array-key,mixed>|SdkNotGiven $data
     * @param list<array<array-key,mixed>>|SdkNotGiven $headers
     * @param string|SdkNotGiven $messenger
     * @param string|SdkNotGiven $contentType
     */
    public function __construct(
        string|SdkNotGiven $subscriberEmail = SdkNotGiven::Value,
        int|SdkNotGiven $subscriberId = SdkNotGiven::Value,
        int|SdkNotGiven $templateId = SdkNotGiven::Value,
        string|SdkNotGiven $fromEmail = SdkNotGiven::Value,
        array|SdkNotGiven $data = SdkNotGiven::Value,
        array|SdkNotGiven $headers = SdkNotGiven::Value,
        string|SdkNotGiven $messenger = SdkNotGiven::Value,
        string|SdkNotGiven $contentType = SdkNotGiven::Value,
    ) {
        $this->subscriberEmail = $subscriberEmail;
        $this->subscriberId = $subscriberId;
        $this->templateId = $templateId;
        $this->fromEmail = $fromEmail;
        $this->data = $data;
        $this->headers = $headers;
        $this->messenger = $messenger;
        $this->contentType = $contentType;
    }

    /** @return array<array-key, mixed> */
    public function toArray(): array
    {
        $values = [
        ];
        if ($this->subscriberEmail !== SdkNotGiven::Value) {
            $values["subscriber_email"] = $this->subscriberEmail;
        }
        if ($this->subscriberId !== SdkNotGiven::Value) {
            $values["subscriber_id"] = $this->subscriberId;
        }
        if ($this->templateId !== SdkNotGiven::Value) {
            $values["template_id"] = $this->templateId;
        }
        if ($this->fromEmail !== SdkNotGiven::Value) {
            $values["from_email"] = $this->fromEmail;
        }
        if ($this->data !== SdkNotGiven::Value) {
            $values["data"] = $this->data;
        }
        if ($this->headers !== SdkNotGiven::Value) {
            $values["headers"] = $this->headers;
        }
        if ($this->messenger !== SdkNotGiven::Value) {
            $values["messenger"] = $this->messenger;
        }
        if ($this->contentType !== SdkNotGiven::Value) {
            $values["content_type"] = $this->contentType;
        }
        return $values;
    }

    /** @return object */
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public static function fromObject(object $data): self
    {
        return new self(
            subscriberEmail: (property_exists($data, "subscriber_email") ? SdkClient::stringValue($data->subscriber_email) : SdkNotGiven::Value),
            subscriberId: (property_exists($data, "subscriber_id") ? SdkClient::intValue($data->subscriber_id) : SdkNotGiven::Value),
            templateId: (property_exists($data, "template_id") ? SdkClient::intValue($data->template_id) : SdkNotGiven::Value),
            fromEmail: (property_exists($data, "from_email") ? SdkClient::stringValue($data->from_email) : SdkNotGiven::Value),
            data: (property_exists($data, "data") ? SdkClient::stringMapValue($data->data) : SdkNotGiven::Value),
            headers: (property_exists($data, "headers") ? array_values(array_map(static fn ($item) => SdkClient::stringMapValue($item), SdkClient::arrayValue($data->headers))) : SdkNotGiven::Value),
            messenger: (property_exists($data, "messenger") ? SdkClient::stringValue($data->messenger) : SdkNotGiven::Value),
            contentType: (property_exists($data, "content_type") ? SdkClient::stringValue($data->content_type) : SdkNotGiven::Value),
        );
    }
}
