<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

/**
 * Single execution path for every generated method. Returns a typed
 * SdkResponse on 2xx; throws SdkHttpError, SdkNetworkError, or
 * SdkTimeoutError otherwise.
 */

require_once __DIR__ . '/Client/SdkClientMethodsPart1.php';
require_once __DIR__ . '/Client/SdkClientMethodsPart2.php';
require_once __DIR__ . '/Client/SdkClientMethodsPart3.php';
require_once __DIR__ . '/Client/SdkClientMethodsPart4.php';
require_once __DIR__ . '/Client/SdkClientMethodsPart5.php';

class SdkClient
{
    use SdkClientMethodsPart1;
    use SdkClientMethodsPart2;
    use SdkClientMethodsPart3;
    use SdkClientMethodsPart4;
    use SdkClientMethodsPart5;

    /** HTTP transport this package was generated for: ext-curl with a PHP stream fallback. */
    public const TRANSPORT_ENGINE = 'curl';

    private const IDEMPOTENT_METHODS = ['GET', 'HEAD', 'PUT', 'DELETE', 'OPTIONS'];
    private const ALWAYS_RETRYABLE = [429, 503];
    private const REQUEST_ID_HEADERS = ['x-request-id', 'openai-request-id', 'x-amzn-requestid'];
    private const PII_KEYS = ["authorization", "cookie", "set_cookie", "setcookie", "password", "passcode", "secret", "token", "api_key", "apikey", "access_token", "accesstoken", "refresh_token", "refreshtoken", "client_secret", "clientsecret", "email", "email_address", "emailaddress", "phone", "phone_number", "phonenumber", "address", "street_address", "streetaddress", "street", "city", "postal_code", "postalcode", "zip_code", "zipcode", "first_name", "firstname", "last_name", "lastname", "full_name", "fullname", "username", "user_name", "ip", "ip_address", "ipaddress", "user_agent", "useragent", "referrer", "url", "uri", "query", "latitude", "longitude", "ssn", "social_security_number", "socialsecuritynumber", "tax_id", "taxid", "national_id", "nationalid", "passport_number", "passportnumber", "date_of_birth", "dateofbirth", "birth_date", "birthdate", "headers", "body", "request_headers", "requestheaders", "request_body", "requestbody"];
    /** Word runs matched anywhere inside a key (`billingEmail`, `stripe_secret_key`). */
    private const PII_SEGMENTS = ["_password_", "_passwd_", "_passphrase_", "_secret_", "_token_", "_api_key_", "_access_token_", "_refresh_token_", "_client_secret_", "_authorization_", "_cookie_", "_set_cookie_", "_credential_", "_private_key_", "_access_key_", "_session_id_", "_card_number_", "_credit_card_", "_cvv_", "_cvc_", "_email_", "_email_address_", "_phone_", "_phone_number_", "_address_", "_street_address_", "_postal_code_", "_zip_code_", "_first_name_", "_last_name_", "_full_name_", "_user_name_", "_user_agent_", "_ssn_", "_social_security_number_", "_tax_id_", "_national_id_", "_passport_number_", "_passport_", "_date_of_birth_", "_birth_date_", "_birthdate_", "_dob_"];
}
