<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

/** Sentinel used to distinguish an omitted optional argument from explicit null. */
enum SdkNotGiven
{
    case Value;
}

final readonly class SdkQueryValue
{
    public function __construct(
        public mixed $value,
        public string $style = 'form',
        public bool $explode = true,
    ) {}
}

final readonly class SdkUploadFile
{
    public function __construct(
        public string $data,
        public string $filename,
        public string $contentType = 'application/octet-stream',
    ) {}
}

final readonly class SdkMultipartPart
{
    public function __construct(
        public mixed $value,
        public string $contentType = 'application/json',
    ) {}
}

class ClientAuthConfig
{
    /** @var array<string,string>|null */
    public ?array $headers = null;
}


/**
 * Error reporting. The endpoint/key/environment below are baked in from the
 * dashboard monitoring config, but $enabled is false at rest — this SDK reports
 * nothing until the consumer opts in, either by configuring a ClientConfig whose
 * logging is enabled, or by calling SdkConfig::setLoggingConfig().
 */
class LoggingConfig
{
    public bool $enabled = false;
    public ?string $endpoint = null;
    public ?string $apiKey = null;
    /** Enrichment forwarded with every logged event. */
    public ?string $environment = null;
    public ?string $release = null;
    /** @var array<string, mixed>|null */
    public ?array $user = null;
    /** @var array<string, mixed>|null */
    public ?array $tags = null;
    /** Redact common credentials and direct identifiers before telemetry (default true). */
    public bool $filterPii = true;
}

class RetryConfig
{
    public int $maxAttempts = 3;
    /** @var list<int> */
    public array $retryOn = [408, 425, 429, 500, 502, 503, 504];
    public float $backoffSeconds = 0.5;
    public float $maxBackoffSeconds = 8.0;
}

/** Controls Idempotency-Key generation, so a retried write is not executed twice. */
class IdempotencyConfig
{
    public bool $enabled = true;
    public string $headerName = "Idempotency-Key";
    /** @var string[] */
    public array $methods = ["POST", "PATCH"];
}

/**
 * Per-call options every generated operation accepts as its last argument.
 * Each one applies to that call only, over the client config: headers replace
 * same-named auth and operation headers, retry replaces the retry policy,
 * timeoutSeconds replaces the per-attempt timeout, and idempotencyKey replaces
 * the generated key (an empty string sends none). Streaming operations apply
 * only the headers.
 */
final readonly class RequestOptions
{
    /** @param array<string, string> $headers */
    public function __construct(
        public array $headers = [],
        public ?string $idempotencyKey = null,
        public ?RetryConfig $retry = null,
        public ?float $timeoutSeconds = null,
    ) {}
}

/**
 * A single in-flight HTTP attempt as seen by middleware. Mutate $headers or
 * $body to alter the request before it hits the wire. $meta is a free-form
 * array middleware can use to share state across the chain.
 */
class SdkRequest
{
    public string $method = "";
    public string $url = "";
    /** @var list<string> */
    public array $headers = [];
    public ?string $body = null;
    public string $contentType = "application/json";
    public string $operationId = "";
    public int $attempt = 1;
    /** @var array<string,mixed> */
    public array $meta = [];
}

/**
 * Raw response visible to middleware. $body is the undecoded response text.
 */
class SdkRawResponse
{
    public int $statusCode = 0;
    public string $statusText = "";
    /** @var array<string,string> */
    public array $headers = [];
    public string $body = "";
    public ?string $requestId = null;
    public float $latencySeconds = 0.0;
    public int $attempt = 1;
}

class ClientConfig
{
    public ?string $baseUrl = null;
    public ?ClientAuthConfig $auth = null;
    public ?LoggingConfig $logging = null;
    public ?RetryConfig $retry = null;
    public ?IdempotencyConfig $idempotency = null;
    /** Per-attempt timeout in seconds. */
    public float $timeoutSeconds = 30.0;
    /** @var (callable(SdkResponse<mixed>):void)|null */
    public mixed $onResponse = null;
    /**
     * User middleware chain. Each entry is `callable(SdkRequest, callable(SdkRequest):SdkRawResponse):SdkRawResponse`.
     * Replaced wholesale on configure(); to extend, read the current value
     * and pass a new array including the previous entries.
     *
     * @var list<callable(SdkRequest, callable(SdkRequest): SdkRawResponse): SdkRawResponse>
     */
    public array $middleware = [];
}

/**
 * One Server-Sent Event yielded by SdkClient::stream(). $data is the raw
 * event payload; consumers can JSON-decode it themselves when applicable.
 */
class SdkStreamEvent
{
    public string $event = "message";
    public string $data = "";
    public ?string $id = null;
    public ?int $retry = null;
}

/** Configuration for SdkClient::waitFor(). */
class WaitForConfig
{
    public float $intervalSeconds = 1.0;
    public float $maxIntervalSeconds = 30.0;
    public float $timeoutSeconds = 600.0;
}

class SdkConfig
{
    private static ?ClientConfig $config = null;

    public static function configure(ClientConfig $config): void
    {
        self::$config = $config;
    }

    public static function getConfig(): ClientConfig
    {
        if (self::$config === null) {
            self::$config = new ClientConfig();
            self::$config->baseUrl = "http://localhost:9000/api";
        }
        return self::$config;
    }

    /**
     * Turns SDK logging on and configures it in one call.
     *
     * Logging is OFF by default — this SDK reports nothing until you ask it to.
     * There are exactly two ways to turn it on:
     *
     *     $c = new ClientConfig();
     *     $c->logging = new LoggingConfig();
     *     $c->logging->enabled = true;
     *     SdkConfig::configure($c);                  // at init
     *
     *     SdkConfig::setLoggingConfig();             // any time after
     *
     * Reports go to the endpoint this build was generated with, or to the
     * endpoint you pass; with neither, nothing is sent. Pass a LoggingConfig to
     * set the endpoint, environment, release, tags, etc.
     *
     * This call ALWAYS enables logging — $enabled on the passed config is ignored,
     * because it defaults to false (logging is opt-in) and honouring it would make
     * the obvious "configure and turn on" call a silent no-op. To turn logging back
     * off:  SdkConfig::getConfig()->logging->enabled = false;
     */
    public static function setLoggingConfig(?LoggingConfig $logging = null): LoggingConfig
    {
        $config = static::getConfig();
        if ($logging !== null) {
            // Replaces wholesale: LoggingConfig field defaults already carry the
            // baked endpoint/key/environment, so a fresh one is never blank.
            $config->logging = $logging;
        } elseif ($config->logging === null) {
            $config->logging = new LoggingConfig();
        }
        $config->logging->enabled = true;
        return $config->logging;
    }
}
