<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

/**
 * Envelope returned by the low-level request layer. High-level endpoint
 * methods unwrap `data` automatically.
 */
/** @template T */
class SdkResponse
{
    /** @var T */
    public mixed $data;

    /**
     * @param T $data
     * @param array<string,string> $headers
     */
    public function __construct(
        mixed $data,
        public int $statusCode,
        public array $headers,
        public ?string $requestId,
        public float $latencySeconds,
        public int $attempt,
    ) {
        $this->data = $data;
    }
}

/**
 * Top-level error type for every SDK failure path. Concrete subclasses:
 * SdkValidationError, SdkHttpError, SdkNetworkError, SdkTimeoutError.
 */
abstract class SdkError extends \RuntimeException
{
    /** HTTP status code when produced from an HTTP response, otherwise null. */
    public function statusCode(): ?int
    {
        return null;
    }

    /** Request id captured from the HTTP response, if any. */
    public function requestId(): ?string
    {
        return null;
    }
}

/** Thrown when a method argument fails an OpenAPI constraint pre-flight. */
class SdkValidationError extends SdkError
{
    /**
     * @param array<string,mixed> $meta
     *
     * `errorCode` rather than `code` because Exception::$code is reserved by
     * the PHP runtime for an `int` and re-declaring it as a string is fatal.
     */
    public function __construct(
        public string $field,
        public string $errorCode,
        string $message,
        public array $meta = [],
    ) {
        parent::__construct($message);
    }
}

/** Thrown for any non-2xx HTTP response. */
class SdkHttpError extends SdkError
{
    private const MAX_DETAIL_CODE_POINTS = 512;

    /**
     * @param array<string,string> $headers
     */
    public function __construct(
        public int $statusCode,
        public string $statusText,
        public string $body,
        public array $headers,
        public ?string $requestId = null,
    ) {
        $status = "HTTP {$statusCode}" . ($statusText === '' ? '' : ' ' . trim($statusText));
        $detail = self::errorDetail($body, $headers);
        parent::__construct($detail === null ? $status : $status . ': ' . $detail);
    }

    public function statusCode(): ?int
    {
        return $this->statusCode;
    }

    public function requestId(): ?string
    {
        return $this->requestId;
    }

    /**
     * Builds the status-specific subclass, or the base class for other statuses.
     *
     * @param array<string,string> $headers
     */
    public static function forStatus(int $statusCode, string $statusText, string $body, array $headers, ?string $requestId = null): self
    {
        $class = match (true) {
            $statusCode === 400 => SdkBadRequestError::class,
            $statusCode === 401 => SdkUnauthorizedError::class,
            $statusCode === 403 => SdkPermissionDeniedError::class,
            $statusCode === 404 => SdkNotFoundError::class,
            $statusCode === 409 => SdkConflictError::class,
            $statusCode === 422 => SdkUnprocessableEntityError::class,
            $statusCode === 429 => SdkRateLimitError::class,
            $statusCode >= 500 => SdkInternalServerError::class,
            default => self::class,
        };
        return new $class($statusCode, $statusText, $body, $headers, $requestId);
    }

    /**
     * Decodes the body into the model the API declares for this error, on the
     * same terms as a success response. `body` keeps the raw text.
     *
     * @template T of object
     * @param class-string<T> $className
     * @return T
     */
    public function decodeBody(string $className): object
    {
        return SdkClient::hydrateClass(json_decode($this->body, false, 512, JSON_THROW_ON_ERROR), $className);
    }

    /** @param array<string,string> $headers */
    private static function errorDetail(string $body, array $headers): ?string
    {
        if ($body === '') {
            return null;
        }

        $decoded = json_decode($body);
        if (is_object($decoded)) {
            $error = $decoded->error ?? null;
            $candidate = self::firstString($decoded->message ?? null, $decoded->detail ?? null);
            if ($candidate === null && is_object($error)) {
                $candidate = self::firstString($error->message ?? null, $error->detail ?? null);
            } elseif ($candidate === null && is_string($error)) {
                $candidate = $error;
            }
            return $candidate === null ? null : self::normalizeDetail($candidate);
        }
        if (json_last_error() === JSON_ERROR_NONE) {
            return null;
        }

        foreach ($headers as $name => $value) {
            if (strcasecmp($name, 'content-type') === 0) {
                $mediaType = strtolower(trim(explode(';', $value, 2)[0]));
                if ($mediaType !== '' && !str_starts_with($mediaType, 'text/')) {
                    return null;
                }
                break;
            }
        }
        return self::normalizeDetail($body);
    }

    private static function firstString(mixed ...$values): ?string
    {
        foreach ($values as $value) {
            if (is_string($value)) {
                return $value;
            }
        }
        return null;
    }

    private static function normalizeDetail(string $value): ?string
    {
        $normalized = preg_replace('/\\s+/u', ' ', trim($value));
        if ($normalized === null || $normalized === '' || preg_match('/[\\p{Cc}\\p{Cs}]/u', $normalized) === 1) {
            return null;
        }
        $characters = preg_split('//u', $normalized, -1, PREG_SPLIT_NO_EMPTY);
        if ($characters === false) {
            return null;
        }
        if (count($characters) <= self::MAX_DETAIL_CODE_POINTS) {
            return $normalized;
        }
        return implode('', array_slice($characters, 0, self::MAX_DETAIL_CODE_POINTS)) . '…';
    }
}

/** Thrown for an HTTP 400 response. */
final class SdkBadRequestError extends SdkHttpError
{
}

/** Thrown for an HTTP 401 response. */
final class SdkUnauthorizedError extends SdkHttpError
{
}

/** Thrown for an HTTP 403 response. */
final class SdkPermissionDeniedError extends SdkHttpError
{
}

/** Thrown for an HTTP 404 response. */
final class SdkNotFoundError extends SdkHttpError
{
}

/** Thrown for an HTTP 409 response. */
final class SdkConflictError extends SdkHttpError
{
}

/** Thrown for an HTTP 422 response. */
final class SdkUnprocessableEntityError extends SdkHttpError
{
}

/** Thrown for an HTTP 429 response. */
final class SdkRateLimitError extends SdkHttpError
{
}

/** Thrown for any HTTP 5xx response. */
final class SdkInternalServerError extends SdkHttpError
{
}

/**
 * Thrown when an operation cannot be authenticated by this build: every
 * security alternative the specification offers names a scheme this build
 * exposes no credential for. The call is refused before it is dispatched rather
 * than sent unauthenticated for the server to reject.
 */
class SdkAuthError extends SdkError
{
    /** @param list<string> $requiredSchemes */
    public function __construct(
        public string $operationId,
        public array $requiredSchemes,
    ) {
        parent::__construct(sprintf(
            'Operation %s requires authentication (%s), which this SDK cannot supply',
            $operationId,
            implode(' or ', $requiredSchemes),
        ));
    }
}


/** Thrown for connection / DNS / socket failures. */
class SdkNetworkError extends SdkError
{
    public function __construct(
        \Throwable $cause,
        public ?string $requestId = null,
    ) {
        parent::__construct($cause->getMessage(), 0, $cause);
    }

    public function requestId(): ?string
    {
        return $this->requestId;
    }
}

/** Thrown when a typed streaming payload cannot be decoded as JSON. */
class SdkStreamParseError extends SdkError
{
    public function __construct(
        public string $payload,
        \Throwable $cause,
    ) {
        parent::__construct('Failed to parse typed stream payload', 0, $cause);
    }
}

/** Thrown when a request exceeds its configured timeout. */
class SdkTimeoutError extends SdkError
{
    public function __construct(
        public float $elapsedSeconds,
        public ?string $requestId = null,
    ) {
        parent::__construct(sprintf('Request timed out after %.3fs', $elapsedSeconds));
    }

    public function requestId(): ?string
    {
        return $this->requestId;
    }
}
