<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

interface SdkWireEnum
{
    public static function from(string|int $value): static;
}

interface SdkOpenEnum extends SdkWireEnum, \JsonSerializable, \Stringable
{
    public function getValue(): string|int;
}
