<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

require_once __DIR__ . '/Models/Campaigns.php';
require_once __DIR__ . '/Models/CampaignsPart2.php';
require_once __DIR__ . '/Models/CampaignsPart3.php';
require_once __DIR__ . '/Models/CampaignsPart4.php';
require_once __DIR__ . '/Models/CampaignsPart5.php';
require_once __DIR__ . '/Models/CampaignsPart6.php';
require_once __DIR__ . '/Models/CampaignsPart7.php';
require_once __DIR__ . '/Models/Import.php';
require_once __DIR__ . '/Models/Lists.php';
require_once __DIR__ . '/Models/Media.php';
require_once __DIR__ . '/Models/Miscellaneous.php';
require_once __DIR__ . '/Models/MiscellaneousPart2.php';
require_once __DIR__ . '/Models/MiscellaneousPart3.php';
require_once __DIR__ . '/Models/MiscellaneousPart4.php';
require_once __DIR__ . '/Models/Settings.php';
require_once __DIR__ . '/Models/SettingsPart2.php';
require_once __DIR__ . '/Models/SettingsPart3.php';
require_once __DIR__ . '/Models/SettingsPart4.php';
require_once __DIR__ . '/Models/Shared.php';
require_once __DIR__ . '/Models/Subscribers.php';
require_once __DIR__ . '/Models/SubscribersPart2.php';
require_once __DIR__ . '/Models/SubscribersPart3.php';
require_once __DIR__ . '/Models/SubscribersPart4.php';
require_once __DIR__ . '/Models/Templates.php';
require_once __DIR__ . '/Models/TemplatesPart2.php';
require_once __DIR__ . '/Models/Transactional.php';
