<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

class Validation
{
    public static function validateDate(string $field, string $value): void
    {
        if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $value) || !strtotime($value)) {
            throw new SdkValidationError($field, 'format:date', "Validation failed for '{$field}': must be a valid date (YYYY-MM-DD)");
        }
    }

}
