<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

trait SdkClientMethodsPart3
{
/**
     * Decodes a schema union containing both an open string and a string enum.
     * Known enum values retain their generated type; extension values remain
     * strings so forward-compatible APIs do not reject newly introduced values.
     *
     * @template T of SdkWireEnum
     * @param class-string<T> $className
     * @return T|string
     */
    public static function hydrateStringEnumOrString(mixed $value, string $className): SdkWireEnum|string
    {
        $string = self::stringValue($value);
        try {
            return $className::from($string);
        } catch (\ValueError) {
            return $string;
        }
    }

/**
     * @template T of SdkWireEnum
     * @param list<class-string<T>> $classNames
     * @return T
     */
    public static function hydrateEnumUnion(mixed $value, array $classNames): SdkWireEnum
    {
        $wireValue = self::enumValue($value);
        foreach ($classNames as $className) {
            try {
                return $className::from($wireValue);
            } catch (\ValueError) {
                continue;
            }
        }
        throw new \ValueError('Value is not a member of the declared enum union');
    }

/**
     * @template T of SdkWireEnum
     * @param list<class-string<T>> $classNames
     * @return T|string
     */
    public static function hydrateStringEnumUnion(mixed $value, array $classNames): SdkWireEnum|string
    {
        $wireValue = self::stringValue($value);
        try {
            return self::hydrateEnumUnion($wireValue, $classNames);
        } catch (\ValueError) {
            return $wireValue;
        }
    }

/**
     * @template T
     * @param array<string, mixed> $values
     * @param callable(mixed): T $decoder
     * @return array<string, T>
     */
    public static function mapValues(array $values, callable $decoder): array
    {
        $result = [];
        foreach ($values as $key => $value) {
            $result[$key] = $decoder($value);
        }
        return $result;
    }

/**
     * @template T of object
     * @param SdkResponse<mixed> $response
     * @param class-string<T> $className
     * @return T
     */
    public static function typedData(SdkResponse $response, string $className): object
    {
        $data = $response->data;
        if (!$data instanceof $className) {
            throw new \UnexpectedValueException("Response data is not an instance of {$className}");
        }
        return $data;
    }

/**
     * @param array<string, string> $authHeaders
     * @return list<string>
     */
    private static function buildHeaders(ClientConfig $cfg, array $authHeaders, string $contentType, bool $hasBody): array
    {
        $headers = [];
        $auth = $cfg->auth;
        if ($auth !== null && !empty($auth->headers)) {
            foreach ($auth->headers as $k => $v) {
                $headers[] = "{$k}: {$v}";
            }
        }
        foreach ($authHeaders as $k => $v) {
            $headers[] = "{$k}: {$v}";
        }
        if ($hasBody) {
            $headers[] = "Content-Type: {$contentType}";
        }
        return $headers;
    }    /**
     * Resolves all configured auth into [headers, queryParams]. OAuth2 fetch
     * happens here, before the retry loop starts.
     *
     * @return array{0: array<string,string>, 1: array<string,mixed>}
     */

private static function resolveAuth(ClientConfig $cfg, string $operationId = ''): array
    {
        $headers = [];
        $query = [];

        $auth = $cfg->auth;
        if ($auth === null) {
            return [$headers, $query];
        }


        return [$headers, $query];
    }

/** @return array{0:?string,1:string} */
    private static function prepareBody(mixed $body, string $contentType): array
    {
        if ($body === SdkNotGiven::Value) {
            return [null, $contentType];
        }
        if (str_starts_with(strtolower($contentType), 'multipart/form-data') && is_array($body)) {
            $boundary = '----InterfacerFormBoundary' . bin2hex(random_bytes(12));
            return [
                self::encodeMultipart(self::multipartFields($body), $boundary),
                'multipart/form-data; boundary=' . $boundary,
            ];
        }
        return [self::encodeBody($body, $contentType), $contentType];
    }

private static function encodeBody(mixed $body, string $contentType): ?string
    {
        if ($body === SdkNotGiven::Value) {
            return null;
        }
        if (str_contains(strtolower($contentType), 'json')) {
            return json_encode(self::normalizeJson($body), JSON_THROW_ON_ERROR);
        }
        if (is_string($body)) {
            return $body;
        }
        if ($body === null) {
            return '';
        }
        return self::scalarString($body);
    }

/** @return array<string, mixed> */
    private static function multipartFields(mixed $value): array
    {
        if (!is_array($value)) {
            throw new \UnexpectedValueException('Expected multipart fields');
        }
        $fields = [];
        foreach ($value as $key => $field) {
            if (!is_string($key)) {
                throw new \UnexpectedValueException('Multipart field names must be strings');
            }
            $fields[$key] = $field;
        }
        return $fields;
    }

private static function normalizeJson(mixed $value): mixed
    {
        if ($value === SdkNotGiven::Value) {
            return SdkNotGiven::Value;
        }
        if ($value instanceof \BackedEnum || $value instanceof SdkOpenEnum) {
            return $value instanceof \BackedEnum ? $value->value : $value->getValue();
        }
        if ($value instanceof \JsonSerializable) {
            return self::normalizeJson($value->jsonSerialize());
        }
        if (is_array($value)) {
            $result = [];
            foreach ($value as $key => $item) {
                if ($item !== SdkNotGiven::Value) {
                    $result[$key] = self::normalizeJson($item);
                }
            }
            return $result;
        }
        if (is_object($value)) {
            $result = [];
            foreach (get_object_vars($value) as $key => $item) {
                if ($item !== SdkNotGiven::Value) {
                    $result[$key] = self::normalizeJson($item);
                }
            }
            return $result;
        }
        return $value;
    }

private static function scalarString(mixed $value): string
    {
        if ($value instanceof \BackedEnum) {
            return self::scalarString($value->value);
        }
        if ($value instanceof SdkOpenEnum) {
            return self::scalarString($value->getValue());
        }
        if (is_bool($value)) {
            return $value ? 'true' : 'false';
        }
        if (is_string($value)) {
            return $value;
        }
        if (is_int($value) || is_float($value)) {
            return (string) $value;
        }
        return json_encode(self::normalizeJson($value), JSON_THROW_ON_ERROR);
    }

/**
     * Builds schema-aware multipart data, including repeated file fields.
     * @param array<string, mixed> $fields
     */
    private static function encodeMultipart(array $fields, string $boundary): string
    {
        $out = '';
        $append = function (string $key, mixed $value) use (&$append, &$out, $boundary): void {
            $contentType = null;
            if ($value instanceof SdkMultipartPart) {
                $contentType = $value->contentType;
                $value = $value->value;
            }
            if ($value === SdkNotGiven::Value) {
                return;
            }
            if (is_array($value) && array_is_list($value)) {
                foreach ($value as $item) {
                    $append($key, $item);
                }
                return;
            }
            $safeKey = addcslashes($key, "\\\"");
            $disposition = "Content-Disposition: form-data; name=\"{$safeKey}\"";
            if ($value instanceof SdkUploadFile) {
                $safeFilename = addcslashes($value->filename, "\\\"");
                $disposition .= "; filename=\"{$safeFilename}\"";
                $contentType = $value->contentType;
                $payload = $value->data;
            } elseif (
                $contentType !== null ||
                is_array($value) ||
                (is_object($value) && !($value instanceof \BackedEnum) && !($value instanceof SdkOpenEnum))
            ) {
                $contentType ??= 'application/json';
                $payload = json_encode(self::normalizeJson($value), JSON_THROW_ON_ERROR);
            } elseif ($value === null) {
                $payload = 'null';
            } else {
                $payload = self::scalarString($value);
            }
            $out .= "--{$boundary}\r\n{$disposition}\r\n";
            if ($contentType !== null) {
                $out .= "Content-Type: {$contentType}\r\n";
            }
            $out .= "\r\n{$payload}\r\n";
        };
        foreach ($fields as $key => $value) {
            $append((string) $key, $value);
        }
        $out .= "--{$boundary}--\r\n";
        return $out;
    }

/**
     * @param list<string> $headers
     * @return array{status: int, headers: array<string, string>, body: string}
     */
    private static function dispatch(string $method, string $url, array $headers, ?string $body, float $timeout): array
    {
        if (function_exists('curl_init')) {
            return self::dispatchCurl($method, $url, $headers, $body, $timeout);
        }
        return self::dispatchStream($method, $url, $headers, $body, $timeout);
    }

/**
     * @param list<string> $headers
     * @return array{status: int, headers: array<string, string>, body: string}
     */
    private static function dispatchCurl(string $method, string $url, array $headers, ?string $body, float $timeout): array
    {
        if ($url === '' || $method === '') {
            throw new SdkNetworkError(new \InvalidArgumentException('HTTP method and URL must not be empty'));
        }
        $ch = curl_init();
        if ($ch === false) {
            throw new SdkNetworkError(new \RuntimeException('failed to initialise cURL'));
        }
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HEADER, true);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $method);
        curl_setopt($ch, CURLOPT_TIMEOUT, (int) ceil($timeout));
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, (int) ceil($timeout));
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        if ($body !== null) {
            curl_setopt($ch, CURLOPT_POSTFIELDS, $body);
        }

        $response = curl_exec($ch);
        $errno = curl_errno($ch);
        $errMsg = curl_error($ch);
        $statusCode = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $headerSize = (int) curl_getinfo($ch, CURLINFO_HEADER_SIZE);

        if ($errno === CURLE_OPERATION_TIMEDOUT) {
            throw new SdkTimeoutError($timeout);
        }
        if ($errno !== 0 || !is_string($response)) {
            throw new SdkNetworkError(new \RuntimeException("cURL error: {$errMsg}"));
        }

        $rawHeaders = substr($response, 0, $headerSize);
        $bodyText = substr($response, $headerSize);
        return [
            'status' => $statusCode,
            'headers' => self::parseHeaders($rawHeaders),
            'body' => $bodyText,
        ];
    }
}
