<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

trait SdkClientMethodsPart5
{
/**
     * Polls a long-running operation until it reaches a terminal state.
     * $isTerminal returns ['done' => bool, 'failed' => bool, 'reason' => ?string].
     *
     * @template T
     * @param callable():T $poll
     * @param callable(T):array{done:bool,failed?:bool,reason?:?string} $isTerminal
     * @return T
     */
    public static function waitFor(callable $poll, callable $isTerminal, ?WaitForConfig $config = null): mixed
    {
        $cfg = $config ?? new WaitForConfig();
        $deadline = microtime(true) + $cfg->timeoutSeconds;
        $interval = $cfg->intervalSeconds;
        while (true) {
            $result = $poll();
            $state = $isTerminal($result);
            if (!empty($state['done'])) {
                if (!empty($state['failed'])) {
                    throw new SdkNetworkError(new \RuntimeException('operation failed: ' . ($state['reason'] ?? 'unknown')));
                }
                return $result;
            }
            if (microtime(true) >= $deadline) {
                throw new SdkTimeoutError($cfg->timeoutSeconds);
            }
            $jitter = mt_rand(0, (int) ($cfg->intervalSeconds * 1000)) / 1000.0;
            $wait = min($interval + $jitter, $cfg->maxIntervalSeconds);
            usleep((int) ($wait * 1_000_000));
            $interval = min($interval * 2, $cfg->maxIntervalSeconds);
        }
    }
}
