<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

trait SdkClientMethodsPart2
{
    /**
         * Replaces same-named header lines, compared case-insensitively, with the
         * per-call values.
         *
         * @param list<string> $lines
         * @param array<string, string> $overrides
         * @return list<string>
         */
    private static function withHeaders(array $lines, array $overrides): array
    {
        if ($overrides === []) {
            return $lines;
        }
        // A Cookie override joins the others in joinCookieHeaders instead.
        $names = array_diff(array_map(strtolower(...), array_keys($overrides)), ['cookie']);
        $kept = array_values(array_filter(
            $lines,
            static fn(string $line): bool => !in_array(strtolower(trim((string) strstr($line, ':', true))), $names, true),
        ));
        foreach ($overrides as $name => $value) {
            $kept[] = "{$name}: {$value}";
        }
        return $kept;
    }

    private static function generateIdempotencyKey(): string
    {
        $bytes = random_bytes(16);
        $bytes[6] = chr((ord($bytes[6]) & 0x0f) | 0x40);
        $bytes[8] = chr((ord($bytes[8]) & 0x3f) | 0x80);
        $hex = bin2hex($bytes);
        return substr($hex, 0, 8) . '-' . substr($hex, 8, 4) . '-' . substr($hex, 12, 4) . '-' . substr($hex, 16, 4) . '-' . substr($hex, 20, 12);
    }

    /** @param array<string, mixed> $params */
    private static function buildUrl(string $base, string $path, array $params): string
    {
        // Absolute URLs (used by url-style pagination follow links) bypass the base URL.
        $url = preg_match('#^https?://#i', $path) === 1 ? $path : rtrim($base, '/') . $path;
        $encoded = [];
        foreach ($params as $key => $value) {
            $queryValue = $value instanceof SdkQueryValue
                ? $value
                : new SdkQueryValue($value);
            $value = $queryValue->value;
            if ($value === null || $value === SdkNotGiven::Value) {
                continue;
            }
            $items = is_array($value) ? array_values($value) : [$value];
            $items = array_map(self::scalarString(...), $items);
            $repeated = $queryValue->style === 'form' && $queryValue->explode;
            $delimiter = match ($queryValue->style) {
                'spaceDelimited' => ' ',
                'pipeDelimited' => '|',
                default => ',',
            };
            $wireValues = $repeated ? $items : [implode($delimiter, $items)];
            foreach ($wireValues as $wireValue) {
                $encoded[] = rawurlencode((string) $key) . '=' . rawurlencode($wireValue);
            }
        }
        if (empty($encoded)) {
            return $url;
        }

        // OpenAPI permits a static query fragment in a path key (for example,
        // `/responses?beta=true`). Generated operation parameters extend that
        // fragment, so preserve it and use `&` rather than a second query marker.
        $separator = str_contains($url, '?') ? '&' : '?';
        return $url . $separator . implode('&', $encoded);
    }

    /**
         * Renders a header parameter in OpenAPI's simple style: array items join with
         * commas and object members become key,value pairs, or key=value pairs when
         * exploded. An omitted or null value sends no header.
         */
    public static function headerValue(mixed $value, bool $explode = false): ?string
    {
        if ($value === SdkNotGiven::Value || $value === null) {
            return null;
        }
        return self::simpleValue(self::normalizeJson($value), $explode);
    }

    /**
         * One cookie parameter in OpenAPI's form style, percent-encoded: an exploded
         * array repeats the name and an exploded object sends one pair per member.
         *
         * @return list<string>
         */
    public static function cookie(string $name, mixed $value, bool $explode = true): array
    {
        if ($value === SdkNotGiven::Value || $value === null) {
            return [];
        }
        $wire = self::normalizeJson($value);
        if (!$explode || !is_array($wire)) {
            return [$name . '=' . rawurlencode(self::simpleValue($wire, false))];
        }
        $pairs = [];
        foreach ($wire as $key => $item) {
            $pairs[] = (array_is_list($wire) ? $name : $key) . '=' . rawurlencode(self::simpleValue($item, false));
        }
        return $pairs;
    }

    /**
         * The operation's cookies as one Cookie header value, or null when none is set.
         *
         * @param list<list<string>> $cookies
         */
    public static function cookieHeader(array $cookies): ?string
    {
        $pairs = array_merge(...$cookies);
        return $pairs === [] ? null : implode('; ', $pairs);
    }

    /** The JSON text of a parameter whose content is application/json. */
    public static function jsonParameter(mixed $value): mixed
    {
        if ($value === SdkNotGiven::Value || $value === null) {
            return $value;
        }
        return json_encode(self::normalizeJson($value), JSON_THROW_ON_ERROR);
    }

    private static function simpleValue(mixed $value, bool $explode): string
    {
        if (!is_array($value)) {
            return self::scalarString($value);
        }
        if (array_is_list($value)) {
            return implode(',', array_map(static fn(mixed $item): string => self::simpleValue($item, false), $value));
        }
        $members = [];
        foreach ($value as $key => $item) {
            $members[] = $key . ($explode ? '=' : ',') . self::simpleValue($item, false);
        }
        return implode(',', $members);
    }

    /**
         * Joins every Cookie line into one, at the first one's place, so an apiKey
         * cookie and the operation's cookies travel in the single Cookie header a
         * client may send.
         *
         * @param list<string> $lines
         * @return list<string>
         */
    private static function joinCookieHeaders(array $lines): array
    {
        $isCookie = static fn(string $line): bool => strcasecmp(trim(explode(':', $line, 2)[0]), 'Cookie') === 0;
        $cookies = [];
        foreach ($lines as $line) {
            if ($isCookie($line)) {
                $cookies[] = trim(explode(':', $line, 2)[1] ?? '');
            }
        }
        $joined = [];
        foreach ($lines as $line) {
            if (!$isCookie($line)) {
                $joined[] = $line;
            } elseif ($cookies !== []) {
                $joined[] = 'Cookie: ' . implode('; ', $cookies);
                $cookies = [];
            }
        }
        return $joined;
    }

    /** Encodes one path parameter exactly once as a single RFC 3986 segment. */
    public static function encodePathSegment(mixed $value): string
    {
        // A path array uses the default `simple` style: its members comma-joined.
        if (is_array($value)) {
            return rawurlencode(implode(',', array_map(self::scalarString(...), $value)));
        }
        $value = $value instanceof \BackedEnum
            ? $value->value
            : ($value instanceof SdkOpenEnum ? $value->getValue() : $value);
        return rawurlencode(self::scalarString($value));
    }

    /**
         * @template T of object
         * @param list<class-string<T>> $variants
         * @param array<string,class-string<T>> $mapping
         * @return T
         */
    public static function hydrateUnion(
        mixed $value,
        array $variants,
        ?string $discriminator = null,
        array $mapping = [],
    ): object {
        $object = self::objectValue($value);
        if ($discriminator !== null && property_exists($object, $discriminator)) {
            $wireValue = $object->{$discriminator};
            $className = $mapping[self::scalarString($wireValue)] ?? null;
            if ($className !== null) {
                return self::hydrateClass($object, $className);
            }
        }
        if (count($variants) === 1) {
            $className = $variants[0];
            return self::hydrateClass($object, $className);
        }
        $lastRejection = null;
        if ($discriminator === null) {
            foreach ($variants as $className) {
                try {
                    return self::hydrateClass($object, $className);
                } catch (SdkValidationError|\UnexpectedValueException $error) {
                    $lastRejection = $error;
                    continue;
                }
            }
        }
        $message = $discriminator === null
            ? 'Cannot select a union variant without a discriminator mapping'
            : "Unknown discriminator value for '{$discriminator}'";
        if ($lastRejection !== null) {
            $message .= ': ' . $lastRejection->getMessage();
        }
        throw new \UnexpectedValueException($message, 0, $lastRejection);
    }

    /**
         * @template T of object
         * @param class-string<T> $expectedType
         * @param list<class-string<object>> $variants
         * @param array<string, class-string<object>> $mapping
         * @return T
         */
    public static function hydrateUnionAs(
        mixed $value,
        string $expectedType,
        array $variants,
        ?string $discriminator = null,
        array $mapping = [],
    ): object {
        $result = self::hydrateUnion($value, $variants, $discriminator, $mapping);
        if (!$result instanceof $expectedType) {
            throw new \UnexpectedValueException("Hydrated union does not implement {$expectedType}");
        }
        return $result;
    }

    /**
         * Tries the nominal object-union decoder first, then a structurally typed
         * map decoder when the object does not satisfy any declared model variant.
         *
         * @template T
         * @template U
         * @param callable(mixed): T $objectDecoder
         * @param callable(mixed): U $mapDecoder
         * @return T|U
         */
    public static function hydrateObjectUnionOrMap(
        mixed $value,
        callable $objectDecoder,
        callable $mapDecoder,
    ): mixed {
        try {
            return $objectDecoder($value);
        } catch (SdkValidationError|\UnexpectedValueException) {
            return $mapDecoder($value);
        }
    }

    /**
         * Decodes a union whose wire variants cannot be selected by JSON kind
         * alone, such as a model object or a string-keyed map of models.
         *
         * @template T
         * @param non-empty-list<callable(mixed): T> $decoders
         * @return T
         */
    public static function decodeUnionValue(mixed $value, array $decoders): mixed
    {
        $lastRejection = null;
        foreach ($decoders as $decoder) {
            try {
                return $decoder($value);
            } catch (SdkValidationError|\UnexpectedValueException $error) {
                $lastRejection = $error;
            }
        }
        throw new \UnexpectedValueException('Cannot select a union variant', 0, $lastRejection);
    }

    public static function stringValue(mixed $value): string
    {
        if (!is_string($value)) {
            throw new \UnexpectedValueException('Expected a string value');
        }
        return $value;
    }

    public static function intValue(mixed $value): int
    {
        if (!is_int($value)) {
            throw new \UnexpectedValueException('Expected an integer value');
        }
        return $value;
    }

    public static function floatValue(mixed $value): float
    {
        if (!is_float($value) && !is_int($value)) {
            throw new \UnexpectedValueException('Expected a numeric value');
        }
        return (float) $value;
    }

    public static function boolValue(mixed $value): bool
    {
        if (!is_bool($value)) {
            throw new \UnexpectedValueException('Expected a boolean value');
        }
        return $value;
    }

    /** @return array<array-key, mixed> */
    public static function arrayValue(mixed $value): array
    {
        if (!is_array($value)) {
            throw new \UnexpectedValueException('Expected an array value');
        }
        return $value;
    }
}
