<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

trait SdkClientMethodsPart3
{
    /** @return array<string, mixed> */
    public static function stringMapValue(mixed $value): array
    {
        // A JSON object's names are all strings, so the numeric ones PHP turns
        // into int keys (Asana keys custom fields by gid) are not the stray keys
        // rejected below.
        if (is_object($value)) {
            $result = [];
            foreach (get_object_vars($value) as $key => $item) {
                $result[(string) $key] = $item;
            }
            return $result;
        }
        $map = self::arrayValue($value);
        $result = [];
        foreach ($map as $key => $item) {
            if (!is_string($key)) {
                throw new \UnexpectedValueException('Expected string map keys');
            }
            $result[$key] = $item;
        }
        return $result;
    }

    public static function objectValue(mixed $value): object
    {
        if (!is_object($value)) {
            throw new \UnexpectedValueException('Expected an object value');
        }
        return $value;
    }

    public static function enumValue(mixed $value): int|string
    {
        if (!is_int($value) && !is_string($value)) {
            throw new \UnexpectedValueException('Expected a backed-enum value');
        }
        return $value;
    }

    /**
         * @template T of object
         * @param class-string<T> $className
         * @return T
         */
    public static function hydrateClass(mixed $value, string $className): object
    {
        $object = self::objectValue($value);
        if (!method_exists($className, 'fromObject')) {
            throw new \LogicException("{$className} does not implement fromObject");
        }
        $result = $className::fromObject($object);
        if (!$result instanceof $className) {
            throw new \UnexpectedValueException("{$className} returned an invalid hydrated value");
        }
        return $result;
    }

    public static function hydrateDynamicClass(mixed $value, string $className): object
    {
        $object = self::objectValue($value);
        if (!method_exists($className, 'fromObject')) {
            throw new \LogicException("{$className} does not implement fromObject");
        }
        $result = $className::fromObject($object);
        if (!is_object($result)) {
            throw new \UnexpectedValueException("{$className} returned an invalid hydrated value");
        }
        return $result;
    }

    /**
         * @template T of SdkWireEnum
         * @param class-string<T> $className
         * @return T
         */
    public static function hydrateEnum(mixed $value, string $className): SdkWireEnum
    {
        return $className::from(self::enumValue($value));
    }

    /**
         * Decodes a schema union containing both an open string and a string enum.
         * Known enum values retain their generated type; extension values remain
         * strings so forward-compatible APIs do not reject newly introduced values.
         *
         * @template T of SdkWireEnum
         * @param class-string<T> $className
         * @return T|string
         */
    public static function hydrateStringEnumOrString(mixed $value, string $className): SdkWireEnum|string
    {
        $string = self::stringValue($value);
        try {
            return $className::from($string);
        } catch (\ValueError) {
            return $string;
        }
    }

    /**
         * @template T of SdkWireEnum
         * @param list<class-string<T>> $classNames
         * @return T
         */
    public static function hydrateEnumUnion(mixed $value, array $classNames): SdkWireEnum
    {
        $wireValue = self::enumValue($value);
        foreach ($classNames as $className) {
            try {
                return $className::from($wireValue);
            } catch (\ValueError) {
                continue;
            }
        }
        throw new \ValueError('Value is not a member of the declared enum union');
    }

    /**
         * @template T of SdkWireEnum
         * @param list<class-string<T>> $classNames
         * @return T|string
         */
    public static function hydrateStringEnumUnion(mixed $value, array $classNames): SdkWireEnum|string
    {
        $wireValue = self::stringValue($value);
        try {
            return self::hydrateEnumUnion($wireValue, $classNames);
        } catch (\ValueError) {
            return $wireValue;
        }
    }

    /**
         * @template T
         * @param array<string, mixed> $values
         * @param callable(mixed): T $decoder
         * @return array<string, T>
         */
    public static function mapValues(array $values, callable $decoder): array
    {
        $result = [];
        foreach ($values as $key => $value) {
            $result[$key] = $decoder($value);
        }
        return $result;
    }

    /**
         * @template T of object
         * @param SdkResponse<mixed> $response
         * @param class-string<T> $className
         * @return T
         */
    public static function typedData(SdkResponse $response, string $className): object
    {
        $data = $response->data;
        if (!$data instanceof $className) {
            throw new \UnexpectedValueException("Response data is not an instance of {$className}");
        }
        return $data;
    }

    /**
         * @param array<string, string> $authHeaders
         * @return list<string>
         */
    private static function buildHeaders(ClientConfig $cfg, array $authHeaders, string $contentType, bool $hasBody): array
    {
        $headers = [];
        $auth = $cfg->auth;
        if ($auth !== null && !empty($auth->headers)) {
            foreach ($auth->headers as $k => $v) {
                $headers[] = "{$k}: {$v}";
            }
        }
        foreach ($authHeaders as $k => $v) {
            $headers[] = "{$k}: {$v}";
        }
        if ($hasBody) {
            $headers[] = "Content-Type: {$contentType}";
        }
        return $headers;
    }    /**
     * Resolves all configured auth into [headers, queryParams]. OAuth2 fetch
     * happens here, before the retry loop starts.
     *
     * @return array{0: array<string,string>, 1: array<string,mixed>}
     */

    private static function resolveAuth(ClientConfig $cfg, string $operationId = ''): array
    {
        $headers = [];
        $query = [];

        $auth = $cfg->auth;
        if ($auth === null) {
            return [$headers, $query];
        }


        return [$headers, $query];
    }

    /** @return array{0:?string,1:string} */
    private static function prepareBody(mixed $body, string $contentType): array
    {
        if ($body === SdkNotGiven::Value) {
            return [null, $contentType];
        }
        if (str_starts_with(strtolower($contentType), 'multipart/form-data') && is_array($body)) {
            $boundary = '----InterfacerFormBoundary' . bin2hex(random_bytes(12));
            return [
                self::encodeMultipart(self::multipartFields($body), $boundary),
                'multipart/form-data; boundary=' . $boundary,
            ];
        }
        return [self::encodeBody($body, $contentType), $contentType];
    }

    private static function encodeBody(mixed $body, string $contentType): ?string
    {
        if ($body === SdkNotGiven::Value) {
            return null;
        }
        $mediaType = strtolower(trim(explode(';', $contentType, 2)[0]));
        if (in_array($mediaType, self::JSON_SEQUENCE_MEDIA_TYPES, true)) {
            // One JSON record per line; a JSON text sequence also starts each with RS.
            $separator = $mediaType === 'application/json-seq' ? "\x1E" : '';
            $text = '';
            foreach (is_array($body) && array_is_list($body) ? $body : [$body] as $record) {
                $text .= $separator . json_encode(self::normalizeJson($record), JSON_THROW_ON_ERROR) . "\n";
            }
            return $text;
        }
        if (str_contains(strtolower($contentType), 'json')) {
            return json_encode(self::normalizeJson($body), JSON_THROW_ON_ERROR);
        }
        if (is_string($body)) {
            return $body;
        }
        if ($body === null) {
            return '';
        }
        return self::scalarString($body);
    }

    /** @return array<string, mixed> */
    private static function multipartFields(mixed $value): array
    {
        if (!is_array($value)) {
            throw new \UnexpectedValueException('Expected multipart fields');
        }
        $fields = [];
        foreach ($value as $key => $field) {
            if (!is_string($key)) {
                throw new \UnexpectedValueException('Multipart field names must be strings');
            }
            $fields[$key] = $field;
        }
        return $fields;
    }

    private static function normalizeJson(mixed $value): mixed
    {
        if ($value === SdkNotGiven::Value) {
            return SdkNotGiven::Value;
        }
        if ($value instanceof \BackedEnum || $value instanceof SdkOpenEnum) {
            return $value instanceof \BackedEnum ? $value->value : $value->getValue();
        }
        if ($value instanceof \JsonSerializable) {
            return self::normalizeJson($value->jsonSerialize());
        }
        if (is_array($value)) {
            $result = [];
            foreach ($value as $key => $item) {
                if ($item !== SdkNotGiven::Value) {
                    $result[$key] = self::normalizeJson($item);
                }
            }
            return $result;
        }
        if (is_object($value)) {
            $result = [];
            foreach (get_object_vars($value) as $key => $item) {
                if ($item !== SdkNotGiven::Value) {
                    $result[$key] = self::normalizeJson($item);
                }
            }
            return $result;
        }
        return $value;
    }

    private static function scalarString(mixed $value): string
    {
        if ($value instanceof \BackedEnum) {
            return self::scalarString($value->value);
        }
        if ($value instanceof SdkOpenEnum) {
            return self::scalarString($value->getValue());
        }
        if (is_bool($value)) {
            return $value ? 'true' : 'false';
        }
        if (is_string($value)) {
            return $value;
        }
        if (is_int($value) || is_float($value)) {
            return (string) $value;
        }
        return json_encode(self::normalizeJson($value), JSON_THROW_ON_ERROR);
    }
}
