<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

trait SdkClientMethodsPart1
{
    /** `stripeSecretKey`, `API-Key` and `first name` become `stripe_secret_key`, `api_key`, `first_name`. */
    private static function normalizePiiKey(int|string $key): string
    {
        $split = preg_replace('/([a-z0-9])([A-Z])/', '$1_$2', (string) $key) ?? (string) $key;
        return preg_replace('/[^a-z0-9]/', '_', strtolower($split)) ?? strtolower($split);
    }

    private static function isPiiKey(int|string $key): bool
    {
        $normalized = self::normalizePiiKey($key);
        if (in_array($normalized, self::PII_KEYS, true)) {
            return true;
        }
        $padded = '_' . $normalized . '_';
        foreach (self::PII_SEGMENTS as $segment) {
            if (str_contains($padded, $segment)) {
                return true;
            }
        }
        return false;
    }

    /** Recursively redacts common credential and direct-identifier fields. */
    private static function sanitizeTelemetry(mixed $value, bool $enabled): mixed
    {
        if (!$enabled || !is_array($value)) {
            return $value;
        }
        $output = [];
        foreach ($value as $key => $item) {
            $output[$key] = self::isPiiKey($key)
                ? '[REDACTED]'
                : self::sanitizeTelemetry($item, $enabled);
        }
        return $output;
    }

    /**
         * @param array<string, mixed> $query
         * @param array<string, mixed> $extraHeaders
         * @return SdkResponse<mixed>
         */
    public static function request(
        string $method,
        string $path,
        ?ClientConfig $config = null,
        array $query = [],
        mixed $body = null,
        string $contentType = 'application/json',
        ?string $returnType = null,
        string $decoder = 'json',
        string $operationId = '',
        array $extraHeaders = [],
        ?RequestOptions $requestOptions = null,
    ): SdkResponse {
        $cfg = $config ?? SdkConfig::getConfig();
        $retry = $requestOptions->retry ?? $cfg->retry ?? new RetryConfig();
        $idem = $cfg->idempotency ?? new IdempotencyConfig();
        $upperMethod = strtoupper($method);
        // Pre-resolve auth (OAuth2 fetch happens once, before retries).
        [$authHeaders, $authQuery] = self::resolveAuth($cfg, $operationId);
        $mergedQuery = empty($authQuery) ? $query : array_merge($query, $authQuery);
        $url = self::buildUrl($cfg->baseUrl ?? '', $path, $mergedQuery);
        [$bodyString, $contentType] = self::prepareBody($body, $contentType);

        // One idempotency key per logical request — reused across retries so
        // the server can deduplicate.
        $idempotencyKey = self::resolveIdempotencyKey($requestOptions?->idempotencyKey, $idem, $upperMethod);

        $timeoutSeconds = $requestOptions->timeoutSeconds ?? $cfg->timeoutSeconds;
        $terminal = function (SdkRequest $req) use ($timeoutSeconds): SdkRawResponse {
            return self::coreTransport($req, $timeoutSeconds);
        };
        $dispatch = self::composeMiddleware($cfg->middleware, $terminal);

        for ($attempt = 1; $attempt <= $retry->maxAttempts; $attempt++) {
            // Build per-attempt headers (auth re-applied for OAuth refresh tolerance).
            $headers = self::buildHeaders($cfg, $authHeaders, $contentType, $bodyString !== null);
            foreach ($extraHeaders as $k => $v) {
                if ($v !== SdkNotGiven::Value && $v !== null) {
                    $wireValue = $v instanceof \BackedEnum
                        ? $v->value
                        : ($v instanceof SdkOpenEnum ? $v->getValue() : $v);
                    $headers[] = "{$k}: " . self::scalarString($wireValue);
                }
            }
            $headers = self::joinCookieHeaders(self::withHeaders($headers, $requestOptions->headers ?? []));
            if ($idempotencyKey !== null) {
                $headers[] = "{$idem->headerName}: {$idempotencyKey}";
            }
            $sdkReq = new SdkRequest();
            $sdkReq->method = $upperMethod;
            $sdkReq->url = $url;
            $sdkReq->headers = $headers;
            $sdkReq->body = $bodyString;
            $sdkReq->contentType = $contentType;
            $sdkReq->operationId = $operationId;
            $sdkReq->attempt = $attempt;

            try {
                $raw = $dispatch($sdkReq);
            } catch (SdkTimeoutError $e) {
                if ($attempt < $retry->maxAttempts) {
                    self::sleepBackoff($retry, $attempt, null);
                    continue;
                }
                throw self::logError($cfg, $upperMethod, $path, $operationId, $e);
            } catch (SdkNetworkError $e) {
                if ($attempt < $retry->maxAttempts) {
                    self::sleepBackoff($retry, $attempt, null);
                    continue;
                }
                throw self::logError($cfg, $upperMethod, $path, $operationId, $e);
            }

            if ($raw->statusCode >= 200 && $raw->statusCode < 300) {
                $data = self::decode($raw->body, $decoder, $returnType);
                $envelope = new SdkResponse($data, $raw->statusCode, $raw->headers, $raw->requestId, $raw->latencySeconds, $raw->attempt);
                if (is_callable($cfg->onResponse)) {
                    ($cfg->onResponse)($envelope);
                }
                return $envelope;
            }

            if ($attempt < $retry->maxAttempts && self::shouldRetry($upperMethod, $raw->statusCode, $retry->retryOn)) {
                self::sleepBackoff($retry, $attempt, $raw->headers['retry-after'] ?? null);
                continue;
            }

            throw self::logError($cfg, $upperMethod, $path, $operationId, SdkHttpError::forStatus($raw->statusCode, $raw->statusText, $raw->body, $raw->headers, $raw->requestId));
        }

        // Reachable only if maxAttempts is misconfigured to 0.
        throw self::logError($cfg, $upperMethod, $path, $operationId, new SdkNetworkError(new \RuntimeException("Request '{$operationId}' produced no attempts")));
    }

    /**
         * Fires the error logger (when configured) and returns the error unchanged
         * so terminal failures can be wrapped inline at each throw site. Delivery is
         * best-effort with a short timeout; a logging failure never masks the
         * originating error. eventId lets the backend deduplicate retried deliveries.
         */
    private static function logError(
        ClientConfig $cfg,
        string $method,
        string $path,
        string $operationId,
        SdkError $error,
    ): SdkError {
        $logging = $cfg->logging;
        if ($logging === null || !$logging->enabled || $logging->endpoint === null) {
            return $error;
        }

        $errorObj = [
            'name' => (new \ReflectionClass($error))->getShortName(),
            'message' => $error->getMessage(),
            'stack' => $error->getTraceAsString(),
        ];
        // Structured frames with original-source context, so the dashboard shows
        // your code directly (PHP is not minified, so no source maps are needed).
        $frames = self::buildFrames($error);
        if (!empty($frames)) {
            $errorObj['frames'] = $frames;
        }

        $payload = [
            'eventId' => self::generateIdempotencyKey(),
            'timestamp' => gmdate('Y-m-d\TH:i:s\Z'),
            'level' => 'error',
            'operationId' => $operationId,
            'method' => $method,
            'path' => $path,
            'error' => $errorObj,
        ];
        if ($error->statusCode() !== null) {
            $payload['statusCode'] = $error->statusCode();
        }
        if ($error->requestId() !== null) {
            $payload['requestId'] = $error->requestId();
        }
        if ($logging->environment !== null) {
            $payload['environment'] = $logging->environment;
        }
        if ($logging->release !== null) {
            $payload['release'] = $logging->release;
        }
        if ($logging->user !== null) {
            $payload['user'] = $logging->user;
        }
        if ($logging->tags !== null) {
            $payload['tags'] = $logging->tags;
        }

        $headers = ['Content-Type: application/json'];
        if ($logging->apiKey !== null) {
            $headers[] = 'Authorization: Bearer ' . $logging->apiKey;
        }

        $ch = curl_init($logging->endpoint);
        if ($ch === false) {
            return $error;
        }
        $payloadJson = json_encode(self::sanitizeTelemetry($payload, $logging->filterPii), JSON_THROW_ON_ERROR);
        curl_setopt_array($ch, [
            CURLOPT_POST => true,
            CURLOPT_POSTFIELDS => $payloadJson,
            CURLOPT_HTTPHEADER => $headers,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT => 2,
        ]);
        curl_exec($ch);

        return $error;
    }

    /**
         * A few source lines around a frame, so the dashboard can show the original
         * code for languages that are not minified (no source maps required).
         *
         * @return array<string, mixed>
         */
    private static function sourceContext(?string $file, int $lineno): array
    {
        if ($file === null || $file === '' || $lineno < 1 || !is_file($file)) {
            return [];
        }
        $lines = @file($file, FILE_IGNORE_NEW_LINES);
        if ($lines === false || $lineno > count($lines)) {
            return [];
        }
        $idx = $lineno - 1;
        $ctx = ['contextLine' => $lines[$idx]];
        $pre = array_slice($lines, max(0, $idx - 5), min(5, $idx));
        $post = array_slice($lines, $idx + 1, 5);
        if (!empty($pre)) {
            $ctx['preContext'] = $pre;
        }
        if (!empty($post)) {
            $ctx['postContext'] = $post;
        }
        return $ctx;
    }

    /** A frame is in-app unless it lives in an installed package (vendor) or a phar. */
    private static function frameInApp(?string $file): bool
    {
        return $file !== null && strpos($file, '/vendor/') === false && strpos($file, 'phar://') === false;
    }

    /**
         * Structured stack frames with original-source context, innermost first.
         * PHP getTrace() locations are off-by-one (a frame is the call site of the
         * NEXT function), so the throw location leads and each entry shifts down.
         *
         * @return array<int, array<string, mixed>>
         */
    private static function buildFrames(\Throwable $error): array
    {
        $frames = [];
        $file = $error->getFile();
        $line = $error->getLine();
        foreach ($error->getTrace() as $t) {
            $fn = ($t['class'] ?? '') . ($t['type'] ?? '') . $t['function'];
            $frame = [
                'function' => $fn,
                'filename' => $file,
                'lineno' => $line,
                'inApp' => self::frameInApp($file),
            ];
            $frames[] = array_merge($frame, self::sourceContext($file, (int) $line));
            $file = $t['file'] ?? $file;
            $line = $t['line'] ?? $line;
        }
        return $frames;
    }

    /**
         * Composes a middleware stack around a terminal handler. The first
         * middleware in $stack is the outermost.
         *
         * @param list<callable(SdkRequest, callable(SdkRequest): SdkRawResponse): SdkRawResponse> $stack
         * @param callable(SdkRequest):SdkRawResponse $terminal
         * @return callable(SdkRequest):SdkRawResponse
         */
    private static function composeMiddleware(array $stack, callable $terminal): callable
    {
        if (empty($stack)) {
            return $terminal;
        }
        $next = $terminal;
        for ($i = count($stack) - 1; $i >= 0; $i--) {
            $mw = $stack[$i];
            $captured = $next;
            $next = function (SdkRequest $req) use ($mw, $captured): SdkRawResponse {
                return $mw($req, $captured);
            };
        }
        return $next;
    }

    /** Innermost handler: performs the actual curl exchange. */
    private static function coreTransport(SdkRequest $req, float $timeoutSeconds): SdkRawResponse
    {
        $started = microtime(true);
        $result = self::dispatch($req->method, $req->url, $req->headers, $req->body, $timeoutSeconds);
        $raw = new SdkRawResponse();
        $raw->statusCode = $result['status'];
        $raw->statusText = self::statusText($result['status']);
        $raw->headers = $result['headers'];
        $raw->body = $result['body'];
        $raw->requestId = self::findRequestId($result['headers']);
        $raw->latencySeconds = microtime(true) - $started;
        $raw->attempt = $req->attempt;
        return $raw;
    }

    /** An explicit key wins and an empty one sends none; otherwise the config policy decides. */
    private static function resolveIdempotencyKey(?string $explicit, IdempotencyConfig $idem, string $method): ?string
    {
        if ($explicit !== null) {
            return $explicit === '' ? null : $explicit;
        }
        return $idem->enabled && in_array($method, $idem->methods, true) ? self::generateIdempotencyKey() : null;
    }
}
