<?php

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

declare(strict_types=1);

namespace listmonk_unofficial_sdk;

trait SdkClientMethodsPart2
{
/**
     * Replaces same-named header lines, compared case-insensitively, with the
     * per-call values.
     *
     * @param list<string> $lines
     * @param array<string, string> $overrides
     * @return list<string>
     */
    private static function withHeaders(array $lines, array $overrides): array
    {
        if ($overrides === []) {
            return $lines;
        }
        $names = array_map(strtolower(...), array_keys($overrides));
        $kept = array_values(array_filter(
            $lines,
            static fn (string $line): bool => !in_array(strtolower(trim((string) strstr($line, ':', true))), $names, true),
        ));
        foreach ($overrides as $name => $value) {
            $kept[] = "{$name}: {$value}";
        }
        return $kept;
    }

private static function generateIdempotencyKey(): string
    {
        $bytes = random_bytes(16);
        $bytes[6] = chr((ord($bytes[6]) & 0x0f) | 0x40);
        $bytes[8] = chr((ord($bytes[8]) & 0x3f) | 0x80);
        $hex = bin2hex($bytes);
        return substr($hex, 0, 8) . '-' . substr($hex, 8, 4) . '-' . substr($hex, 12, 4) . '-' . substr($hex, 16, 4) . '-' . substr($hex, 20, 12);
    }

/** @param array<string, mixed> $params */
    private static function buildUrl(string $base, string $path, array $params): string
    {
        // Absolute URLs (used by url-style pagination follow links) bypass the base URL.
        $url = preg_match('#^https?://#i', $path) === 1 ? $path : rtrim($base, '/') . $path;
        $encoded = [];
        foreach ($params as $key => $value) {
            $queryValue = $value instanceof SdkQueryValue
                ? $value
                : new SdkQueryValue($value);
            $value = $queryValue->value;
            if ($value === null || $value === SdkNotGiven::Value) {
                continue;
            }
            $items = is_array($value) ? array_values($value) : [$value];
            $items = array_map(self::scalarString(...), $items);
            $repeated = $queryValue->style === 'form' && $queryValue->explode;
            $delimiter = match ($queryValue->style) {
                'spaceDelimited' => ' ',
                'pipeDelimited' => '|',
                default => ',',
            };
            $wireValues = $repeated ? $items : [implode($delimiter, $items)];
            foreach ($wireValues as $wireValue) {
                $encoded[] = rawurlencode((string) $key) . '=' . rawurlencode($wireValue);
            }
        }
        if (empty($encoded)) {
            return $url;
        }

        // OpenAPI permits a static query fragment in a path key (for example,
        // `/responses?beta=true`). Generated operation parameters extend that
        // fragment, so preserve it and use `&` rather than a second query marker.
        $separator = str_contains($url, '?') ? '&' : '?';
        return $url . $separator . implode('&', $encoded);
    }

/** Encodes one path parameter exactly once as a single RFC 3986 segment. */
    public static function encodePathSegment(mixed $value): string
    {
        // A path array uses the default `simple` style: its members comma-joined.
        if (is_array($value)) {
            return rawurlencode(implode(',', array_map(self::scalarString(...), $value)));
        }
        $value = $value instanceof \BackedEnum
            ? $value->value
            : ($value instanceof SdkOpenEnum ? $value->getValue() : $value);
        return rawurlencode(self::scalarString($value));
    }

/**
     * @template T of object
     * @param list<class-string<T>> $variants
     * @param array<string,class-string<T>> $mapping
     * @return T
     */
    public static function hydrateUnion(
        mixed $value,
        array $variants,
        ?string $discriminator = null,
        array $mapping = [],
    ): object {
        $object = self::objectValue($value);
        if ($discriminator !== null && property_exists($object, $discriminator)) {
            $wireValue = $object->{$discriminator};
            $className = $mapping[self::scalarString($wireValue)] ?? null;
            if ($className !== null) {
                return self::hydrateClass($object, $className);
            }
        }
        if (count($variants) === 1) {
            $className = $variants[0];
            return self::hydrateClass($object, $className);
        }
        $lastRejection = null;
        if ($discriminator === null) {
            foreach ($variants as $className) {
                try {
                    return self::hydrateClass($object, $className);
                } catch (SdkValidationError|\UnexpectedValueException $error) {
                    $lastRejection = $error;
                    continue;
                }
            }
        }
        $message = $discriminator === null
            ? 'Cannot select a union variant without a discriminator mapping'
            : "Unknown discriminator value for '{$discriminator}'";
        if ($lastRejection !== null) {
            $message .= ': ' . $lastRejection->getMessage();
        }
        throw new \UnexpectedValueException($message, 0, $lastRejection);
    }

/**
     * @template T of object
     * @param class-string<T> $expectedType
     * @param list<class-string<object>> $variants
     * @param array<string, class-string<object>> $mapping
     * @return T
     */
    public static function hydrateUnionAs(
        mixed $value,
        string $expectedType,
        array $variants,
        ?string $discriminator = null,
        array $mapping = [],
    ): object {
        $result = self::hydrateUnion($value, $variants, $discriminator, $mapping);
        if (!$result instanceof $expectedType) {
            throw new \UnexpectedValueException("Hydrated union does not implement {$expectedType}");
        }
        return $result;
    }

/**
     * Tries the nominal object-union decoder first, then a structurally typed
     * map decoder when the object does not satisfy any declared model variant.
     *
     * @template T
     * @template U
     * @param callable(mixed): T $objectDecoder
     * @param callable(mixed): U $mapDecoder
     * @return T|U
     */
    public static function hydrateObjectUnionOrMap(
        mixed $value,
        callable $objectDecoder,
        callable $mapDecoder,
    ): mixed {
        try {
            return $objectDecoder($value);
        } catch (SdkValidationError|\UnexpectedValueException) {
            return $mapDecoder($value);
        }
    }

/**
     * Decodes a union whose wire variants cannot be selected by JSON kind
     * alone, such as a model object or a string-keyed map of models.
     *
     * @template T
     * @param non-empty-list<callable(mixed): T> $decoders
     * @return T
     */
    public static function decodeUnionValue(mixed $value, array $decoders): mixed
    {
        $lastRejection = null;
        foreach ($decoders as $decoder) {
            try {
                return $decoder($value);
            } catch (SdkValidationError|\UnexpectedValueException $error) {
                $lastRejection = $error;
            }
        }
        throw new \UnexpectedValueException('Cannot select a union variant', 0, $lastRejection);
    }

public static function stringValue(mixed $value): string
    {
        if (!is_string($value)) {
            throw new \UnexpectedValueException('Expected a string value');
        }
        return $value;
    }

public static function intValue(mixed $value): int
    {
        if (!is_int($value)) {
            throw new \UnexpectedValueException('Expected an integer value');
        }
        return $value;
    }

public static function floatValue(mixed $value): float
    {
        if (!is_float($value) && !is_int($value)) {
            throw new \UnexpectedValueException('Expected a numeric value');
        }
        return (float) $value;
    }

public static function boolValue(mixed $value): bool
    {
        if (!is_bool($value)) {
            throw new \UnexpectedValueException('Expected a boolean value');
        }
        return $value;
    }

/** @return array<array-key, mixed> */
    public static function arrayValue(mixed $value): array
    {
        if (!is_array($value)) {
            throw new \UnexpectedValueException('Expected an array value');
        }
        return $value;
    }

/** @return array<string, mixed> */
    public static function stringMapValue(mixed $value): array
    {
        // A JSON object's names are all strings, so the numeric ones PHP turns
        // into int keys (Asana keys custom fields by gid) are not the stray keys
        // rejected below.
        if (is_object($value)) {
            $result = [];
            foreach (get_object_vars($value) as $key => $item) {
                $result[(string) $key] = $item;
            }
            return $result;
        }
        $map = self::arrayValue($value);
        $result = [];
        foreach ($map as $key => $item) {
            if (!is_string($key)) {
                throw new \UnexpectedValueException('Expected string map keys');
            }
            $result[$key] = $item;
        }
        return $result;
    }

public static function objectValue(mixed $value): object
    {
        if (!is_object($value)) {
            throw new \UnexpectedValueException('Expected an object value');
        }
        return $value;
    }

public static function enumValue(mixed $value): int|string
    {
        if (!is_int($value) && !is_string($value)) {
            throw new \UnexpectedValueException('Expected a backed-enum value');
        }
        return $value;
    }

/**
     * @template T of object
     * @param class-string<T> $className
     * @return T
     */
    public static function hydrateClass(mixed $value, string $className): object
    {
        $object = self::objectValue($value);
        if (!method_exists($className, 'fromObject')) {
            throw new \LogicException("{$className} does not implement fromObject");
        }
        $result = $className::fromObject($object);
        if (!$result instanceof $className) {
            throw new \UnexpectedValueException("{$className} returned an invalid hydrated value");
        }
        return $result;
    }

public static function hydrateDynamicClass(mixed $value, string $className): object
    {
        $object = self::objectValue($value);
        if (!method_exists($className, 'fromObject')) {
            throw new \LogicException("{$className} does not implement fromObject");
        }
        $result = $className::fromObject($object);
        if (!is_object($result)) {
            throw new \UnexpectedValueException("{$className} returned an invalid hydrated value");
        }
        return $result;
    }

/**
     * @template T of SdkWireEnum
     * @param class-string<T> $className
     * @return T
     */
    public static function hydrateEnum(mixed $value, string $className): SdkWireEnum
    {
        return $className::from(self::enumValue($value));
    }
}
